### ISSUE TITLE
Import de masse de BDD externe

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#107]
Si des échantillons ont un champ mal rempli (comme la date de _sample_date_ dans l'exemple), les objets **col.object** sont importés mais pas leur description **col.sample**. Ce qui pour un utilisateur revient à aucun import  des échantillons défectueux mais laisse des traces dans la BDD avec des objets incomplets. L'utilisateur ne peut pas savoir quel échantillon est mal spécifié dans son fichier CSV.

**Exemple** : 

cybercarotheque,"LAU15-P2","01_core","CAROTHEQUE","Ã‰tat normal",6.064683,44.96775,"2018-01-21 16:48:43.19973+01","2015","","LAUVITEL","IGSN:IEFRA05I2","{""site"" : """", ""type_de_materiel"" : ""Sediment"", ""longueur"" : 25, ""pi"" : ""FOUINAT Laurent (ORCID:0000-0002-1231-917X)"", ""mission"" : ""Carottage Spatial Crue Mai 2015"", ""numero_ordre_section"" : 1, ""profondeur_top"" : 0, ""profondeur_bottom"" : 25, ""diametre"" : 63, ""corer_type"" : ""gravityCorer"", ""bathy"" : null, ""URL_objet"" : """"}"

![message_import_bddexterne](https://user-images.githubusercontent.com/7202505/35196533-895423ca-fed3-11e7-9785-64959cab02e7.png)

**En base**
select * from col.object where uid >= 109 and uid <= 329 and uid not in (select uid from col.sample where uid >= 109 and uid <= 329)

**Proposition**
Il ne faudrait alors pas importer aucun des objets tant qu'il reste des lignes problématiques. Proposer un message de log plus explicite : 
- ligne x du fichier CSV : date mal formattée (un champs YYYY-MM-DD est attendu). 
Faire corriger jusqu'à bon fonctionnement.

Sinon, ce serait bien de pouvoir supprimer des échantillons que l'on vient d'importer en masse, si l'on a les droits de gestion de projet au moins. Les fichiers CSV mal faits, c'est fréquent !

**Comment by equinton** [comment]
Rajouter un contrôle de format de date lors du contrôle des fichiers d'import
Voir s'il est possible de gérer des transactions lors de l'écriture (commit, rollback)

**Comment by equinton** [comment]
feature-import-mars18:

- contrôle sur les dates rajouté
- mise en place d'une transaction (commit/rollback) pour éviter les imports partiels
