### ISSUE TITLE
Contrôler les identifiants externes pour import fichier CSV

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#108]
COLLEC fait bien une proposition d'appariement (très pratique !) entre valeurs d'attributs externes et liste des paramètres définis : 

- lieux de prélèvement (sampling_place_name), 
- type d'échantillon (sample_type_name), 
- projet (project_name), 
- état de l'objet (object_status_name).

![controle_lieux_prelevements_import_bddexterne_valider](https://user-images.githubusercontent.com/7202505/35196650-3e99cd1a-fed5-11e7-8e25-365aa5872a05.png)

Mais il ne le fait pas bien pour _identifier_type_code_ (l'identifiant externe de l'échantillon). Dans l'exemple, il devrait proposer igsn.

**Comment by equinton** [comment]
Non reproduit. Il faudrait avoir le contenu du fichier à importer ainsi que le contenu de la table des identifiants secondaires pour vérifier le fonctionnement.

**Comment by equinton** [comment]
Il est probable que ce soit un problème de casse non identique entre le fichier d'import et le contenu en base de données.

**Comment by equinton** [comment]
Modification de la comparaison en transformant tous les libellés en majuscules (inhibition de la comparaison par casse)
