### ISSUE TITLE
Aucun email ou message renvoyé par la procédure de récupération (oublie mot de passe) si casse différente

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#118]
Afin d'éviter des erreurs d'envoi d'email selon la configuration du serveur postfix à cause de la casse, passer l'adresse email en minuscule systématiquement.

**Comment by exmackina** [comment]
Après reproduction, il semble que cela soit indépendant de la configuration du serveur postfix -> bug ?
En fait, lorsqu'on lance la procédure de récupération, après avoir saisi son adresse email et validé, s'il y a la moindre différence de casse avec celle déjà enregistrée, alors cela renvoie à la page d'accueil sans message et sans envoyer d'email -> il serait préférable d'avoir un message explicatif
Techniquement getFromMail($mail) de identification.class.php recherche par une requête SQL avec l’opérateur de comparaison “=” qui est sensible à la casse avec PostgreSQL (contrairement à MySQL) -> pistes de solution : convertir en minuscules les 2 chaînes, utiliser un opérateur insensible à la casse comme ILIKE (mais : "This is not in the SQL standard but is a PostgreSQL extension")

Même si la recherche d'adresse n'est pas liée à la configuration du serveur postfix, ce dernier point n'en demeure pas moins valide. L'envoie pourrait échouer selon la configuration.

**Comment by equinton** [comment]
il vaut mieux utiliser la fonction lower dans la recherche plutôt que l'opérateur ilike, trop peu connu.

**Comment by exmackina** [comment]
corrigé avec https://github.com/Irstea/collec/commit/0cde62370f90fe9c238b193b74e679cb9028c0fa
framework/identification/identification.class.php   @777             $sql .= " where lower(mail) = lower(:mail)";
