### ISSUE TITLE
Mouvement petit terminal : flasher des QRcodes entree/sortie/validation à la place ?

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#125]
Une solution pratique aux mouvements d'échantillons serait de flasher une suite d'instructions (en se passant d'écran donc) : 
- ENTREE (QRcode = instruction entrée) - flasher le container - flasher les échantillons - VALIDER
- SORTIE (QRcode = instruction sortie) - flasher le container - flasher les échantillons - (QRcode = motif de sortie éventuellement) - VALIDER

La mémoire d'une douchette permet d'enregistrer jusqu'à 400 items. En utilisant le menu Entrées/Sorties par lot adapté en fonction, on se passe ainsi de l'achat de terminaux mobiles ou tablettes dans les salles de rangement.

**Comment by equinton** [comment]
???

C'est le fonctionnement de : Entrée/sortie par lots. La douchette stocke les infos, qui sont déchargées dans l'interface. Il est possible d'indiquer quel code est un container, les mouvements sont générés automatiquement.

Ça fonctionne également pour les sorties.
