### ISSUE TITLE
Mise à jour par import en masse d'échantillons externes

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#126]
Il est possible de faire en sorte que l'import en masse d'échantillons externe 
- soit créé des échantillons, 
- soit mette à jour des échantillons existant dans la base de données (identifiés par dbuid_origin). 
C'est une proposition qui règle partiellement le bug 107 (Import de masse de BDD externe) en permettant de mettre à jour les infos qui ne vont pas. 
Les fichiers impactés sont : 
modules/classes/sample.class.php sur la fonction verifyBeforeImport
/modules/gestion/sample.php
au niveau de importStage3, ligne 310
En ajoutant ceci : 
/*
           * CPP: Recuperer l'uid de l'objet si la base de donnees origine est celle "courante", i.e. du serveur
           * Permet d'autoriser les mises a jour. La PK declaree de sample est sample_id (voir modules/classes/sample.class.php)
           */
            $ori = explode(":", $row["dbuid_origin"]);
            if ($_SESSION["APPLI_code"] == $ori[0]) {
                $sample["uid"] = $ori[1];
		//récupérer l'identifiant de l'échantillon à mettre à jour (un UID --> un sample_id)
                $previoussample = $dataClass->lire($sample["uid"]);
                $sample["sample_id"] = $previoussample["sample_id"];
            }

**Comment by equinton** [comment]
Cas présenté : réimport d'un échantillon exporté dans la base d'origine, après traitement sur le terrain.

Recherche sur le dbuid_origin, sachant qu'il peut s'agir de la même base de données.

**Comment by equinton** [comment]
Recherche de dbuid_origin dans la base de données, quel que soit le contexte (échantillon réintégré ou réimport d'un échantillon préalablement existant provenant d'une autre base)

feature-import-mars18
