### ISSUE TITLE
Pouvoir supprimer des container vides. 

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#128]
vi /home/collec/collec-lienss/collec-release-1.2/modules/classes/storage.class.php
getNbFromContainer interroge lastmovement au lieu de storage

-- FIX l 255
 $sql = "select count (*) as nombre from container c
                                join col.last_movement using (container_id)
                                where c.uid = :uid";

Permet de supprimer le container tranquillement

**Comment by equinton** [comment]
Le problème, c'est que si on supprime un container qui a été utilisé pour des mouvements (c'est la requête initiale), on perd l'information pour tous les autres containers ou échantillons qui ont été stockés à un moment ou à un autre.

Dans la requête corrigée, on ne fait que vérifier que le container est vide. S'il a été utilisé, l'info est perdue (je ne suis même pas sûr que la suppression fonctionne alors, à cause des contraintes d'intégrité).

À valider sur le plan fonctionnel.
