### ISSUE TITLE
Etiquette : cd 

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#129]
Pour un échantillon, cd doit valoir sample_date (date de prélèvement de l'échantillon) 
Pour un container, c'est la date de dernier mouvement (permet d'avoir une idée de la "fraîcheur" de l'étiquette).

vi /home/collec/collec-lienss/collec-release-1.2/modules/classes/object.class.php
Fonction generateQrcode, ligne 347

$sql = "select uid, identifier as id, clp_classification as clp, '' as pn,
                                        '$APPLI_code' as db,
                                        '' as prj, storage_product as prod,
                                         wgs84_x as x, wgs84_y as y, null as cd,
                    null as metadata, null as loc
                                        from object
                                        join container using (uid)
                                        join container_type using (container_type_id)
                                        where uid in ($uids)
                                        UNION
                                        select uid, identifier as id, clp_classification as clp, protocol_name as pn,
                                        '$APPLI_code' as db,
                                        project_name as prj, storage_product as prod,
                                         wgs84_x as x, wgs84_y as y, sample_creation_date as cd,
                    metadata::varchar, sampling_place_name as loc
                                        from object
                                        join sample using (uid)
                                        join sample_type using (sample_type_id)
                                        join project using (project_id)
                    left outer join sampling_place using (sampling_place_id)
                                        left outer join container_type using (container_type_id)
                                        left outer join operation using (operation_id)
                                        left outer join protocol using (protocol_id)
                                        where uid in ($uids)
                        ";
						
----------------------- 
Remplacé par 
-----------------------
$sql = "select uid, identifier as id, clp_classification as clp, '' as pn,
                                        '$APPLI_code' as db,
                                        '' as prj, storage_product as prod,
                                         wgs84_x as x, wgs84_y as y, storage_date as cd,
                    null as metadata, null as loc
                                        from object
                                        join container using (uid)
                                        join container_type using (container_type_id)
										left outer join last_movement using (uid)
                                        where uid in ($uids)
                                        UNION
                                        select uid, identifier as id, clp_classification as clp, protocol_name as pn,
                                        '$APPLI_code' as db,
                                        project_name as prj, storage_product as prod,
                                         wgs84_x as x, wgs84_y as y, sample_date as cd,
                    metadata::varchar, sampling_place_name as loc
                                        from object
                                        join sample using (uid)
                                        join sample_type using (sample_type_id)
                                        join project using (project_id)
                    left outer join sampling_place using (sampling_place_id)
                                        left outer join container_type using (container_type_id)
                                        left outer join operation using (operation_id)
                                        left outer join protocol using (protocol_id)
                                        where uid in ($uids)
                        ";

**Comment by equinton** [comment]
Je ne comprend pas le besoin. L'étiquette est intangible et ne doit pas être liée à un mouvement.
Il faut que tu m'expliques le cas d'usage que tu rencontres qui nécessite cette évolution.

**Comment by cplumejeaud** [comment]
En fait, avoir l'information cd permet d'avoir une idée de la date
d'émission de l'étiquette et donc de sa "fraicheur" ou péremption.
Les étiquettes aussi périment, à l'usage (après pas mal de discussion)

Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr

2018-03-01 12:15 GMT+01:00 equinton <notifications@github.com>:

**Comment by equinton** [comment]
Rajouter la date du dernier mouvement de l'objet pour générer les étiquettes

**Comment by exmackina** [comment]
#140
