### ISSUE TITLE
 listes déroulantes -> disposer de l'autocomplétion automatique

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#139]
Les listes déroulantes que souhaitent créer les utilisateurs sont souvent longues (> 10 items)
La complétion automatique serait un vrai plus. 
Que ce soit dans les métadonnées, ou les lieux de prélèvement.

**Comment by equinton** [comment]
Voir du côté de http://jqueryui.com/autocomplete/#combobox

**Comment by equinton** [comment]
Voir du côté de http://jqueryui.com/autocomplete/#combobox

**Comment by cplumejeaud** [comment]
Salut Eric

Juste, pour préciser, les listes déroulantes sont décisives lors de la
création ou modification d'échantillon, pour le choix de lieux de
prélèvement, et aussi pour le choix des items dans les listes de
métadonnées.
Je ne suis pas sure que tu aies vu pour les listes déroulantes dans les
métadonnées.

Bises
Christine

Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr

2018-03-07 13:49 GMT+01:00 equinton <notifications@github.com>:
