### ISSUE TITLE
Réduire la vitesse d'impression de la Zebra sous Debian/GNOME pour QR code sans bavure

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#147]
Réduire la vitesse à 1 po/s (pouce par seconde) pour éviter les "bavures" sur les QR codes au bout de quelques étiquettes (dès 4-5) imprimées d'affilées et éviter ainsi qu'ils soient illisibles.
![capture du 2018-03-09 17-36-12](https://user-images.githubusercontent.com/26461464/37218346-751dda10-23c0-11e8-8678-6c9b8787c306.png)

**Comment by exmackina** [comment]
![qr code lisible pas lisible](https://user-images.githubusercontent.com/26461464/37280404-f3b80c0e-25ed-11e8-9094-70243ddb04e7.png)

**Comment by exmackina** [comment]
Sous Windows, à la vitesse de 10,1cm/s des "bavures" peuvent apparaître rendant le QR code illisible, tandis qu'à 5cm/s la qualité est meilleure.
![param speed](https://user-images.githubusercontent.com/26461464/37297871-1cd356e4-261f-11e8-84b4-6ec1cf923a4c.png)

**Comment by equinton** [comment]
Information insérée dans la FAQ du site web
