### ISSUE TITLE
metadonnee

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#153]
-  probleme avec le type : liste à choix multiple : on n'a pas trouvé comment sélectionner plusieurs choix

- On n'a pas compris le fonctionnement de checkbox. On pensait devoir mettre des valeurs à cliquer mais on n'a pas vu comment le faire.

- On ne comprend pas le sens de unité de mesure (en + obligatoire). On met quoi par exemple si on veut mettre des noms de personnes ?

- Le carré blanc autour de chaque élément de métadonnée  n'est pas assez visible 

- on a eu l'impression que la première fois que l'on remplit, on peut valider même si tous les champs obligatoires ne sont pas remplis.

**Comment by equinton** [comment]
feature-import-mars18
