### ISSUE TITLE
Données de formulaire réinitialisées si champ select obligatoire non rempli

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#155]
Si le champ sample_type_id est vide à la création d'un échantillon,
alors en validant on obtient bien un message d'erreur (Le champ sample_type_id est obligatoire, mais n'a pas été renseigné.) **mais par contre les champs sont vidés.**

<<En fait, si les champs sont vidés, c'est que c'est le serveur qui a détecté le problème, et pas la page web : il réaffiche alors le formulaire vierge... Le problème, c'est que le type d'échantillon est un champ "select" qui ne supporte pas nativement l'attribut required : il faut donc modifier la fonction javascript $('#sampleForm').submit(function(event) { pour s'assurer que la valeur soit remplie et déclencher, si ce n'est pas le cas, un event.preventDefault pour bloquer l'envoi vers le serveur, avec affichage d'un message (alert()).>> Eric

**Comment by equinton** [comment]
Feature-database-mars18
