### ISSUE TITLE
menage de masse

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#156]
Suite à des imports en masse qui n'ont pas posé problème (pas encore compris pourquoi), j'ai besoin de faire du ménage en masse de container et d'échantillon. Est ce qu'il y a une commande pour le faire ?

**Comment by quidoz** [comment]
Suite à des imports en masse qui ONT posé problème (pas encore compris pourquoi), j'ai besoin de faire du ménage en masse de container et d'échantillon. Est ce qu'il y a une commande pour le faire ?

**Comment by equinton** [comment]
Il faudrait que tu précises ce qu'il s'est passé, pour qu'on puisse voir où il y a un souci.
Pour supprimer des containers ou des échantillons, il faut le faire par des commandes sql : 

- repérer le premier uid concerné, puis : 
delete from object_identifier where uid > xxx;
delete from event where uid > xxx;
delete from booking where uid > xxx;
delete from document where uid > xxx;
delete from storage where uid > xxx;
delete from subsample ss using sample s where s.sample_id = ss.sample_id and uid > xxx;
delete from sample where uid > xxx;
delete from object where uid > xxx;

**Comment by quidoz** [comment]
Merci pour le script. J'ai ajouté en avant dernière ligne delete from col.container where uid > xxx ; pour détruire les containeurs.

L'ajout d'échantillon se passe bien excepté les métadonnées (peut être que j'ai mal écrit le json) et l'affectation dans le bon container. Il ne le trouve pas et donc en créé à chaque ligne d'échantillon...

[copie_ecran.pdf](https://github.com/Irstea/collec/files/1819655/copie_ecran.pdf)
 
[Latifrons_INES_RB14_masse.pdf](https://github.com/Irstea/collec/files/1819662/Latifrons_INES_RB14_masse.pdf)
ps : ca serait bien de support le csv ou ods comme type de fichiers

**Comment by equinton** [comment]
Semble être en doublon de #94

**Comment by quidoz** [comment]
J'ai testé sans mettre les métadonnées (json) - supprimer les colonnes . Ca ne marche pas non plus mais peut être que les métadonnées sont obligatoires vu que j'ai mis des champs obligatoires dedans
