### ISSUE TITLE
échantillons dérivés : pouvoir importer la filiation par import d'échantillons externes

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#157]
J'ai l'impression qu'on a oublié de préciser comment faire pour importer une filiation existante entre des échantillons lors de leur import dans COLLEC par import d'échantillons externes. Je me trompe ?

**Comment by equinton** [comment]
C'est un bug que j'ai déjà repéré. Je vais le traiter prochainement, probablement cette semaine.

>

**Comment by equinton** [comment]
feature-import-mars18
