### ISSUE TITLE
recherche avec les metadonnées 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#159]
Il ne s'agit pas d'un bug mais d'une interrogation. vous avez fait le choix de rattacher les métadonnées au type d'échantillon. Ce choix rend difficile la recherche avec les métadonnées, car il faut déjà sélectionner le type d'échantillon avant de faire la recherche par métadonnée.  
Dans mon cas, les metadonnées sont commun pour un protocole. Dans les métadonnées j'ai mis des éléments très génériques style taxon, récolteur et donc je ne peux pas chercher dans ma base de données tous les échantillons d'un taxon donné. Vous allez me dire que collec-science n'est pas fait pour cela ...

**Comment by equinton** [comment]
C'est quasi insoluble... Lors des protocoles d'échantillonnage, il est fréquent de rajouter des métadonnées pour indiquer de nouvelles valeurs (taxon, puis, pour un otolithe, sa provenance - gauche ou droite, etc.). Certains types d'échantillons peuvent être communs à des collections différentes. Ainsi, nous gérons plusieurs collections qui traitent de poissons, et les types d'échantillons sont alors identiques.

Pour l'instant, le logiciel affiche les champs de métadonnées utilisables dans les recherches à partir des types d'échantillons.

À voir s'il faut afficher la liste complète à chaque fois ou pas : point à débattre, il y  a du pour (réponse à ta demande) et du contre (liste qui peut vite devenir longue).

**Comment by equinton** [comment]
Script à utiliser : 
with js as (select json_array_elements(metadata_schema::json) elements from col.metadata)
select distinct elements->>'name' fieldname
from js
where elements->>'isSearchable' = 'yes';

**Comment by equinton** [comment]
Implémenté dans feature-import-mars18
