### ISSUE TITLE
visibilite des informations

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#160]
Il ne s'agit pas d'un bug mais d'une question pour savoir si j'ai tout compris dans les droits
Si j'ai bien configuré mon application, j'ai l'impression que 
- toutes les informations sur tous les projets sont visibles par tout le monde. Par contre tout le monde n'a pas le droit de les modifier.
- les containers (famille, type, conteneurs) sont définis hors des projets
- les échantillons (famille, type, échantillons) sont définis par projet

**Comment by equinton** [comment]
oui, c'est tout à fait ça.
