### ISSUE TITLE
Modèles d'étiquette non éditable avec branche develop 19 mars 2018

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#163]
Il ne semble plus possible d'éditer/ajouter un modèle d'étiquette.
![collec labo chrono dev 1](https://user-images.githubusercontent.com/26461464/37776559-d6991186-2de5-11e8-8acf-c7ea328c470b.png)

**Comment by equinton** [comment]
Déjà corrigé dans la branche feature-import-mars18
