### ISSUE TITLE
Le Lieu de prélèvement disparaît du formulaire de recherche même si bien appliqué

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#169]
Après avoir lancé une recherche d'échantillons, le champ "Lieu de prélèvement" est vidé même s'il est bien appliqué dans le filtre de recherche.
![collec chrono environnement](https://user-images.githubusercontent.com/26461464/37909377-fff1bd8a-310a-11e8-9ba0-5610324c9b4c.png)
Comportement attendu : le champ "Lieu de prélèvement" garde la valeur donné lors de la recherche.

**Comment by equinton** [comment]
Le pb survient quand une collection est sélectionnée. Le lieu de prélèvement, lorsqu'il est rafraîchi lors de la requête Ajax, n'est pas correctement positionné par rapport à la valeur de $search.
