### ISSUE TITLE
Problème d'export des metadata en "Fichier CSV"

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#170]
Lors de l'export des échantillons en "Fichier CSV", certaines valeurs de metadata posent problème en affichage par colonne (voir extrait ci-dessous) :
Une liste de valeurs (de combobox) affiche "Array".
L’absence d'un champ décale les colonnes vers la gauche. 

metadata                                                          	|pi    	|utilisateurs  	|mission
--------------------------------------------------------------------|-------|---------------|---------------
{"pi":"Toto","utilisateurs":["Toto"],"mission":"Quinte Bay 2008"} 	|Toto  	|Array         	|Quinte Bay 2008
{"pi":"Toto","utilisateurs":["Toto"],"mission":"Quinte Bay 2008"} 	|Toto  	|Array         	|Quinte Bay 2008
{"pi":"Toto","utilisateurs":["Toto"],"mission":"Quinte Bay 2008"} 	|Toto  	|Array         	|Quinte Bay 2008
{"pi":"Toto","utilisateurs":["Toto"],"mission":"Quinte Bay 2008"} 	|Toto  	|Array         	|Quinte Bay 2008
{"utilisateurs":["Titi","Toto"],"mission":"Mongolie 2009"}        	|Array 	|Mongolie 2009 	|
{"utilisateurs":["Titi","Toto"],"mission":"Mongolie 2009"}        	|Array 	|Mongolie 2009 	|

**Comment by equinton** [comment]
Il s'agit du fichier pour impression externe, et non pas le fichier d'export vers une autre base de données.
