### ISSUE TITLE
La photo des échantillons n'apparaît pas dans la liste d'échantillons d'un conteneur

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#174]
Lorsqu'on consulte les détails d'un conteneur, la photo des échantillons n'apparaît pas :
/index.php?module=containerDisplay&uid=103
![collec labo chrono dev 3](https://user-images.githubusercontent.com/26461464/38140552-8327cb64-3434-11e8-8d3b-8b92d4a616af.png)

Tandis que la photo apparaît bien lorsqu'on recherche des échantillons :
/index.php?module=sampleList
![collec labo chrono dev 2](https://user-images.githubusercontent.com/26461464/38140556-87edf04c-3434-11e8-9ff4-7ec17278fb94.png)

**Comment by equinton** [comment]
corrigé dans feature_eq_avril_18
C'était valable également pour les containers rattachés
