### ISSUE TITLE
Scan multiple - problème si plusieurs fois le même container

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#176]
Lors d' "Entrée / sortie par scan multiple" problème avec :
A10
ZAAJChrono:366
ZAAJChrono:367
A3
ZAAJChrono:283
**A10**
ZAAJChrono:358

revient à tord à  :
A10
ZAAJChrono:366
ZAAJChrono:367
A3
ZAAJChrono:283
ZAAJChrono:358

tandis que la saisie ci-dessous est bien prise en compte
A10
ZAAJChrono:366
A10
ZAAJChrono:367
A10
ZAAJChrono:358
A3
ZAAJChrono:283

Cela est utile lorsqu'on a oublié de scanner des échantillons et qu'on les rajoute par la suite, ou lorsqu'on importe les lieux de stockage d'une feuille de calcul non triée par lieux de stockage.

**Comment by equinton** [comment]
Corrigé dans feature_eq_avril_18
