### ISSUE TITLE
Impression PDF de liste d'étiquettes pour plus de 300 items

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#178]
Elle plante le serveur qui répond que l'URL est trop longue. Cela peut-être gênant pour des utilisateurs qui souhaitent garder une copie PDF des étiquettes générées pour leur campagne pour un lot d'échantillon. 
Le cas se présente à la mi avril 2018. 

Que faire ? Ajuster mieux les paramètres mémoire de java (pour FOP) ou du serveur PHP ?

**Comment by equinton** [comment]
Vu. Il faut passer par une requête de type post pour que les variables ne soient plus dans le corps de la requête, et cela impose l'ouverture d'un onglet dédié aux étiquettes (pas de possibilité de faire un retour arrière vers une requête post).

Je regarde les modifs à faire dans la semaine.

Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cplumejeaud** [comment]
ok, merci

Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr

**Comment by equinton** [comment]
feature_eq_avril_18
