### ISSUE TITLE
Process pour modifier en masse les métadonnées avec un tableur

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#181]
Pour modifier en masse les métadonnées :
- Exporter avec “Export vers autre base“
- Ajouter au fichier les colonnes de métadonnées nécessaires et les préfixer par md_
- Editer les données à modifier
- Importer par Objet > Import d'échantillons externes
![capture du 2018-05-02 11-50-50](https://user-images.githubusercontent.com/26461464/39517082-1f2f1f2e-4dff-11e8-9eee-309598c03351.png)

Astuce : pour avoir les métadonnées facilement éditables sous un tableur et donc en colonnes et non en JSON, exporter avec “Fichier CSV”

**Comment by exmackina** [comment]
NB : Il peut paraître plus facile d'ajouter/modifier par la suite des données (métadonnées) avec l'outil d' _import d'échantillons externes_ que de le faire au début, lors de l'_import de masse_. Dans ce cas je recommande d'importer en 2 étapes : d'abord les données juste nécessaires pour l'_import de masse_, et ensuite le reste avec l'_import d'échantillons externes_ en passant par l'_Export vers autre base_ qui donne le modèle pré-rempli du document attendu pour l'import (avec les bonnes colonnes).

**Comment by equinton** [comment]
L'importation de masse sera complétée pour ajouter l'importation des métadonnées sous forme de champ, ce qui évitera de recourir à deux opérations.

**Comment by equinton** [comment]
Documentation mise à jour dans le site en s'inspirant fortement de la démarche : 
https://www.collec-science.org/2017/09/04/les-importations-de-masse/
