### ISSUE TITLE
Update vers base COLLEC20 : script col_alter_1.2-1.2.3.sql à corriger

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#182]
Le script collec/install/pgsql/col_alter_1.2-1.2.3.sql présente 1 souci : 
 6 est censé est l'ID du group import, mais quand on travaille sur une base qui a déjà des groupes, ce n'est pas le cas. Il faut utiliser ceci à la place de '6' : select max(aclgroup_id) from aclgroup
--------------
Suggestion pour le fix
--------------
insert into aclgroup (aclgroup_id, groupe, aclgroup_id_parent) 
values((select max(aclgroup_id)+1 from aclgroup), 'import', 3);

insert into aclacl (aclaco_id, aclgroup_id) values (6, (select max(aclgroup_id) from aclgroup));

-- donner le droit à l'admin de faire des imports
insert into acllogingroup(acllogin_id, aclgroup_id) 
values (1, (select max(aclgroup_id)+1 from aclgroup));

select setval('aclaco_aclaco_id_seq', (select max(aclaco_id) from aclaco));
select setval('aclgroup_aclgroup_id_seq', (select max(aclgroup_id) from aclgroup));

**Comment by equinton** [comment]
Corrigé dans hotfix-2.0.1
