### ISSUE TITLE
Update collec2.0 : script SQL à compléter

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#183]
L'erreur se voit au moment du listing des échantillons qui rend une page vide

TEST : 

https://siza.univ-lr.fr/collec20/index.php?moduleBase=sample&action=List&isSearch=1&name=&collection_id=4&uid_min=0&uid_max=0&sample_type_id=&sampling_place_id=&object_status_id=1&select_date=&date_from=08%2F05%2F2017&date_to=08%2F05%2F2018&metadata_field%5B%5D=&metadata_value%5B%5D=&metadata_field%5B%5D=&metadata_value%5B%5D=&metadata_field%5B%5D=&metadata_value%5B%5D=

Page vide pour cette requete SQL : 

select s.sample_id, s.uid, s.collection_id, collection_name, s.sample_type_id, s.dbuid_origin, sample_type_name, s.sample_creation_date, s.sampling_date, s.metadata, s.expiration_date, s.parent_sample_id, st.multiple_type_id, s.multiple_value, st.multiple_unit, mt.multiple_type_name, so.identifier, so.wgs84_x, so.wgs84_y, so.object_status_id, object_status_name, 
 pso.uid as parent_uid, pso.identifier as parent_identifier, container_type_name, clp_classification, operation_id, protocol_name, protocol_year, protocol_version, operation_name, operation_order,operation_version, metadata_schema, document_id, identifiers, movement_date, movement_type_name, movement_type_id, sp.sampling_place_id, sp.sampling_place_name, lm.line_number, lm.column_number, container_uid, oc.identifier as container_identifier 
  from sample s 
 join sample_type st on (st.sample_type_id = s.sample_type_id) 
 join collection p on (p.collection_id = s.collection_id) 
 join object so on (s.uid = so.uid) 
 left outer join sampling_place sp on (sp.sampling_place_id = s.sampling_place_id) 
 left outer join object_status os on (so.object_status_id = os.object_status_id) 
 left outer join sample ps on (s.parent_sample_id = ps.sample_id) 
 left outer join object pso on (ps.uid = pso.uid)	
 left outer join container_type ct using (container_type_id) 
 left outer join operation using (operation_id) 
 left outer join protocol using (protocol_id) 
 left outer join multiple_type mt on (st.multiple_type_id = mt.multiple_type_id) 
 left outer join last_photo on (so.uid = last_photo.uid) 
 left outer join v_object_identifier voi on (s.uid = voi.uid) 
 left outer join last_movement lm on (s.uid = lm.uid) 
 left outer join object oc on (container_uid = oc.uid) 
 left outer join movement_type using (movement_type_id) 
 left outer join metadata using (metadata_id) 
 where s.collection_id = 4 and so.object_status_id = 1

LOGS
 
 [Tue May 08 12:26:03.288685 2018] [:error] [pid 12204] [client 10.5.5.146:20601] 
 PHP Fatal error:  Uncaught ObjetBDDException: SQLSTATE[42501]: Insufficient privilege: 7 ERREUR:  
 droit refus\xc3\xa9 pour la relation last_movement in 
 /home/collec/collec20/collec-release-2.0/plugins/objetBDD-3.5/ObjetBDD.php:1808\n
 Stack trace:\n
 #0 /home/collec/collec20/collec-release-2.0/plugins/objetBDD-3.5/ObjetBDD.php(1841): ObjetBDD->executeAsPrepared('select s.sample...', Array)\n
 #1 /home/collec/collec20/collec-release-2.0/modules/classes/sample.class.php(392): ObjetBDD->getListeParamAsPrepared('select s.sample...', Array)\n
 #2 /home/collec/collec20/collec-release-2.0/modules/gestion/sample.php(31): Sample->sampleSearch(Array)\n
 #3 /home/collec/collec20/collec-release-2.0/framework/controller.php(479): include('/home/collec/co...')\n
 #4 /home/collec/collec20/collec-release-2.0/index.php(3): include('/home/collec/co...')\n
 #5 {main}\n  thrown in /home/collec/collec20/collec-release-2.0/plugins/objetBDD-3.5/ObjetBDD.php on line 1808, 
 referer: https://siza.univ-lr.fr/collec20/index.php?module=sampleList
 
Solution : rajouter dans install/pgsql/col_alter_1.2-1.2.3.sql la ligne suivante
 
 ALTER TABLE col.last_movement
  OWNER TO collec;

**Comment by equinton** [comment]
Le problème des droits est complexe à traiter, et ne fonctionne que si l'utilisateur est collec (pas le cas forcément pour toutes les implémentations).
Si la mise à jour est effectuée avec le script upgrade-1.2-1.2.3.sql (ou sa version .sh), les droits sont correctement positionnés (connexion en tant que collec, qui devient propriétaire des objets créés). DAns le cas contraire, il faut gérer manuellement les droits en les adaptant au contexte.

**Comment by equinton** [comment]
Ajout de la gestion de l'exception dans l'application, pour éviter la page blanche.
Ajout d'un commentaire explicatif en début de script
hotfix-2.0.1
