### ISSUE TITLE
Creating new user provokes a "date/time field value out of range" error

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#185]
Ce problème a été invoqué en avril - connexion en anglais https://localhost/index.php?module=setlanguage&langue=en ne fonctionnait pas.

Connecté en tant que admin **en anglais** création des nouveaux utilisateur https://localhost/index.php?module=loginChange&id=0 ne fonctionne pas. En français ça fonctionne. Output de postgresql log est identique, alors ce vieux bug est toujours vivant : 

> 2018-05-18 11:59:51.443 CEST [22988] collec@collec ERROR:  date/time field value out of range: "2018-18-05"
2018-05-18 11:59:51.443 CEST [22988] collec@collec HINT:  Perhaps you need a different "datestyle" setting.
2018-05-18 11:59:51.443 CEST [22988] collec@collec STATEMENT:  insert into logingestion(datemodif, login, actif, password, is_clientws) values ($1, $2, $3, $4, $5) RETURNING id

Je suppose que toutes les modifications de date sont infectées. C'est pourquoi le problème de modification de mot de passe se pose ces derniers jours. à vérifier les logs - peut-être un autre _date/time field value out of range_ nous attends dans un coin.

**Comment by equinton** [comment]
Merci de préciser la version de Collec-Science installée

**Comment by equinton** [comment]
Corrigé un peu partout dans l'ensemble du logiciel dans hotfix-2.0.1
Merci de tester avec la version hotfix-2.0.1 avant mise en prod.

**Comment by zer0mode** [comment]
Connections + modifications de mdp en anglais/français testés. Maintenant ça fonctionne.
