### ISSUE TITLE
Les listes de choix sont illisibles sur de petits écrans

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#186]
Sur des PDA ou des tablettes les listes de choix sont illisibles car elles tronquent leur contenu textuel au milieu des lettres. Il faut ajuster le style CSS. 

Cette proposition est une solution qui fonctionne  : 

Editer display/CSS/blue.css et rajouter au début de ce fichier dans COLLEC. 
select {
    font: inherit;
}

**Comment by equinton** [comment]
blue.css n'est pas utilisé dans l'application, c'est bootstrap-prototypephp.css qui est chargé.
L'ajout de l'entrée ne semble pas être efficace pour afficher correctement les select.

Il faut utiliser ça : 
@media (max-width: 991px) {
	select {min-height: 2em;}
}
