### ISSUE TITLE
Créer une faq décrivant comment gérer le multi-instance (entrées dns)

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#190]
Dans le site collec-science.org à partir de la doc

**Comment by zer0mode** [comment]
Voici [les étapes](https://github.com/zer0mode/CS-repo/blob/master/multi-instance_config.md) pour mettre en place le multi-instance.

Un ensemble de paires key-value pourrait être pré-configuré dans le fichier [param.ini](https://github.com/Irstea/collec/blob/hotfix-2.0.2/param.ini) pour simplifier l'activation des multi-instances.

Le caractère `;` devrait être utilisé pour les commentaires au lieu de `#` (voir l'exemple dans le guide).

**Comment by equinton** [comment]
Le ; est supporté nativement pour les commentaires (fonction parse_ini_file de php).
APPLI_titre est obsolète, et géré maintenant dans la base de données elle-même (table dbparam, valeur APPLI_title).
Corrections de param.ini et param.inc.php.dist réalisées

**Comment by zer0mode** [comment]
A partir de ligne https://github.com/Irstea/collec/blob/07d0e20b28945905b8ca0466e649e29ef6db5307/param.ini#L6
il faut enlever les <kbd>;</kbd>

_(release 2.1)_
