### ISSUE TITLE
BD transfer

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#194]
Action :
Transfert de la BD (updated 1.2 -> 1.2.3 + 1.2.3 -> 2.0) sur la VM (version 2.0.1) _//export avec pg_dump to DBtransfer_
sur une install locale collec (version 2.0.1) _//import DBtransfer_

Resultat :
Pour se connecter avec succès il faut configurer des nom et mdp de postgres identiques à ceux de la VM dans pg_hba.conf.
output de navigateur :
>La base de données n'est pas dans la version attendue (2.0). Version actuelle :

Une fois le postgres user est identique le chargement du contenu (objets + mouvement) ne fonctionne pas - on obtient une page blanche dans navigateur. La partie gacl n'est pas affectée. Voici l'extrait d'apache error.log

>[Fri Jun 01 11:57:24.666210 2018] [php7:error] [pid 30373] [client 127.0.0.1:41460] PHP Fatal error:  Uncaught TokenException: File param/id_collec not readable in /var/www/html/collec-science/collec201/framework/identification/token.class.php:50\nStack trace:\n#0 /var/www/html/collec-science/collec201/framework/controller.php(332): Token->__construct('param/id_collec', 'param/id_collec...')\n#1 /var/www/html/collec-science/collec201/index.php(3): include('/var/www/html/c...')\n#2 {main}\n  thrown in /var/www/html/collec-science/collec201/framework/identification/token.class.php on line 50, referer: https://localhost/index.php?module=connexion

**Comment by equinton** [comment]
Il y a plusieurs causes possibles aux différents problèmes rencontrés. Je soupçonne que le fichier param.inc.php soit mal configuré au regard de l'installation de l'application dans la machine virtuelle.

Pour la connexion à la base de données, il y a plusieurs raisons possibles, mais c'est probablement le fichier pg_hba.conf qui n'est pas en adéquation avec la configuration dans param.inc.php (ou param.ini). Un exemple de pg_hba.conf : 
# "local" is for Unix domain socket connections only

local   all             all                                     peer
local	all		quinton					md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
Dans cet exemple, on peut se connecter à toute base de données en utilisant l'adresse : 
`pgsql:host=127.0.0.1;dbname=xxx`
ou bien : 
`pgsql:host=localhost;dbname=xxx`
avec le login quinton

Pour ce qui concerne le message d'erreur, la nouvelle procédure d'installation introduit la génération d'une clé de chiffrement asymétrique, pour éviter d'utiliser la même clé que celle du protocole https : 
```
# generate rsa key for encrypted tokens
echo "generate encryption keys for identification tokens"
openssl genpkey -algorithm rsa -out collec/param/id_collec -pkeyopt rsa_keygen_bits:2048
openssl rsa -in collec/param/id_collec -pubout -out collec/param/id_collec.pub
chown www-data collec/param/id_collec
```
Pour régler au moins ce souci, soit il faut lancer le code précédent, soit il faut modifier le fichier param.inc.php pour désactiver l'utilisation de la clé générée.

En résumé, je pense qu'on est confronté à des problèmes de configuration, il faudrait savoir comment a été gérée l'installation.

**Comment by zer0mode** [comment]
* Pour l'info :

Je n'ai pas pu reproduire cette erreur. La config qui ne fonctionne pas est sur un ordinateur loin de chez moi. Mais on peut considérer que les pages blanches avec les erreurs d'identification indiquées sont effectivement liés à la configuration. 

_Solution : soit il faut revérifier les détails de connexion à la BD dans **`param.inc.php`** soit dans **`pg_hba.conf`**._
