### ISSUE TITLE
Erreur lors du sous-échantillonage

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#195]
Erreur obtenue lors de la validation de la création d'un sous échantillon : SQLSTATE[42703]: Undefined column: 7 ERROR: column "subsampling_date" of relation "subsample" does not exist LINE 1: insert into subsample(sample_id, subsampling_date, movement_...

**Comment by equinton** [comment]
Corrigé en hotfix-2.0.2
La colonne avait été renommée par erreur dans l'application, alors que la base de données conservait la valeur initiale correcte.
