### ISSUE TITLE
importer un fichier csv pour alimenter le champ taxon d'une métadonnée

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#196]
Bonjour
Pour remplir les listes déroulantes du champ taxon de ma métadonnée Metadonnee_Barteria_Genet avec les valeurs ci dessous, comment dois je renseigner le fichier csv ?
Barteria dewevrei
Barteria fistulosa
Barteria nigritana
Tetraponera aethiops
Tetraponera latifrons
Merci
MCQ

**Comment by equinton** [comment]
{"taxon":["Barteria dewevrei", "Barteria fistulosa", "etc."], "autre_chose":"autre_truc"}

Eric Quinton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by exmackina** [comment]
Dans le fichier CSV, dans la colonne md_NOM_DU_CHAMP (à ajouter à droite des autres colonnes si besoin) mettre dans chaque cellule les différentes valeurs séparées par des virgules, sans guillemets, comme ceci :

| md_taxon   | 
| ------------------------------------------------ |
| Barteria dewevrei, Barteria fistulosa     |    
| Tetraponera latifrons                             |   
| Barteria nigritana, Barteria dewevrei     |

**Comment by quidoz** [comment]
Bonjour

J’ai tout mis dans la même cellule (C1L1) : 1_reine_fondatrice,domatie,domatie avec champi,écorce,feuille,fragment d'herbier,individus,individus adultes,individus couvain,ouvrières,patch fongique

J’ai essayé de mettre sur deux lignes mais sans succès

A+

MCQ

+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : Alexandre M [mailto:notifications@github.com]
Envoyé : vendredi 8 juin 2018 09:48
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] importer un fichier csv pour alimenter le champ taxon d'une métadonnée (#196)


Dans le fichier CSV, dans la colonne md_NOM_DU_CHAMP (à ajouter à droite des autres colonnes si besoin) mettre dans chaque cellule les différentes valeurs séparées par des virgules, sans guillemets, comme ceci :
md_taxon

Barteria dewevrei, Barteria fistulosa

Tetraponera latifrons

Barteria nigritana, Barteria dewevrei
