### ISSUE TITLE
Intégrer la position de l'objet dans le QRcode

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#2]
Il serait plus rassurant de pouvoir conserver le lieu et la date associée à l'objet (container ou échantillon) dans le QRcode. En effet, les étiquettes peuvent survivre longtemps par rapport à la base de données.
[wgs84_x, wgs84_y, sample_creation_date]

**Comment by equinton** [comment]
Champs utilisables : x, y et cd (creation date)
