### ISSUE TITLE
Champ de métadonnées de type URL

### ISSUE THREAD

**Issue by mrouan** [Irstea/collec#201]
Il serait intéressant d'avoir un nouveau type de champ de métadonnées de type URL permettant de mettre un lien vers une fiche de métadonnées ou description détaillée de l'échantillon dans un portail web externe. En consultation ce champs serait cliquable et ouvrirait l'URL dans un nouvel onglet.

**Comment by equinton** [comment]
Étude d'impact en terme de sécurité à réaliser, pour éviter des attaques de type XSS (lien qui exécuterait du javascript plutôt que la redirection vers une adresse web maîtrisée).
On fera ça cet été, dans la version 2.2
