### ISSUE TITLE
$APPLI_name utilisé dans passwordLost.php (mail de récupération), mais vide

### ISSUE THREAD

**Issue by exmackina** [Irstea/collec#202]
Lors de la récupération de mot de passe, un mail est envoyé avec pour objet : 
$APPLI_name - réinitialisation du mot de passe

Mais $APPLI_name est vide. (dans tout le code, $APPLI_name n'apparaît que dans le fichier passwordLost.php)
Alexandre>Ne serait-ce pas plutôt **$APPLI_titre** ?
Eric>A priori, on serait plutôt sur **$APPLI_code**, $APPLI_titre étant utilisé pour le libellé dans la barre de titre. Ou alors, mettre **$APPLI_titre ( $APPLI_code)**.

NB : $APPLI_code apparaît dans les étiquettes, remplit le champ db
Modifiable depuis le menu : Administration > Paramètres de l'application

Avec les valeurs par défaut on obtient donc un mail avec pour objet : 
- "Collec-Science - réinitialisation..." avec $APPLI_titre
- "proto - réinitialisation..." avec $APPLI_code
- "Collec-Science (proto) - réinitialisation..." avec $APPLI_titre ($APPLI_code)

Cela reste à choisir...

**Comment by equinton** [comment]
Avec les dernières modifs, il faut utiliser les variables en session ($_SESSION["APPLI_code"] et $_SESSION["APPLI_title"]) 
Attention : APPLI_titre est remplacé par APPLI_title, sauf dans les fichiers param.inc.php, pour des questions de compatibilité ascendante.
APPLI_title est maintenant dans dbparam

Pour le mail, ok pour utiliser $_SESSION["APPLI_title"], qui sera plus parlant pour la plupart des utilisateurs, le code intéressant surtout les gestionnaires (code qui figure sur les étiquettes).
