### ISSUE TITLE
accès collect science

### ISSUE THREAD

**Issue by heb1** [Irstea/collec#208]
Bonjour;
Je vous écris car je souhaite essayer le logiciel que vous avez développé pour le suivi et la traçabilité ds échantillons. Le login et mot de passe de la version d essai ne fonctionnent pas. Pouvez vous m'indiquer si il est  toujours valide.``Meilleures salutations

Henri Beaudemoulin 
PAT Zerbaz
31 chemin croix jubile
97410 Saint Pierre 
Reunion

**Comment by heb1** [comment]
Bonjour;
Je vous écris car je souhaite essayer le logiciel que vous avez développé pour le suivi et la traçabilité ds échantillons. Le login et mot de passe de la version d essai ne fonctionnent pas. Pouvez vous m'indiquer si il est toujours valide.``Meilleures salutations

Henri Beaudemoulin
PAT Zerbaz
31 chemin croix jubile
97410 Saint Pierre
Reunion
henri.beaudemoulin@plantadvanced.com

**Comment by cplumejeaud** [comment]
Bonjour


Avez-vous essayé cette adresse ?
https://collec-science.irstea.fr/

   - login : collec-science
   - mot de passe : Collec-Science

En attendant de pouvoir tester la dernière version, 2.1 (mi juillet), voici
un lien vers la version 1.2
https://siza.univ-lr.fr/collec12/
login : admin
mot de passe : password

N'hésitez pas à nous faire part de vos questions et remarques.

Bonne journée
Christine


Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr

**Comment by equinton** [comment]
Bonjour,

Suite aux orages de ce week-end, il est possible que la connexion soit tombée (le serveur de bases de données n'avait pas redémarré correctement).

Je viens de vérifier : l'appli de démo fonctionne maintenant correctement (cf. le message de Christine). À noter qu'elle devrait basculer en version 2.1 demain mardi, ou au plus tard mercredi 4/7.

Cordialement,

**Comment by equinton** [comment]
Avez-vous réussi à vous connecter à l'application de démo ?

**Comment by cplumejeaud** [comment]
Bonjour,

Afin de satisfaire les exigences de ma DSI, j'ai changé le mot de passe
admin de mes sites de démo.
Contactez moi directement sur mon mail afin de l'avoir.

Bonne journée
Christine

Le lun. 2 juil. 2018 08:01, christine Plumejeaud <cplumejeaud@gmail.com> a
écrit :

> Bonjour
>
>
> Avez-vous essayé cette adresse ?
> https://collec-science.irstea.fr/
>
>    - login : collec-science
>    - mot de passe : Collec-Science
>
> En attendant de pouvoir tester la dernière version, 2.1 (mi juillet),
> voici un lien vers la version 1.2
> https://siza.univ-lr.fr/collec12/
> login : admin
> mot de passe : password
>
> N'hésitez pas à nous faire part de vos questions et remarques.
>
> Bonne journée
> Christine
>
>
> Christine Plumejeaud
> Ingénieure de recherche,
>   <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
> formation LIENSs (après connexion sur l'Intranet
> http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
>
> <http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
>  : http://lienss.univ-larochelle.fr/Formation-permanente
> <http://lienss.univ-larochelle.fr/Formation-interne>
>
> Responsable Plateforme DISA (Données : Intégration, Structuration et
> Analyse).
> Littoral Environnement et Sociétés (LIENSs), UMR 7266
> 2 rue Olympe de Gouges
> 17000 La Rochelle
> +(33) - 05 16 49 67 83
> christine.plumejeaud-perreau@univ-lr.fr
>

**Comment by equinton** [comment]
Bonjour,

Avez-vous pu accéder à un des sites de test ?

Cordialement,

Eric Quinton
