### ISSUE TITLE
Mauvais libellé de l'université de Franche-comté

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#209]
Dans la liste des contributeurs, remplacer l'université de Besançon par : université de Franche-Comté

**Comment by exmackina** [comment]
Pour la version anglaise j'avais fait le choix de ne pas traduire le nom de l'université, mais c'est une solution parmi d'autres, avec chacune leurs avantages et inconvénients. Il est également possible de donner la version dans la langue d'origine, souvent accompagnée d'un sigle, et une version dans la langue cible. Par exemple on trouve "Le Massachusetts Institute of Technology (MIT), en français Institut de technologie du Massachusetts" au sujet du [MIT sur Wikipedia](https://fr.wikipedia.org/wiki/Massachusetts_Institute_of_Technology). Voici également un article intéressant à ce sujet : http://traductionquebec.com/domaine-de-la-traduction/traduction-du-nom-des-etablissements-scolaires-anglais/
D'ailleurs ici "Université Bordeaux 1" n'a pas était traduit. Selon les règles de l'article ci-dessus, cela donnerait "Bordeaux University" mais où mettre le "1" ? ou bien "University of Bordeaux 1" comme sur [Wikipedia en anglais](https://en.wikipedia.org/wiki/University_of_Bordeaux_1) ? (on trouve aussi "The University of Bordeaux" sur https://www.u-bordeaux.com/About-us)
