### ISSUE TITLE
Date de création de l'échantillon (d'échantillonnage)

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#213]
Bonjour

Je suis en train de rentrer les veilles collections du CEFE et bien sur je n'ai pas de date de création de l'échantillon mais une année.  Ce cas est très courant quand on récupère de veilles données.

Je suis donc "obligée" de faire un choix arbitraire (1 Janvier) ce qui est faux. Et comma ca m'embête de faire des faux, ca me contrarie

Est ce qu'il serait envisageable de rajouter un champ année e,n // au champ date ? 

A+

MCQ

**Comment by equinton** [comment]
Bonjour Marie-Claude,

C'est un peu compliqué à gérer. D'autres personnes souhaiteront conserver également le mois, et pourquoi pas, faire des recherches dessus... Pour l'avoir vécu dans d'autres jeux de données, il n'y a pas de solution simple.
Dans ton cas de figure, j'utiliserais plutôt les métadonnées pour renseigner cette information, et je n'utiliserais pas le champ sampling_date. Si tu décris le champ de métadonnées "annee" comme "utilisable pour les recherches", tu pourras faire une recherche par année, sans qu'on soit obligé de compliquer l'architecture du logiciel.
La procédure d'import accepte maintenant des colonnes de type md_annee, pour intégrer des champs de métadonnées unitaires (sans avoir à reconstruire le format Json).

Cordialement,

Eric.

**Comment by quidoz** [comment]
Bonjour

Merci pour ta réponse. Si je n’ai pas mis le mois, c’est parce que pour moi l’erreur est moins importante de mettre un faux jour dans un mois qu’un faux jour dans une année

Les métadonnées c’est pas super génial comme solution. Par exemple le menu « Rechercher des échantillons » va être difficile à comprendre. On ne pourrait pas mettre une précision au niveau de la date ? par défaut ça serait au jour mais on pourrait mettre au mois ou à l’année ?

Dans la phase « import de masse », tu veux dire que je peux remplacer
sample_metadata_json

{”recoltant” : ["Nils Bourland"], "nature” : ["feuille"], "taxon” : ["Barteria"]}

{”recoltant” : ["Nils Bourland"], "nature” : ["feuille"], "taxon” : ["Barteria"]}

{”recoltant” : ["Nils Bourland"], "nature” : ["feuille"], "taxon” : ["Barteria"]}

{”recoltant” : ["Nils Bourland"], "nature” : ["feuille"], "taxon” : ["Barteria"]}

{”recoltant” : ["Nils Bourland"], "nature” : ["individus"], "taxon” : ["Tetraponera aethiops"]}


Par 3 colonnes
md_recoltant
md_nature
md_taxon

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : jeudi 5 juillet 2018 14:57
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] Date de création de l'échantillon (d'échantillonnage) (#213)


Bonjour Marie-Claude,

C'est un peu compliqué à gérer. D'autres personnes souhaiteront conserver également le mois, et pourquoi pas, faire des recherches dessus... Pour l'avoir vécu dans d'autres jeux de données, il n'y a pas de solution simple.
Dans ton cas de figure, j'utiliserais plutôt les métadonnées pour renseigner cette information, et je n'utiliserais pas le champ sampling_date. Si tu décris le champ de métadonnées "annee" comme "utilisable pour les recherches", tu pourras faire une recherche par année, sans qu'on soit obligé de compliquer l'architecture du logiciel.
La procédure d'import accepte maintenant des colonnes de type md_annee, pour intégrer des champs de métadonnées unitaires (sans avoir à reconstruire le format Json).

Cordialement,

Eric.

**Comment by equinton** [comment]
Pour les métadonnées, c'est bien ça. 3 colonnes préfixées avec md_ Normalement, ça fonctionne avec la version 2.1.

Pour les dates, je reste réservé. Je pense que de passer par les métadonnées permet de conserver un fonctionnement simple pour tout le monde, et de gérer un cas particulier plus facilement. Ce n'est pas forcément idéal, mais ça me parait le moins risqué et le moins coûteux (en terme de complexité).

Cordialement,

Eric Quinton

**Comment by quidoz** [comment]
Bonjour

J’ai installé la version 2.1 et j’ai testé les métadonnées. Ca marche bien.

J’ai juste un souci quand il y a deux valeurs. J’aurai dû écrire cette case md_recoltant comment ? J’ai mis cela Rumsaïs Blatrix, Champlain Djiéto-Lordon mais c’est pas bon

Je joins mon fichier csv  au cas où

A+

MCQ

PS : à ce j’ai compris les valeurs des métadonnées servent le temps de l’insertion (liste déroulante quand saisie manuel ?, contrôle quand saisie automatique ?) mais pà plus rien après (on peut les effacer sans souci)






+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : jeudi 5 juillet 2018 16:05
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] Date de création de l'échantillon (d'échantillonnage) (#213)

Pour les métadonnées, c'est bien ça. 3 colonnes préfixées avec md_ Normalement, ça fonctionne avec la version 2.1.

Pour les dates, je reste réservé. Je pense que de passer par les métadonnées permet de conserver un fonctionnement simple pour tout le monde, et de gérer un cas particulier plus facilement. Ce n'est pas forcément idéal, mais ça me parait le moins risqué et le moins coûteux (en terme de complexité).

Cordialement,

Eric Quinton

**Comment by cplumejeaud** [comment]
Bonjour Marie-Claude

Non, même si collec permet d'effacer les métadonnées, c'est absolument
contre la philosophie de ma proposition. Il faut conserver les métadonnées
qui constituent le dictionnaire des données collectées.
D'ailleurs, dans notre premier développement de cette extension, les
métadonnées une fois utilisées dans des échantillons ne pouvaient plus être
ni modifiées ni supprimées.
Il ne faudrait jamais modifier un formulaire de métadonnées une fois
utilisé pour des échantillons, ou alors, il faudrait supprimer les
échantillons correspondants.  Si on a besoin de modifier un formulaire de
saisie, il est facile de créer une autre version des métadonnées par
duplication, et d'associer le type d'échantillon à cet autre formulaire.

Est-ce que tu peux me renvoyer ton fichier CSV ? Tu as oublié de le
joindre.

Bonne journée
Christine





Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr

**Comment by quidoz** [comment]
Bonjour

Je l’avais joint (je le remet). C’est un fichier pour importer en masse. Les colonnes H à L sont des métadonnées

Je taquinais un peu pour les métadonnées qui ont un statut temporaire. En tout cas les enlever ne semble pas poser de problème car ils sont codées en dur dans la bdd me semble t’il.

Loin de moi l’idée de les enlever mais l’import par fichier csv les efface

A+

MCQ

+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : cplumejeaud [mailto:notifications@github.com]
Envoyé : mercredi 11 juillet 2018 08:46
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] Date de création de l'échantillon (d'échantillonnage) (#213)

Bonjour Marie-Claude

Non, même si collec permet d'effacer les métadonnées, c'est absolument
contre la philosophie de ma proposition. Il faut conserver les métadonnées
qui constituent le dictionnaire des données collectées.
D'ailleurs, dans notre premier développement de cette extension, les
métadonnées une fois utilisées dans des échantillons ne pouvaient plus être
ni modifiées ni supprimées.
Il ne faudrait jamais modifier un formulaire de métadonnées une fois
utilisé pour des échantillons, ou alors, il faudrait supprimer les
échantillons correspondants. Si on a besoin de modifier un formulaire de
saisie, il est facile de créer une autre version des métadonnées par
duplication, et d'associer le type d'échantillon à cet autre formulaire.

Est-ce que tu peux me renvoyer ton fichier CSV ? Tu as oublié de le
joindre.

Bonne journée
Christine





Christine Plumejeaud
Ingénieure de recherche,
<http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet
http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
: http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>

Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr<mailto:christine.plumejeaud-perreau@univ-lr.fr>

Le 10 juillet 2018 à 17:59, quidoz <notifications@github.com<mailto:notifications@github.com>> a écrit :

> Bonjour
>
> J’ai installé la version 2.1 et j’ai testé les métadonnées. Ca marche
> bien.
>
> J’ai juste un souci quand il y a deux valeurs. J’aurai dû écrire cette
> case md_recoltant comment ? J’ai mis cela Rumsaïs Blatrix, Champlain
> Djiéto-Lordon mais c’est pas bon
>
> Je joins mon fichier csv au cas où
>
> A+
>
> MCQ
>
> PS : à ce j’ai compris les valeurs des métadonnées servent le temps de
> l’insertion (liste déroulante quand saisie manuel ?, contrôle quand saisie
> automatique ?) mais pà plus rien après (on peut les effacer sans souci)
>
>
>
>
>
>
> +++++++++++++++++
> Marie-Claude QUIDOZ
> CEFE / CNRS
> 1919, Route de Mende
> <https://maps.google.com/?q=1919,+Route+de+Mende&entry=gmail&source=g>
> 34293 Montpellier Cedex 5
> Tel : 04 67 61 32 39
> Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr%3cmailto:Marie-Claude.Quidoz@cefe.cnrs.fr>>
> http://www.cefe.cnrs.fr/fr/pf/sie
>
>
> De : equinton [mailto:notifications@github.com]
> Envoyé : jeudi 5 juillet 2018 16:05
> À : Irstea/collec <collec@noreply.github.com<mailto:collec@noreply.github.com>>
> Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr<mailto:Marie-claude.QUIDOZ@cefe.cnrs.fr>>; Author <
> author@noreply.github.com<mailto:author@noreply.github.com>>
> Objet : Re: [Irstea/collec] Date de création de l'échantillon
> (d'échantillonnage) (#213)
>
> Pour les métadonnées, c'est bien ça. 3 colonnes préfixées avec md_
> Normalement, ça fonctionne avec la version 2.1.
>
> Pour les dates, je reste réservé. Je pense que de passer par les
> métadonnées permet de conserver un fonctionnement simple pour tout le
> monde, et de gérer un cas particulier plus facilement. Ce n'est pas
> forcément idéal, mais ça me parait le moins risqué et le moins coûteux (en
> terme de complexité).
>
> Cordialement,
>
> Eric Quinton
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<https://github.com/
<https://github.com/%0b>> Irstea/collec/issues/213#issuecomment-402733113>, or mute the thread<

**Comment by equinton** [comment]
Pour l'importation de multi-valeurs, il faut qu'elles soient dans un format "liste":
["valeur1","valeur2","valeur3"]
C'est le même principe que pour les collections python.
Et bien sûr, la description des métadonnées doit être d'un type compatible
