### ISSUE TITLE
Admin should be able to delete selections

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#214]
> il fait trop chaud et ça me fatigue d'écrire en français

... a surprise for the end of the day

Every existing application on the planet has a possibility to select multiple elements and to delete the selection in a click. At least administrators have that _power_. Collec-science doesn't have that option. 

This is a question of ergonomics. Or is there a reason for such an awkward paranoid box concept ?

Or should I look around again and find a hidden button or a menu somewhere ?

**Comment by equinton** [comment]
Le logiciel est développé en fonction des besoins exprimés. Celui-ci ne l'a pas été (exprimé).

Je présume que cela concerne la suppression d'échantillons, ou également la suppression de contenants ? Depuis la page de recherche ?

**Comment by zer0mode** [comment]
Je suppose que chaque utilisateur-administrateur va avoir besoin de supprimer un ensemble d'échantillons après un certain temps d'utilisation.

> ... depuis une page de recherche

par exemple avec _Delete_:
<kbd>Copy</kbd> <kbd>CSV</kbd> <kbd>Print</kbd> <kbd>Delete</kbd>  
ou autrement

_Use case 1_
- importation à partir d'un fichier par erreur
- sélection de ces échantillons importés par erreur pour suppression

_Use case 2_
- nettoyage d'échantillons / contenants après péremption

_Use case 3_
- suppression d'échantillons préparés avant terrain mais pas finalement prélevés.
