### ISSUE TITLE
Pages blanches quand même

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#215]
Après chaque login on obtiens une page blanche qui s’arrête sur `https://monza.collec-za.org/index.php`. Il faut forcement recharger la page pour continuer.

Personne n'a rencontré le même comportement ?

_master 2.1 et le versions précédentes_

**Comment by quidoz** [comment]
si moi ! mais ca ne semble plus arriver dans la version 2.0.1

**Comment by cplumejeaud** [comment]
Bonjour,
Je retesterai lundi prochain avec un install fraiche de la version de demo
sur mon serveur en 2.1 pour vous dire. Maintenant que j'ai les bons
certificats, je vais tester à fond.
Bonne journée

**Comment by equinton** [comment]
Essaie de vider le cache de ton navigateur, il me semble qu'on avait déjà rencontré ce type de problème il y a quelques mois qui avait été réglé avec cette manip.

Eric Quinton
