### ISSUE TITLE
import de plus de 50 termes dans une métadonnée

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#216]
Bonjour

J'ai voulu importer un fichier de métadonnées de recoltant. Ce fichier contient plus de 50 termes (qui ne sont pas tous jolis).  Le logiciel me le signale, me demande ce que je veux faire et ensuite plus rien ! 

?,A. Bouquet,A. Rial,A.J.M. 5248,A.J.M. 5250,A.J.M. 9897,A.M. 1335,A.M. 596,al,Andel,Anna Saltmarsh,B .M. 9673,B. Descoings,B. Dupre,B. F. F. de Wilde-Duyfjes,Bertrand Kokolo,Bosch,Bradley,Breteler,Bruce Webber,C. 848,C.C.H. 1337,C.M. 4010,C.M. 5425,Carvalho,Céline Born,Champlain Djiéto-Lordon,Charles Doumenge,Christiane Atteke,Compère,David Harris,de Nere,Descoings,Doyle McKey,Eimunjeze,Eneme,Eneme Fr.,Essouma,Etuge,Evrard,F. Abaga,F. Hallé,F.J. 1373,F.J. 1404,F.J. 14663,François Bretagnolle,G.M.P.C. 4735,Gael Bouca,Gérard,Gilles Dauby,Guillaume Léotard,Hallé,Hedin,Hilaire Ontsana,J. 183,J. 4953,J. Koechlin,J. Trochain,J.J. 3085,J.J.F.E. de 514,J.J.F.E. de 7677,J.L.C.H. van 2567,J.L.P. 2350,J.L.P. 3284,Jan Wieringa,Jean Josef Zinga,Jongkind,Judicaël Mezui,Judicael Mezui M'Eko,L. Makany,Latilo,Le Testu,Leeuwenberg,Lejoly,Lisowski,Louis,M. 86,M.F. de 4925,M.G. FHI70572,Maas,Marie Charpentier,Marie-Hélène Chevallier,Mbaniboua,McKey,Meer,Moussavou,N. 2842,Néré de 32,Nils Bourland,Obama,Olivier Hardy,P. 1205,P. 3189,P. 4874,P.J.M. 10256,P.P.C. van 1792,P.P.C. van 724,Rumsaïs Blatrix,Salleh,Schoenmaker,Sinclair,Sita,T.R. van 4129,Tisserant (équipe),ToussaintV.E. FHI70274,Valkenburg,van Nek,W. J. J. O. de Wilde,W.J.J.O. de 2800,Walters,Wieringa,Wilde,Wilde (WALK-B),Y. Attims
--

![image](https://user-images.githubusercontent.com/29607993/42337122-040d9004-8086-11e8-8404-ff24164f7c3c.png)

A+

MCQ

**Comment by equinton** [comment]
Bonjour Marie-Claude,

Peux-tu mettre ton fichier en pièce jointe, pour que je puisse réaliser des tests et corriger le code ?

Merci,

Eric

**Comment by quidoz** [comment]
Bonjour

Je suis en version 2.0.1

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : vendredi 6 juillet 2018 09:31
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)


Bonjour Marie-Claude,

Peux-tu mettre ton fichier en pièce jointe, pour que je puisse réaliser des tests et corriger le code ?

Merci,

Eric

**Comment by equinton** [comment]
Problème non reproduit à partir des données fournies:
![capture d ecran de 2018-08-30 12-10-29](https://user-images.githubusercontent.com/6715861/44845452-dcb35680-ac4d-11e8-9615-0cbbd07c7c1a.png)

Peux-tu indiquer avec quel navigateur tu as réalisé l'opération ?

**Comment by quidoz** [comment]
Bonjour

Normalement j’utilise uniquement Firefox (sous windows)

Je peux retester cet apres midi si tu veux

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : jeudi 30 août 2018 12:12
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)


Problème non reproduit à partir des données fournies:
[capture d ecran de 2018-08-30 12-10-29]<https://user-images.githubusercontent.com/6715861/44845452-dcb35680-ac4d-11e8-9615-0cbbd07c7c1a.png>

Peux-tu indiquer avec quel navigateur tu as réalisé l'opération ?

**Comment by quidoz** [comment]
Bonjour

Il est taquin le logiciel !

J’ai réessayé la manip. ca a bien marché. J’ai vu la liste des récoltants affichés dans les métadonnées. Elle est aussi dans la base de données. Mais maintenant je ne peux plus y accéder. Quand je clique sur Metadonnee_Barteria_Genet dans le menu modele de métadonnées, ca ne fait rien. J’ai arrêté le service apache / postgresql et redemarrez. Ca ne marche toujours pas.

Je peux faire quoi pour m’en sortir ?

A+

MCQ


1;"Metadonnee_Barteria_Genet";"[{"name":"recoltant","type":"select","choiceList":["?","A. Bouquet","A. Rial","A.J.M. 5248","A.J.M. 5250","A.J.M. 9897","A.M. 1335","A.M. 596","al","Andel","Anna Saltmarsh","B .M. 9673","B. Descoings","B. Dupre","B. F. F. de Wilde-Duyfjes","Bertrand Kokolo","Bosch","Bradley","Breteler","Bruce Webber","C. 848","C.C.H. 1337","C.M. 4010","C.M. 5425","Carvalho","Céline Born","Champlain Djiéto-Lordon","Charles Doumenge","Christiane Atteke","Compère","David Harris","de Nere","Descoings","Doyle McKey","Eimunjeze","Eneme","Eneme Fr.","Essouma","Etuge","Evrard","F. Abaga","F. Hallé","F.J. 1373","F.J. 1404","F.J. 14663","François Bretagnolle","G.M.P.C. 4735","Gael Bouca","Gérard","Gilles Dauby","Guillaume Léotard","Hallé","Hedin","Hilaire Ontsana","J. 183","J. 4953","J. Koechlin","J. Trochain","J.J. 3085","J.J.F.E. de 514","J.J.F.E. de 7677","J.L.C.H. van 2567","J.L.P. 2350","J.L.P. 3284","Jan Wieringa","Jean Josef Zinga","Jongkind","Judicaël Mezui","Judicael Mezui M'Eko","L. Makany","Latilo","Le Testu","Leeuwenberg","Lejoly","Lisowski","Louis","M. 86","M.F. de 4925","M.G. FHI70572","Maas","Marie Charpentier","Marie-Hélène Chevallier","Mbaniboua","McKey","Meer","Moussavou","N. 2842","Néré de 32","Nils Bourland","Obama","Olivier Hardy","P. 1205","P. 3189","P. 4874","P.J.M. 10256","P.P.C. van 1792","P.P.C. van 724","Rumsaïs Blatrix","Salleh","Schoenmaker","Sinclair","Sita","T.R. van 4129","Tisserant (équipe)","ToussaintV.E. FHI70274","Valkenburg","van Nek","W. J. J. O. de Wilde","W.J.J.O. de 2800","Walters","Wieringa","Wilde","Wilde (WALK-B)","Y. Attims"],"isSearchable":"yes","required":true,"helperChoice":false,"description":"indiquer ici le ou les récoltants de l'échantillon","measureUnit":"N/A"},{"name":"nature","type":"select","choiceList":["écorce","domatie","feuille","fragment d'herbier","individus"],"isSearchable":"no","required":true,"helperChoice":false,"description":"indiquer la nature de l'échantillon (exemple : feuilles, tiges, individus, ...)","measureUnit":"N/A"},{"name":"taxon","type":"select","choiceList":["Adenia","Adenia poggei","Adenia tricostata","Barteria","Barteria dewevrei","Barteria dewevrei(?)","Barteria fistulosa","Barteria nigritana","Barteria nigritana(?)","Barteria solida","Barteria solida ?","Camponotus","Cataulucus","champignon","Crematogaster","fourmi_autre","Paropsia edulis","Paropsia grewioides","Paropsia sp","Paropsia vareciformis","Paropsiopsis sp.","pas_foumi","Polyrhachis","Tetraponera","Tetraponera aethiops","Tetraponera latifrons"],"isSearchable":"yes","required":true,"helperChoice":false,"description":"indiquer le taxon","measureUnit":"N/A"},{"name":"phenologie","type":"select","choiceList":["FL","FR","ST"],"isSearchable":"no","required":false,"helperChoice":false,"description":"indiquer la phénologie","measureUnit":"N/A"},{"name":"phenotype","type":"select","choiceList":["grosses domaties"],"isSearchable":"no","required":false,"helperChoice":false,"description":"indiquer le phénotype","measureUnit":"N/A"}]"


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : QUIDOZ Marie-Claude
Envoyé : jeudi 30 août 2018 12:15
À : Irstea/collec <reply@reply.github.com>; Irstea/collec <collec@noreply.github.com>
Cc : Author <author@noreply.github.com>
Objet : RE: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)

Bonjour

Normalement j’utilise uniquement Firefox (sous windows)

Je peux retester cet apres midi si tu veux

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : jeudi 30 août 2018 12:12
À : Irstea/collec <collec@noreply.github.com<mailto:collec@noreply.github.com>>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr<mailto:Marie-claude.QUIDOZ@cefe.cnrs.fr>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)


Problème non reproduit à partir des données fournies:
[capture d ecran de 2018-08-30 12-10-29]<https://user-images.githubusercontent.com/6715861/44845452-dcb35680-ac4d-11e8-9615-0cbbd07c7c1a.png>

Peux-tu indiquer avec quel navigateur tu as réalisé l'opération ?

**Comment by quidoz** [comment]
Bonjour

J’ai utilisé pour le test Firefox 61.0.2 (64 bits) sur Windows 8

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : QUIDOZ Marie-Claude
Envoyé : jeudi 30 août 2018 15:27
À : Irstea/collec <reply@reply.github.com>; Irstea/collec <collec@noreply.github.com>
Cc : Author <author@noreply.github.com>
Objet : RE: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)

Bonjour

Il est taquin le logiciel !

J’ai réessayé la manip. ca a bien marché. J’ai vu la liste des récoltants affichés dans les métadonnées. Elle est aussi dans la base de données. Mais maintenant je ne peux plus y accéder. Quand je clique sur Metadonnee_Barteria_Genet dans le menu modele de métadonnées, ca ne fait rien. J’ai arrêté le service apache / postgresql et redemarrez. Ca ne marche toujours pas.

Je peux faire quoi pour m’en sortir ?

A+

MCQ


1;"Metadonnee_Barteria_Genet";"[{"name":"recoltant","type":"select","choiceList":["?","A. Bouquet","A. Rial","A.J.M. 5248","A.J.M. 5250","A.J.M. 9897","A.M. 1335","A.M. 596","al","Andel","Anna Saltmarsh","B .M. 9673","B. Descoings","B. Dupre","B. F. F. de Wilde-Duyfjes","Bertrand Kokolo","Bosch","Bradley","Breteler","Bruce Webber","C. 848","C.C.H. 1337","C.M. 4010","C.M. 5425","Carvalho","Céline Born","Champlain Djiéto-Lordon","Charles Doumenge","Christiane Atteke","Compère","David Harris","de Nere","Descoings","Doyle McKey","Eimunjeze","Eneme","Eneme Fr.","Essouma","Etuge","Evrard","F. Abaga","F. Hallé","F.J. 1373","F.J. 1404","F.J. 14663","François Bretagnolle","G.M.P.C. 4735","Gael Bouca","Gérard","Gilles Dauby","Guillaume Léotard","Hallé","Hedin","Hilaire Ontsana","J. 183","J. 4953","J. Koechlin","J. Trochain","J.J. 3085","J.J.F.E. de 514","J.J.F.E. de 7677","J.L.C.H. van 2567","J.L.P. 2350","J.L.P. 3284","Jan Wieringa","Jean Josef Zinga","Jongkind","Judicaël Mezui","Judicael Mezui M'Eko","L. Makany","Latilo","Le Testu","Leeuwenberg","Lejoly","Lisowski","Louis","M. 86","M.F. de 4925","M.G. FHI70572","Maas","Marie Charpentier","Marie-Hélène Chevallier","Mbaniboua","McKey","Meer","Moussavou","N. 2842","Néré de 32","Nils Bourland","Obama","Olivier Hardy","P. 1205","P. 3189","P. 4874","P.J.M. 10256","P.P.C. van 1792","P.P.C. van 724","Rumsaïs Blatrix","Salleh","Schoenmaker","Sinclair","Sita","T.R. van 4129","Tisserant (équipe)","ToussaintV.E. FHI70274","Valkenburg","van Nek","W. J. J. O. de Wilde","W.J.J.O. de 2800","Walters","Wieringa","Wilde","Wilde (WALK-B)","Y. Attims"],"isSearchable":"yes","required":true,"helperChoice":false,"description":"indiquer ici le ou les récoltants de l'échantillon","measureUnit":"N/A"},{"name":"nature","type":"select","choiceList":["écorce","domatie","feuille","fragment d'herbier","individus"],"isSearchable":"no","required":true,"helperChoice":false,"description":"indiquer la nature de l'échantillon (exemple : feuilles, tiges, individus, ...)","measureUnit":"N/A"},{"name":"taxon","type":"select","choiceList":["Adenia","Adenia poggei","Adenia tricostata","Barteria","Barteria dewevrei","Barteria dewevrei(?)","Barteria fistulosa","Barteria nigritana","Barteria nigritana(?)","Barteria solida","Barteria solida ?","Camponotus","Cataulucus","champignon","Crematogaster","fourmi_autre","Paropsia edulis","Paropsia grewioides","Paropsia sp","Paropsia vareciformis","Paropsiopsis sp.","pas_foumi","Polyrhachis","Tetraponera","Tetraponera aethiops","Tetraponera latifrons"],"isSearchable":"yes","required":true,"helperChoice":false,"description":"indiquer le taxon","measureUnit":"N/A"},{"name":"phenologie","type":"select","choiceList":["FL","FR","ST"],"isSearchable":"no","required":false,"helperChoice":false,"description":"indiquer la phénologie","measureUnit":"N/A"},{"name":"phenotype","type":"select","choiceList":["grosses domaties"],"isSearchable":"no","required":false,"helperChoice":false,"description":"indiquer le phénotype","measureUnit":"N/A"}]"


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : QUIDOZ Marie-Claude
Envoyé : jeudi 30 août 2018 12:15
À : Irstea/collec <reply@reply.github.com>; Irstea/collec <collec@noreply.github.com<mailto:collec@noreply.github.com>>
Cc : Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : RE: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)

Bonjour

Normalement j’utilise uniquement Firefox (sous windows)

Je peux retester cet apres midi si tu veux

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : equinton [mailto:notifications@github.com]
Envoyé : jeudi 30 août 2018 12:12
À : Irstea/collec <collec@noreply.github.com<mailto:collec@noreply.github.com>>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr<mailto:Marie-claude.QUIDOZ@cefe.cnrs.fr>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [Irstea/collec] import de plus de 50 termes dans une métadonnée (#216)


Problème non reproduit à partir des données fournies:
[capture d ecran de 2018-08-30 12-10-29]<https://user-images.githubusercontent.com/6715861/44845452-dcb35680-ac4d-11e8-9615-0cbbd07c7c1a.png>

Peux-tu indiquer avec quel navigateur tu as réalisé l'opération ?

**Comment by equinton** [comment]
Problème lié à Firefox dans un environnement Windows. Solution : utiliser un navigateur basé sur Chrome.

Faq créée : https://www.collec-science.org/faq/#description_metadata
