### ISSUE TITLE
Problème de suppression d'un objet de type Famille de contenant

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#219]
Après une opération de suppression (par exemple une famille de containers : "Contenant"),
le rafraîchissement de l'écran n'a pas lieu. 
En fait, l'objet n'est pas supprimé alors que l'écran répond qu'il y a eu suppression. 

Ci joint la capture d'écran. 
![refresh_screen](https://user-images.githubusercontent.com/7202505/42584903-8fc41282-8534-11e8-89b3-7a4ba26cb0fd.png)

Pas de trace d'erreur dans les logs de COLLEC. 
****
Postgres se plaint d'un viol de contrainte d'intégrité dans les logs. 
> 
> 2018-07-11 17:57:19.788 CEST [29960]  ERREUR:  UPDATE ou DELETE sur la table « container_family » viole la contrainte de clé étrangère
>         « container_family_container_type_fk » de la table « container_type »
> 2018-07-11 17:57:19.788 CEST [29960] DÉTAIL:  La clé (container_family_id)=(3) est toujours référencée à partir de la table « container_type ».
> 2018-07-11 17:57:19.788 CEST [29960] INSTRUCTION :  delete from container_family where container_family_id= $1

Ci joint la recherche de Containers qui seraient de cette famille : aucun. Donc ce n'est pas un problème de contrainte d'intégrité apriori. 
![delete_famille_contenant](https://user-images.githubusercontent.com/7202505/42585176-3889b660-8535-11e8-8b35-33d10907e7fe.png)

**Comment by equinton** [comment]
Il n'est pas possible de supprimer une famille de contenants alors qu'un type de contenant est toujours rattaché à celle-ci.
Par contre, un message d'erreur devrait être affiché.
