### ISSUE TITLE
suppression en masse de données importées en masse

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#221]
Bonjour

Est ce qu'il serait possible de prévoir une fonctionnalité pour pouvoir supprimer en masses les données importées en masse ? Pour ma part je me débrouille en allant dans la base de données mais c'est pas super sur. Ca serait bien de pouvoir présenter un fichier contenant les données à supprimer. Une autre solution (n'est pas très intéressant ici) serait de garder la traçabilité entre les données entrées et les fichiers. ET ainsi indiquer que l'on veut supprimer le fichier X du xx/xx/xxxx

A+

MCQ

**Comment by quidoz** [comment]
Je viens de me rendre compte que ma demande correspond à cette demande 
"Admin should be able to delete selections #214"

**Comment by equinton** [comment]
Fermé pour cause de doublon.
Sera traité par une fonction rattachée à la liste des échantillons (même principe que pour l'impression d'étiquettes ou l'exportation).
