### ISSUE TITLE
problème de date lors d'un import CSV

### ISSUE THREAD

**Issue by mrouan** [Irstea/collec#225]
Lorsque j'importe le fichier CSV suivant avec une sampling_date formatée comme préconisé sur la page d'import en masse (dd/mm/yyyy donc ici 15 juin 2018) la date importée est le 06/05/2018 soit le 6 mai 2018...

```sample_identifier;collection_id;wgs84_x;wgs84_y;sample_status_id;sample_type_id;sampling_date;expiration_date;sampling_place_id;container_identifier;container_type_id;container_status_id;container_parent_uid;md_type_de_materiel;md_site;md_longueur;md_pi;md_mission;md_numero_ordre_section;md_profondeur_top;md_profondeur_bottom;md_diametre;md_corer_type;md_URL_objet;md_bathy
ROHU-1-2;4;-3.12131656188392;47.5027578920409;1;1;15/06/2018;;107;;;;;Sediment;ROHU;100;Pierre Stephan (ORCID:0000-0001-7975-2149);BEV;2;100;200;5;Cobra;http://;0```

**Comment by equinton** [comment]
Non reproduit en version 2.2
Mise en production prévue vendredi.

**Comment by zer0mode** [comment]
Testé sur 2.2 et cette erreur a été reproduite avec le [fichier](https://github.com/Irstea/collec/issues/224#issuecomment-424028432) utilisé sur la version 2.1

**Comment by equinton** [comment]
Si l'importation s'est déroulée avec l'appli configurée en anglais, c'est probablement lié à un bug dans la traduction (je vais corriger) : le format attendu pour les importations en anglais est mm-dd-yyyy

Merci de me préciser si c'est bien le cas, et tester l'importation en français pour vérifier que le format de date est le bon.

**Comment by equinton** [comment]
Les fichiers importés en anglais doivent avoir les dates formatées en anglais.
Mise à jour des textes dans le dernier commit.
