### ISSUE TITLE
Propagation du statut / état de contenants sur les échantillons

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#226]
Une proposition a été évoqué concernant l'état des échantillons. Si un congélateur cesse de fonctionner pendant une période prolongée, par exemple
- _( type d'événement = contenant cassé temporairement )_ `<MENU> Paramètres -> Types d'événements`

la qualité des échantillons contenus pourrait régresser. Alors il serait important d'indiquer cet état et le rendre visible sur les échantillons concernée a partir de `<MENU> Objets -> Echantillons` si l'événement s'est produit.

Conséquemment il faudra introduire la date de début et la date de fin pour le `types d’événements`.

**Comment by equinton** [comment]
C'est plus compliqué que ça. Il faudrait pouvoir recalculer, pour un échantillon, tous les événements qui se sont produits pour les containers où il a séjourné. Pas impossible, mais complexe.
On verra pour une version future.

**Comment by equinton** [comment]
Traité différemment : dans la version 2.2.2, il sera possible de créer des événements globalement pour une liste d'échantillons, par exemple ceux présents dans un container.
Dans les commentaires, il suffit d'indiquer ce qu'il s'est passé pour que le détail soit disponible en consultation d'un échantillon.
Si ce n'est pas suffisant, on verra ce qu'il conviendra de faire plus tard.
