### ISSUE TITLE
pb avec la version 2.2.1

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#236]
Bonjour

J'ai installé la version 2.2.1 (j'avais auparavant la 2.1). J'arrive bien à me connecter, je vois les infos du  menu paramètre (donc la connexion à la base de données est bonne) mais j'ai des pages qui ne marchent pas, style

https://collection.cefe.cnrs.fr/index.php?module=protocolChange&protocol_id=1
https://collection.cefe.cnrs.fr/index.php?module=containerList
https://collection.cefe.cnrs.fr/index.php?module=sampleList

Cette page ne fonctionne pas
Impossible de traiter cette demande via collection.cefe.cnrs.fr à l'heure actuelle.
HTTP ERROR 500

Une idée de l'erreur ? J'ai essayé avec Chrome et Mozilla

A+

MCQ

**Comment by quidoz** [comment]
Bonjour

J'ai trouvé l'erreur. Je ne sais pas si elle vient de ma façon de faire les mises à jour de la base de données ou des fichiers fournis. Tjs est il que la table collect n'avait pas le bon propriétaire. C'était indiqué postgres au lieu de collec

A+

MCQ

**Comment by equinton** [comment]
Le script de mise à jour est construit en plusieurs parties, pour permettre une attribution des droits au _login_ collec : 
```
echo "update database"
chmod 755 /var/www/html/collec-science
cd collec/install
su postgres -c "psql -f upgrade-2.0-2.1.sql"
```

Dans cette première partie, la connexion s'effectue avec le _login_ postgres (su postgres).

Le script d'upgrade lance ensuite la connexion à la base collec en utilisant le login collec : 
`\c "dbname=collec user=collec password=collecPassword host=localhost"`

En étant connecté avec le _user_ collec, le script de modification de la base de données, exécuté ensuite, attribuera automatiquement les droits à cet _user_ : 
`\ir pgsql/col_alter_2.0-2.1.sql`
