### ISSUE TITLE
collec-science pour gérer le contenu d'une chambre froide

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#237]
Bonjour

J ai eu la question suivante de la part de mon directeur "ce logiciel est-il utilisable pour gérer la future chambre froide ? j’espère que la réponse est oui. L’idée, c’est que tous les échantillons qui rentreront dans cette chambre soient dûment répertoriés ou dit autrement pas de codes, pas d’échantillons !!!!"  

Je lui aurai bien répondu oui ET non. 

OUI 
- car je suis bien dans le cas d'un container et d'échantillon.
- car collec-science est prévue pour gérer la gestion de matériels 
- si les échantillons vont parties d'une collection déjà "structurées / définies" dans collec-science 
 
NON 
- car je ne pourrais pas imposer que la collection soit définie précisément au préalable
- car collec-science est structurée en fonction d'une collection et non d'un contenant
 
Et vous, vous lui réponderiez quoi à mon directeur ? (sachant que l'on a + de 100 "collections" différentes et que la chambre froide arrive d'ici peu)

A+

MCQ

**Comment by equinton** [comment]
Une chambre froide, c'est une pièce. Le stockage des échantillons se fait sur des étagères, probablement : il suffit de les décrire.

Quant aux collections, je ne sais que répondre... Tu peux toujours créer une collection "fourre-tout" avec des types d'échantillon génériques, si ça t'amuse : tout pourra être identifié, mais je ne suis pas sûr que ce soit pérenne sur le long terme. Sinon, il faut faire le boulot de description adéquat.

Cordialement,

Eric Quinton

**Comment by quidoz** [comment]
Bonjour

L'idée est d'organiser toutes les collections mais ça va prendre du temps.

Est ce que quelqu'un a utilisé collec-science pour gérer du matériel ? 
parce que dans un premier temps ma chambre froide pourrait être gérer 
comme cela... c'est à dire avec un niveau de détail  faible

A+

MQ

Le 22/10/2018 à 19:55, equinton a écrit :

**Comment by equinton** [comment]
Bonjour,

J'ai du mal à comprendre le besoin. Stocker du matériel n'est pas la même chose que stocker des échantillons, et une chambre froide n'est qu'une pièce : sans description précise de ce que vous voulez faire, c'est difficile de répondre.

Le logiciel a été (également) conçu pour répondre à des besoins simples de magasinage (entrée/sortie de matériels). À Bordeaux, nous avions prévu une instance pour gérer des entrées/sorties de matériel terrain. Nous ne l'avons pas mis en route parce que le local concerné devait être réaffecté à d'autres usages, mais le logiciel répond à ce type de demande.

Si vous n'êtes pas capables de gérer des collections d'échantillons, vous pouvez envisager de ne traiter que des conteneurs (caisses remplies d'échantillons en vrac, probablement). Il suffit de définir vos caisses, les identifier, et codifier tous les rangements (rayons, étagères, etc.) dans votre chambre froide. Le contenu des caisses pourra être décrit par la suite en précisant les échantillons qu'elles contiennent.

Quoi qu'il en soit, je vous conseille de commencer par décrire les processus que vous souhaitez mettre en œuvre, à court terme et à moyen terme. Si vous n'avez pas une idée assez claire de vos objectifs, vous risquez de vous "égarer" dans la configuration, et cela pourrait être compliqué ensuite pour corriger le tir.

Contrairement à ce qui a été dit, Collec-Science est parfaitement capable de gérer des conteneurs et de ne pas traiter d'échantillons (et donc de collections). 

Je suis toutefois  surpris que la question se pose au moment de la livraison de la chambre froide : il me semblait que c'était le genre d'investissements qui nécessitait un certain temps pour être mis en œuvre. La mise au point d'un magasinage nécessite des réflexions en amont pour éviter de faire n'importe quoi.

Cordialement,

Éric Quinton.
