### ISSUE TITLE
Utilisateur Safari ne peut pas se connecter 

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#238]
Pour l'information :

La connexion n'est pas possible si l'utilisateur navigue avec Safari. Tout fonctionne correctement en utilisant le même compte sur Firefox.

**Comment by equinton** [comment]
Merci de préciser la plate-forme et la version de Collec-Science : je n'ai pas reproduit le problème dans ma machine Linux avec Opera installé spécialement pour le test.

**Comment by zer0mode** [comment]
> ... le même compte sur Firefox.

_... le même compte sur Firefox et sur le même système (iOS)._

Je n'ai pas récupéré des détails d'OS ni de navigateur. La même situation s'est reproduite pour deux utilisateurs Mac. Un 3ème utilisateur (iOS / Safari) n'a pas rencontré ce souci.

-> à suivre, j'attends l'info sur les versions

**Comment by equinton** [comment]
Je me souviens d'un problème de connexion qui était lié au refus des cookies par le navigateur, et je crois bien que c'était avec un mac : comme la session est gérée par des cookies, si le navigateur ne les accepte pas, chaque page redemande la connexion... C'est sans fin.

Fait vérifier que les cookies sont bien acceptés dans le navigateur

**Comment by equinton** [comment]
Problème également rencontré ailleurs.

Il faudrait tester les solutions proposées ici : 
https://appuals.com/safari-cant-establish-a-secure-connection-to-the-server/
