### ISSUE TITLE
Gestion des prêts d'échantillons

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#239]
Ajouter un module de prêts d'échantillons à d'autres structures.

Besoins identifiés:
- date de prêt
- date prévue de retour
- liste des laboratoires emprunteurs ?
- affichage de la liste des emprunts en cours, ou échus, par collection ou emprunteur

Modes opératoires:
- lors d'un emprunt, création d'un mouvement de sortie. Ajout d'un statut (code à définir) : emprunté ?
- lors du retour, retour du statut à 1 ?

**Comment by IsabelleBilly** [comment]
si possible, prévoir de pouvoir le faire par lot d'échantillons
