### ISSUE TITLE
échantillons / conteneurs pré-sélectionnés

### ISSUE THREAD

**Issue by zer0mode** [Irstea/collec#240]
Quand la page des échantillons / conteneurs est chargée tous les éléments de la liste sont sélectionnés / cochés.
![image](https://user-images.githubusercontent.com/18060286/48938947-01e4f780-ef13-11e8-8943-c4ec10258440.png)

Les casés sont dans la dernière colonne de la liste est cette colonne n'est pas visible _(sauf si la vue est de-zoomée par défaut, ce qu'il n'est pas le cas)_. Les utilisateurs ne sont pas au courant qu'il y a un _"traitement en cours"_. Pour procéder il faut d'abord tout décocher.

Une erreur affectant tout la liste pourrait se produire par une mauvaise manipulation.

- si c'est une fonctionnalité utilisée par certains utilisateurs ça serait plus informatif de **déplacer cette colonne tout à gauche de la liste** (à côté de l'UID)
- sinon c'est plus intuitif d'obtenir une liste des éléments recherchés qui ne sont pas automatiquement pré-sélectionnés; **il faut désactiver la pré-séléction**

**Comment by equinton** [comment]
C'est une fonction de base qui sert notamment à générer les étiquettes.
Ok pour modifier l'emplacement de la colonne, par contre la liste restera sélectionnée pour ne pas modifier les habitudes actuelles.

**Comment by equinton** [comment]
Déplacement de la colonne en première position et intégration du tri du tableau en fonction de son affichage ou non (droit de gestion existant ou non)
