### ISSUE TITLE
probleme avec l'affichage des lieux de prélévement

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#269]
La liste déroulante est ok mais une fois sélectionnée et recherchée, le "reaffichage" comporte un caractère bizarroide
![image](https://user-images.githubusercontent.com/29607993/54833412-55e3cb00-4cbe-11e9-8582-99a21022dc00.png)

**Comment by equinton** [comment]
Non reproduit. Il s'agit d'un encodage html dans l'exemple, peut-être un copier-coller de libellé depuis une page web lors de la création du lieu de prélèvement.
