### ISSUE TITLE
Comportement bizarre en scan d'étiquettes

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#27]
Lors du scan d'étiquettes avec une douchette, des logiciels complémentaires s'ouvrent et interfèrent avec la saisie.
Firefox / Microsoft windows 7

**Comment by equinton** [comment]
Problème non reproduit, probablement lié à une mauvaise configuration de la douchette

**Comment by cplumejeaud** [comment]
Pas vu. Manuel d'utilisation de la douchette en ligne sur POPS. 
http://www-iuem.univ-brest.fr/pops/projects/za
