### ISSUE TITLE
accès au détail des métadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#270]
Dans la liste, je vois bien mon modèle de métadonnées
![image](https://user-images.githubusercontent.com/29607993/54833521-8c214a80-4cbe-11e9-8d65-404442ec6fd4.png)

Mais quand je clique sur modifier, je n'ai pas accès au détail
![image](https://user-images.githubusercontent.com/29607993/54833586-aa874600-4cbe-11e9-9a7d-5aff99e3a0f2.png)
 
qui existe bien dans les échantillons
![image](https://user-images.githubusercontent.com/29607993/54833646-cd195f00-4cbe-11e9-8239-9e935be29d78.png)

**Comment by equinton** [comment]
Problème déjà signalé en 2018, lié à l'utilisation de Firefox quand une liste contient plus de 50 items : 
https://github.com/Irstea/collec/issues/216

Dans ton cas de figure, il faut utiliser Chrome pour éviter le problème, ou éviter de gérer une liste de choix de plus de 50 items dans les métadonnées.
