### ISSUE TITLE
rechercher des contenants avec statut

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#275]
Si on sélectionne seulement un statut et on fait rechercher, ça ne recherche rien . 
Pas de souci avec famille et famille/type

**Comment by equinton** [comment]
oui, c'est assez logique: dans le cas contraire, on peut ramener l'ensemble de la base de données (la quasi-totalité des contenants ont le statut "État normal".

On peut envisager d'autoriser la recherche si le statut n'est pas à 1, dans le cas où aucun autre critère ne soit renseigné.

**Comment by equinton** [comment]
Recherche par statut > 1 intégrée.
