### ISSUE TITLE
date de creation dans la base quand on fait des imports de masse

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#277]
Bonjour
Suite à mon import de masse, je pensais trouver mes échantillons en recherchant échantillon / rechercher par date de création et en mettant aujourd'hui. Mais ca n'a pas marché

**Comment by equinton** [comment]
Deux pistes pour expertiser le pb:
- vérifie le contenu des champs dans la base de données (au cas où il y ait un réel problème)
- teste avec des intervalles différents (le jour précédent, le jour suivant)
Ça me permettra de mieux cerner le point.

Merci,
Éric.

**Comment by quidoz** [comment]
Bonjour

 

Il faut mettre le jour suivant dans le champ « au » donc la date de demain

 

A+


MCQ

 

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

 

De : Eric Quinton [mailto:notifications@github.com] 
Envoyé : mardi 2 juillet 2019 18:10
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] date de creation dans la base quand on fait des imports de masse (#277)

 

Deux pistes pour expertiser le pb:

*	vérifie le contenu des champs dans la base de données (au cas où il y ait un réel problème)
*	teste avec des intervalles différents (le jour précédent, le jour suivant)
Ça me permettra de mieux cerner le point.

Merci,
Éric.

**Comment by equinton** [comment]
Vérifier la nature du test, pour prendre en compte l'intervalle de dates et non entre deux timestamps.
