### ISSUE TITLE
saisir des metadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#278]
Bonjour 

Dans mon fichier csv, pour saisir deux informations dans une métadonnée à choix multiple, j'ai séparé les deux termes par des virgules. Par exemple dans le champ md_recoltant, j'ai indiqué Rumsaïs Blatrix, Champlain Djiéto-Lordon  . Collec-Science l'a accepté mais il n'a pas compris que c'était deux valeurs. Est ce qu'il fallait écrire ainsi "Rumsaïs Blatrix", "Champlain Djiéto-Lordon" ? 

De façon générale, j'ai un peu de mal avec la gestion des métadonnées - et avec ma mémoire ! (à quoi sert la liste des valeurs que je mets dans choix possible (ca n'a pas l'air bloquant)? Est ce que je dois tout remettre dans mon fichier quand je fais un import en csv (ou est ce cumulatif) ? Est- ce qu'il y a une doc qui décrit cela ?

MCQ

**Comment by cplumejeaud** [comment]
Salut Marie-Claude,

il faut tout remettre dans ton fichier CSV (si on parle de celui qui
spécifie les listes de choixà. Demain, je testerai ton cas avec les 2
personnes
"Rumsaïs Blatrix", "Champlain Djiéto-Lordon"

A demain
Christine

Christine Plumejeaud
Ingénieure de recherche,
  <http://lienss.univ-larochelle.fr/Formation-interne>Correspondante
formation LIENSs (après connexion sur l'Intranet)
<http://lienss.univ-larochelle.fr/?page=login_public&url=rubrique503&id_rubrique=503>
 : http://lienss.univ-larochelle.fr/Formation-permanente
<http://lienss.univ-larochelle.fr/Formation-interne>
Responsable Plateforme DISA (Données : Intégration, Structuration et
Analyse).
Littoral Environnement et Sociétés (LIENSs), UMR 7266
2 rue Olympe de Gouges
17000 La Rochelle
+(33) - 05 16 49 67 83
christine.plumejeaud-perreau@univ-lr.fr
https://orcid.org/0000-0001-9271-3355
<christine.plumejeaud-perreau@univ-lr.fr>

**Comment by quidoz** [comment]
Bonjour
A la relecture de mon message, il n'était pas clair.  Je le complète

**Dans le fichier csv qui me permet d’importer les échantillons**, pour saisir deux informations dans une métadonnée à choix multiple, j'ai séparé les deux termes par des virgules. Par exemple dans le champ md_recoltant, j'ai indiqué Rumsaïs Blatrix, Champlain Djiéto-Lordon . Collec-Science l'a accepté mais il n'a pas compris que c'était deux valeurs. Est ce qu'il fallait écrire ainsi "Rumsaïs Blatrix", "Champlain Djiéto-Lordon" ?

De façon générale, j'ai un peu de mal avec la gestion des métadonnées - et avec ma mémoire ! (à quoi sert la liste des valeurs que je mets dans choix possible (ca n'a pas l'air bloquant)? Est ce que je dois tout remettre dans **mon fichier csv des métadonnées** quand je fais un import en csv (ou est ce cumulatif) ? Est- ce qu'il y a une doc qui décrit cela ?

MCQ

**Comment by equinton** [comment]
En fait, les métadonnées sont stockées au format json. Pour stocker des multi-valeurs, il faut respecter la syntaxe Json, à savoir :
["valeur1","valeur2"]
Dans un csv, les champs doivent être séparés par un ;
