### ISSUE TITLE
import en masse : sampling_date

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#279]
Bonjour

Dans la vérification de l'imprort en masse il n'a pas signalé que 2006-00-01 était problématique  ainsi que le symbome ? dans le champ date. Pr contre à l'insertion il m'a dit 
Line 185 : error when import sample - SQLSTATE[22008]: Datetime field overflow: 7 ERREUR: valeur du champ date/time en dehors des limites : « 0-06-20 » HINT: Peut-être avez-vous besoin d'un paramètrage « datestyle » différent.

J'en profite pour poser une question : le format de la date est forcément année-date-jour ? on ne pourrait pas avoir année ou année-mois dans la même collection ?

**Comment by equinton** [comment]
L'appli ne peut pas tout détecter : il y a déjà pas mal de contrôles, et certains cas de figures résistent aux tests...
Concernant le stockage des dates, il n'existe pas de norme dans les bases de données permettant de gérer correctement des dates incomplètes (jour ou mois manquant) : il faut impérativement : 

- soit définir une règle (on fixe au 1er jour du mois ou au 1er jour de l'année)
- soit créer des champs dédiés.

La première solution est la seule utilisable avec Collec-Science : ce serait beaucoup trop "usine à gaz" de gérer avec la seconde approche. C'est toutefois une solution que j'utilise dans l'importation de données historiques, pour d'autres projets, mais cela complexifie ensuite le travail d'analyse des chercheurs.

**Comment by quidoz** [comment]
Bonjour

 

L’application détecte 2001-00-00 (et le signale)  mais pas 2001-00-01, je ne vois pas la différence entre les deux (dans les deux cas ce n’est pas un format date). C’est un peu la même chose avec ?

 

MCQ
