### ISSUE TITLE
rechercher des échantillons - libellés différents pour les listes de sélection

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#280]
Bonjour
Je ne comprend pas pourquoi dans le champ type, il n'y a pas la valeur "sélectionnez", c'est à dire ne pas mettre de valeur (pour pouvoir revenir à un état vierge, j'ai du me déconnecter et me reconnecter)
Je ne comprend pas pourquoi pas défaut dans le champ statut c'est la valeur "état normal" qui est sélectionné (et en plus on ne peut pas rechercher dessus - cf question rechercher des contenants avec statut #275)

**Comment by quidoz** [comment]
Je viens de remarquer que dans collection et référent, c’est marqué "choisissez" et dans d'autres "Sélectionnez"

**Comment by equinton** [comment]
Le champ "type" est un champ permettant de taper un libellé pour rechercher les valeurs correspondantes, cela évite d'avoir à dérouler l'ensemble de la liste (idem pour les lieux de prélèvements). 
Pour effacer la zone, il suffit de sélectionner le texte et d'appuyer sur la touche <suppr>

Ticket conservé pour les aspects libellés (zone "recherche par date" avec le libellé "Sélectionnez", autres champs avec "Choisissez".

**Comment by quidoz** [comment]
Bonjour

 

En tant qu’utilisateur lambda , je pense que toutes les champs devraient présenter la même type d’interface (style on choisit dans une liste déroulante ou on tape les premières lettres du mot) ainsi que la même façon de reinitialiser le champ

 

A+

 

MCQ

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie
