### ISSUE TITLE
version 2.3 et certificat auto signé

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#286]
Bonjour
Je viens de migrer en 2.3. Je rencontre des problèmes avec le certificat auto signé que j'utilise (y a des pages qui s'affichent bien style la connexion (https://collection.cefe.cnrs.fr/index.php) et d'autres qui refusent de s'afficher style la liste des échantillons (https://collection.cefe.cnrs.fr/index.php?module=sampleList). Le message affiché dans ce cas la est : Strict-Transport-Security : la connexion au site n’est pas digne de confiance, l’en-tête spécifié a été ignoré.[En savoir plus]
MCQ

**Comment by equinton** [comment]
Bonjour Marie-Claude,
Peux-tu m'indiquer avec quel navigateur tu travailles ?
Sinon, pour régler le problème :
- éditer le fichier .htaccess à la racine de l'application
- supprimer les lignes :
Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains;"
Header set Strict-Transport-Security "max-age=63072000"

Je ferai des tests pour voir si je peux affiner la config.

**Comment by quidoz** [comment]
Bonjour

 

J’ai essayé avec Chrome et Firefox

 

A+

 

MCQ

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

 

De : Eric Quinton [mailto:notifications@github.com] 
Envoyé : jeudi 22 août 2019 13:59
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] version 2.3 et certificat auto signé (#286)

 

Bonjour Marie-Claude,
Peux-tu m'indiquer avec quel navigateur tu travailles ?
Sinon, pour régler le problème :

*	éditer le fichier .htaccess à la racine de l'application
*	supprimer les lignes :
Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains;"
Header set Strict-Transport-Security "max-age=63072000"

Je ferai des tests pour voir si je peux affiner la config.

**Comment by quidoz** [comment]
Bonjour

 

J’ai tjs le même problème. Voici mon .htaccess

 

more /var/www/html/collec/.htaccess

<LimitExcept GET POST>

Deny from all

</LimitExcept>

Options -Indexes

php_flag session.cookie_httponly on

php_flag session.cookie_secure on

php_flag register_globals off

php_flag magic_quotes_gpc true

php_flag display_errors Off

Header unset X-WebKit-CSP

Header add X-WebKit-CSP "default-src 'self'"

Header unset ETag

Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate, private"

Header set Pragma "no-cache"

Header set X-Frame-Options SAMEORIGIN

Header set X-XSS-Protection "1; mode=block"

Header set X-Content-Type-Options "nosniff"

Header set Content-Security-Policy "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' 'unsafe-inline'; img-src 'self' data: *.openstreetmap.org 'unsafe-inline'; style-

src 'self' 'unsafe-inline';"

<FilesMatch "\.(ico|flv|jpg|jpeg|png|gif|js|css|swf)$">

    Header set Cache-Control "max-age=604800, private"

</FilesMatch>

MCQ

**Comment by equinton** [comment]
essaie de redémarrer le serveur apache : il est possible qu'il reste des caches qui n'ont pas été réinitialisés

**Comment by quidoz** [comment]
Bonjour

Déjà fait mais sans succès. 

De plus, j’ai un truc bizarre que tu n’as pas sur ta version de test



MCQ

**Comment by quidoz** [comment]
Le problème venait des droits dans la base de données PostGreSQL

MCQ
