### ISSUE TITLE
recherche des échantillons avec uniquement date de creation dans la base

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#288]
Un problème est survenu lors de l'exécution de la requête. Contactez votre administrateur pour obtenir un diagnostic. SI on rajoute un autre critère, c'est OK

**Comment by equinton** [comment]
Rajouter un espace manquant dans la ligne 362 de modules/classes/sample.class.php ainsi (avant s.$field) : 
$where .= $and . " s.$field::date between :date_from and :date_to";

**Comment by quidoz** [comment]
C’est OK maintenant
