### ISSUE TITLE
des ... à mauvais escient ? 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#292]
des ... à mauvais escient ? 

![image](https://user-images.githubusercontent.com/29607993/63871989-3794a080-c9bd-11e9-8c86-def0c7196ae1.png)

![image](https://user-images.githubusercontent.com/29607993/63872123-86423a80-c9bd-11e9-9ec4-8abf4498136e.png)

**Comment by equinton** [comment]
Pb spécifique à Chrome. Corrigé en modifiant la feuille de style.
