### ISSUE TITLE
PB : Export CVS

### ISSUE THREAD

**Issue by Bismuth69** [Irstea/collec#293]
Lorsque l'on veut exporter un collection au format CSV : https://banquise.irstea.fr/index.php?module=sampleList

Si on clique sur le bouton bleu "Fichier CVS", l'export est limité à 999 lignes.
Idem pour "Export vers une autre base".

En revanche, le bouton gris "CSV" semble permet d'exporter l'intégralité d'une sélection.

**Comment by equinton** [comment]
Pour corriger le problème, il faut modifier le paramètre suivant dans /etc/php/7.2/apache2/php.ini : 
max_input_vars = 10000
