### ISSUE TITLE
colonne emplacement vide ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#295]
Si je liste (avec l'onglet contenants présents), le contenu de mon placard ![image](https://user-images.githubusercontent.com/29607993/64022549-caa51600-cb36-11e9-95b4-aafe83a146f7.png) la colonne emplacement est vide. Par contre si j'utilise l'ongle "grille d'objets", l'emplacement est bien utilisé 
![image](https://user-images.githubusercontent.com/29607993/64022761-2e2f4380-cb37-11e9-8938-9cf7cbc53e71.png)

**Comment by equinton** [comment]
Il s'agit de l'emplacement "textuel", qui est différent de l'emplacement ligne/colonne.
Je complète.
