### ISSUE TITLE
date d'echantillonage

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#300]
J'ai des dates vraiment étranges dans date de création/échantillonnage. Il ne me semble pas que j'avais cela avant

![image](https://user-images.githubusercontent.com/29607993/64545912-f17afd80-d329-11e9-8473-b67a3986fee6.png)

**Comment by equinton** [comment]
oui, c'est normal. Un labo a besoin de connaître l'heure exacte d'échantillonnage : les dates ont été transformées en date-heure (c'est juste un changement de paramétrage, le stockage en base était déjà dans ce format).

**Comment by quidoz** [comment]
c’est la date qui me choque (2020)
