### ISSUE TITLE
Référent de l'échantillon pour un contenant

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#301]
J'ai du mal avec la notion de référent (j'ai prévu d'ajouter cette définition au lexique mais pour l'instant je ne sais pas quoi mettre) mais encore plus quand dans la création d'un contenant on me demande le référent de l'échantillon ![image](https://user-images.githubusercontent.com/29607993/64703509-de446b00-d4ac-11e9-9d79-81ad03c8ad7a.png)

**Comment by equinton** [comment]
À modifier : le libellé dans l'écran
Précision sémantique : le référent d'un contenant est celui qui est responsable du contenant. En général, il n'est renseigné que pour les pièces utilisées pour le stockage (c'est la personne qui dit où ranger les échantillons) ou les matériels techniques susceptibles de tomber en panne (frigo, p. e.)
