### ISSUE TITLE
tri alphabétique dans famille de contenant

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#314]
Bonjour
Un bug ou pas. je n'en sais rien. mais si on met étagère (avec un accent) c'est classé à la fin de la liste alphabétique. C'est pas terrible

![image](https://user-images.githubusercontent.com/29607993/69233619-80f42680-0b8d-11ea-8877-266c82bf547a.png)

**Comment by equinton** [comment]
https://www.datatables.net/blog/2017-02-28

**Comment by equinton** [comment]
Test en rajoutant le plugin intl pour DataTables, mais sans succès.
En stand-by pour le moment
