### ISSUE TITLE
tracabilité des insertions par fichiers

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#317]
Bonjour 
Est ce qu'il y a une table dans la BD qui conserve cette information (import effectué : nb de lignes traitées / premier UID généré et dernier UID généré ainsi que le nom du fichier / date voir le separateur utilisé et l'encodage du fichier). Ca pourrait être super utile pour détruire toutes les lignes d'un fichier mal importé (comme moi avec de mauvais format de date)

![image](https://user-images.githubusercontent.com/29607993/69246635-5a43e900-0ba9-11ea-85ec-1ffdd6f41e51.png)

**Comment by equinton** [comment]
Enregistrement dans les logs des UID générés
Ajout d'une fonctionnalité de consultation des logs enregistrées
