### ISSUE TITLE
séparateur dans les champs json

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#318]
Bonjour
il est également possible de définir les métadonnées avec un attribut par colonne. Dans ce cas, la colonne doit être nommée md_nomAttribut, par exemple : md_taxon. 
Est ce que je pourrais avoir un exemple de la syntaxe à mettre pour les valeurs  (par exemple quand j'ai deux valeurs pour mon attribut)

**Comment by equinton** [comment]
Il s'agit d'un format JSON (le même que celui utilisé pour les collections par Python).
ex : {"monchamp":[val1,val2]}
Ce qui se traduit, dans une colonne de type md_ dans un fichier CSV, par : 
[val1,val2]

**Comment by quidoz** [comment]
Bonjour

J’ai essayé avec ce fichier sur la première ligne, ça ne marche pas. Où est l’erreur ?

sample_identifier       md_taxon       md_phenology           md_phenotype           md_nature            sample_type_id          sampling_date           wgs84_y          wgs84_x          md_recoltant            container_parent_uid            collection_id   sample_status_id

BF10F  Tetraponera aethiops                        individus         1          17/03/2009     3.66291           10.11242            ["Rumsaïs Blatrix", "Champlain Djiéto-Lordon"]      430      1          1

BF118F            Tetraponera aethiops                        individus         1          08/03/2007     3.09146            13.61436         Charles Doumenge    430      1          1

BF119F            Tetraponera aethiops                        individus         1          07/03/2007     2.87665            13.90856         Charles Doumenge    430      1          1

BF11F  Tetraponera aethiops                        individus         1          17/03/2009     3.76444           11.1958            [Rumsaïs Blatrix, Champlain Djiéto-Lordon]            430      1          1

BF120F            Tetraponera aethiops                        individus         1          07/03/2007     3.02014            13.82301         Charles Doumenge    430      1          1

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

 

De : Eric Quinton [mailto:notifications@github.com] 
Envoyé : lundi 25 novembre 2019 09:49
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] séparateur dans les champs json (#318)

 

Il s'agit d'un format JSON (le même que celui utilisé pour les collections par Python).
ex : {"monchamp":[val1,val2]}
Ce qui se traduit, dans une colonne de type md_ dans un fichier CSV, par :
[val1,val2]
