### ISSUE TITLE
fichier csv du type d'echantillon

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#319]
Bonjour

Ca serait bien de pouvoir faire un fichier csv de cette liste 

![image](https://user-images.githubusercontent.com/29607993/69255640-78651580-0bb8-11ea-827d-aeb14107d7d1.png)

**Comment by equinton** [comment]
Bonjour Marie-Claude,

Le fichier CSV, c'est pour pouvoir importer dans une autre instance ?

Merci,

Éric.

**Comment by quidoz** [comment]
Bonjour

non pour avoir une sortie que l'on peut importer sous excel

MCQ

Le 09/01/2020 à 11:30, Eric Quinton a écrit :
