### ISSUE TITLE
donner un exemple pour les imports de masse

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#320]
Bonjour
Ca serait bien de mettre un exemple pour les Import d'échantillons ou de contenants à partir d'un fichier CSV, car c'est un peu galère pour savoir comment écrire les choses. Par exemple pour les latitudes et longitudes, il faut mettre des points et non des virgules. Pour les champs md_xx on ne sait pas la syntaxe qu'il faut mettre.

**Comment by equinton** [comment]
Ajout d'exemples et de précisions dans le texte explicatif
