### ISSUE TITLE
message "vous ne disposez pas des droits nécessaires pour supprimer l'echantillon"

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#323]
Bonjour

J'ai fait 3 copies d'écran (avant et après). Il me dit que je ne peux pas supprimer l’échantillon 1915 et pourtant il le fait. Je me demande si ca ne vient pas du fait que ma BDD est bizarroïde car j'ai mis les métadonnées obligatoires et vu le "bug" actuel pour importer les métadonnées avec des md_*** j'importe des échantillons sans métadonnées

![image](https://user-images.githubusercontent.com/29607993/70456133-d6956200-1aad-11ea-8f13-a8904f258054.png)

![image](https://user-images.githubusercontent.com/29607993/70456347-3be95300-1aae-11ea-9b37-7d79574cfd15.png)

![image](https://user-images.githubusercontent.com/29607993/70456422-5b807b80-1aae-11ea-81f8-4c71199bbcf3.png)

**Comment by equinton** [comment]
Non reproduit dans la version de développement
Quelques corrections du script (meilleure gestion des erreurs potentielles)
