### ISSUE TITLE
ajouter "à droite à gauche"

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#325]
Bonjour

Je ne sais pas si c'est possible (car ca a des conséquences sur la représentation ensuite) mais ca serait sympa si on pouvait mettre de droite à gauche pour les plateaux des étagères

![image](https://user-images.githubusercontent.com/29607993/70643699-be564c00-1c41-11ea-8958-8f404bf13df4.png)

**Comment by equinton** [comment]
Coûteux pour l'affichage, à voir...

Fonction array_reverse utilisable avec Smarty ?
