### ISSUE TITLE
lieu de prélévement

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#326]
Bonjour

J'ai l'impression que les latitudes et longitudes indiquées lors de la création d'un lieu de prélèvement ne sont pas utilisés (NDR : pas de carte)

![image](https://user-images.githubusercontent.com/29607993/70908252-0642ed80-200b-11ea-8237-b9f6815073da.png)

**Comment by equinton** [comment]
Il y a une protection pour éviter d'écraser des coordonnées qui auraient déjà été saisies. Pour que la longitude et la latitude soient mises à jour quand on sélectionne un lieu de prélèvement, il faut que celles-ci soient vides auparavant.
