### ISSUE TITLE
ratachement à plusieurs collections 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#327]
Bonjour

Je trouve dommage que l'on ne puisse pas indiquer pour certains paramètres en l’occurrence lieu de prélèvement et type d'échantillons, l'appartenance à plusieurs collections. Ça fait dupliquer l'information et oblige à nommer "bétement" des choses pour les distinguer

**Comment by equinton** [comment]
- pour les lieux de prélèvement, il suffit de ne pas indiquer de collection pour que ceux-ci soient disponibles pour toutes les collections. Basculer à un mode de fonctionnement n-n est possible, mais coûteux en complexité et en efficacité. Le jeu en vaut-il la chandelle ? 
- pour le type d'échantillons, je ne comprend pas la question : ils ne sont pas rattachés aux collections.

**Comment by quidoz** [comment]
Bonjour

*	pour le type d'échantillons, je ne comprend pas la question : ils ne sont pas rattachés aux collections.

T’as raison. C’est moi qui bêtement avait ajouté le nom de la collection dans le nom du type d’échantillon

**Comment by quidoz** [comment]
Bonjour

 

*	pour les lieux de prélèvement, il suffit de ne pas indiquer de collection pour que ceux-ci soient disponibles pour toutes les collections. Basculer à un mode de fonctionnement n-n est possible, mais coûteux en complexité et en efficacité. Le jeu en vaut-il la chandelle ?

Non ca n’en vaut pas la chandelle. Suffit de ne pas mettre de collection lors de la saisie. Je l’ai indiqué dans le lexique
