### ISSUE TITLE
echantillon détruit -> lieu de stockage ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#328]
Bonjour

Quand on passe un échantillon de statut normal à statut détruit, est ce que ça ne pourrait pas lever une alerte en indiquant qu'il faut agir au niveau du lieu de stockage (sinon on provoque des incohérences)

**Comment by equinton** [comment]
Ajouter une fonctionnalité de sortie quand le statut passe à "détruit", et si l'échantillon est toujours référencé dans un container.

**Comment by equinton** [comment]
Création du mouvement de sortie quand le statut passe à détruit.
