### ISSUE TITLE
améliorer la documentation pour les imports de masse

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#329]
Bonjour

En lisant cette documentation,  on a l’impression que les informations sur les échantillons sont obligatoires pour créer des échantillons

![image](https://user-images.githubusercontent.com/29607993/70911626-8de02a80-2012-11ea-93fe-534c18816a45.png)

**Comment by equinton** [comment]
Peux-tu proposer une autre rédaction ou des améliorations au texte ?

**Comment by quidoz** [comment]
Bonjour

 

Peut être que la meilleure solution serait de faire deux « interfaces » 

-          Une pour la création de contenant  

o    container_identifier : l'identifiant du contenant (obligatoire)

o    container_type_id : le numéro informatique du type de contenant (obligatoire)

o    container_status_id : le numéro informatique du statut du contenant (obligatoire)

o    container_location : l'emplacement de rangement du contenant dans son parent (texte libre)

o    container_column : n° de la colonne de stockage dans le contenant parent

o    container_line : n° de la ligne de stockage dans le contenant parent

o    container_parent_uid : l'UID du contenant parent

-          Une pour la création de l’échantillon avec le contenant (la documentation actuelle)

 

Ou alors indiquez dans le texte en bas de l’import qu’il est possible de créer uniquement les contenants si on renseigne uniquement les paramètres qui commencent par container_

 

 

 

 

+++++++++++++++++

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

 

De : Eric Quinton [mailto:notifications@github.com] 
Envoyé : mardi 17 décembre 2019 10:58
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Assign <assign@noreply.github.com>
Objet : Re: [Irstea/collec] améliorer la documentation pour les imports de masse (#329)

 

Peux-tu proposer une autre rédaction ou des améliorations au texte ?
