### ISSUE TITLE
changement de mot de passe et message bizarre

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#342]
Bonjour
Pour réaliser des essais, je me suis créé hier soir un compte invite. Ce matin quand je me connecte avec le compte invite, il me dit que je dois changer rapidement le mot de passe (NDR : je n'ai gardé le message) mais quand je clique sur "modifier le mot de passe', il me dit 
Le mode d'identification utilisé pour votre compte n'autorise pas la modification du mot de passe depuis cette application

**Comment by equinton** [comment]
Il faudrait tester en :
- se déconnectant
- se reconnectant
- faire immédiatement la modification du mot de passe.

Il y a un mécanisme d'identification "caché" par cookie, qui évite d'avoir à se reconnecter dans la journée, et quand ce mécanisme est activé, la modification du mot de passe est inhibée.

**Comment by equinton** [comment]
correction effectuée pour tenir compte des token
