### ISSUE TITLE
Test version2.4 - recherche échantillons

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#356]
Bonjour

Merci pour cette prise en compte mais çà serait bien de revenir (après avoir cliqué sur recherche) sur l'onglet que l'on avait choisi (par exemple Localisation)

**Comment by quidoz** [comment]
Ca permettrait de voir ainsi les critères de recherche que l'on a mis

**Comment by equinton** [comment]
Un effet de bord du rajout de la cartographie dans l'affichage...

**Comment by equinton** [comment]
Ca fonctionnait en pré-version, une modification malheureuse a entraîné la non génération du cookie permettant de stocker l'onglet sélectionné.
