### ISSUE TITLE
Test version2.4 - corbeille ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#357]
Bonjour
ce terme apparait suivi d'un ? sur certains menus de la recherche d'échantillon. je ne le vois pas défini dans le lexique.  SI je regarde dans échantillon je vois qu'il est possible de mettre un échantillon dans une corbeille. Il doit y avoir une nuance avec la notion de statut car sinon il serait une valeur de ce champ  mais j'avoue ne pas savoir à quoi il correspond ...

**Comment by equinton** [comment]
La corbeille est un emplacement pour "jeter" un objet, avant sa destruction complète.
Elle a été implémentée pour gérer les échanges automatiques entre bases de données : il faut pouvoir indiquer qu'un échantillon est supprimé (dans les faits : placé à la corbeille).
Dans le processus d'échange :
- échantillon placé à la corbeille
- transmission de l'information à la base de données distante
- possibilité de refaire la transmission en cas de problème
- suppression définitive de l'échantillon quelque temps après.
On aurait pu gérer ça avec un statut, mais cela posait d'autres problèmes : le recours à un champ dédié est plus simple.

**Comment by quidoz** [comment]
OK Faudrait trouver une autre façon de le rechercher. Je dirai par l'ajout d'un onglet supplémentaire réservé à ce mode de recherche  pour les échantillons et les contenants

**Comment by equinton** [comment]
Libellé changé et remplacé par : en attente de suppression
