### ISSUE TITLE
Test version2.4 - Echantillon - recherche par localisation

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#358]
Bonjour
Si je prend l'onglet "Echantillons- Localisation et je choisis comme lieu de prélèvement "Estuaire de la Gironde" j'ai 12 réponses avec la liste et avec la carte 8 réponses (dont 2 avec des coordonnées bizarres). Je soupçonne qu'avec la liste il cherche le terme "Estuaire de la Gironde" dans lieu de prélèvement et qu'avec la liste il regarde les coordonnées ! 
Est ce normal qu'il y ait une incohérence entre les deux ?

**Comment by equinton** [comment]
La carte travaille à partir des coordonnées géographiques enregistrées dans l'échantillon.
La liste des lieux de prélèvements travaille à partir de la liste éponyme.
Il n'est donc pas anormal que les recherches ne ramènent pas exactement les mêmes choses, surtout dans une base de test...

**Comment by quidoz** [comment]
tu veux dire que dans une vrai base, j'aurai forcément la même chose des deux cotés ?

**Comment by equinton** [comment]
pas forcément, ce sont deux notions différentes. La cartographie travaille à partir des données xy, les localisations précisent une zone générique (un lac, une station, etc.).
Si un échantillon se voit affecté une localisation dont les coordonnées xy ont été définies, alors il récupérera automatiquement ces coordonnées. Mais si la station n'a pas de coordonnées, et que l'échantillon n'est pas positionné, il n'aura alors aucune coordonnée.
