### ISSUE TITLE
Test version2.4 - Echantillon - recherche par localisation

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#359]
Bonjour
Le RAZ ne remet pas à zéro le résultat des recherches.

**Comment by equinton** [comment]
Le RAZ remet à zéro les critères de recherche, mais ne supprime pas la liste.

**Comment by quidoz** [comment]
C'est dommage

**Comment by equinton** [comment]
Intellectuellement, on pourrait supprimer la liste, mais je ne suis pas sûr que cela représente un quelconque intérêt. Le RAZ intervient quand on veut réaliser une nouvelle requête, et celle-ci ne sera de toute façon déclenchée qu'après appui sur le bouton _ad hoc_
