### ISSUE TITLE
Test version2.4 - Protocoles

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#361]
Bonjour
J'ai testé l’ajout d'un fichier pdf dans la définition d'un protocole. Ca marche bien mais je ne sais pas comment le supprimer maintenant ?
![image](https://user-images.githubusercontent.com/29607993/74856874-219be300-5343-11ea-9bed-38948c7187e3.png)

**Comment by equinton** [comment]
Corriger en ajoutant la possibilité de supprimer la pièce jointe
