### ISSUE TITLE
Test versionV2.4 - type d'echantillon

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#364]
Bonjour
Il reste l'UID pour protocole / opération dans cet écran
![image](https://user-images.githubusercontent.com/29607993/74936865-3469f280-53eb-11ea-8768-8b2f0b035c99.png)

**Comment by equinton** [comment]
Pas compris la remarque ?

**Comment by quidoz** [comment]
Bonjour

Dans la colonne protocole/opération, c’est indiqué 2020 Protocole…. Je pense que le 2020 est l’UID

MCQ

**Comment by equinton** [comment]
Non, c'est l'année du protocole...

**Comment by quidoz** [comment]
ok

De : Eric Quinton <notifications@github.com>
Envoyé : jeudi 20 février 2020 16:08
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] Test versionV2.4 - type d'echantillon (#364)


Non, c'est l'année du protocole...
