### ISSUE TITLE
Test version2.4 - import de contenants externe

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#365]
Bonjour
Pour faire de vrai test, j'ai voulu utiliser cette fonction pour récupérer un fichier que j'avais fait sur la version en production (NDLR : je ne me rappelle plus comment j'ai fait ce fichier). Il me dit 👍 (Je pex t'envoyer le fichier pour tester)
![image](https://user-images.githubusercontent.com/29607993/74939425-24084680-53f0-11ea-9802-eef9daf17b98.png)

**Comment by equinton** [comment]
Fais-moi parvenir le fichier, que je regarde ce qu'il se passe.
Il est possible que ce ne soit pas la bonne fonction d'importation que tu as utilisée. Est-ce bien un fichier .json que tu veux importer ?

**Comment by quidoz** [comment]
Bonjour

Je te l’envoie par filesender

A+

MCQ

De : Eric Quinton <notifications@github.com>
Envoyé : jeudi 20 février 2020 15:45
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] Test version2.4 - import de contenants externe (#365)


Fais-moi parvenir le fichier, que je regarde ce qu'il se passe.
Il est possible que ce ne soit pas la bonne fonction d'importation que tu as utilisée. Est-ce bien un fichier .json que tu veux importer ?

**Comment by quidoz** [comment]
Bonjour
T’es arrivée à reproduire le bug ?
MCQ

.

**Comment by equinton** [comment]
Le module s'adapte assez mal à un export global de tous les containers : les mêmes containers peuvent être exportés plusieurs fois, et les échantillons qu'ils contiennent également.
Pour ce genre d'opération, il vaut mieux utiliser le module expérimental (paramètres > modèles d'export), mais qui n'est pas encore couplé avec les listes d'objets.

Il faudrait refaire un test en ne sélectionnant que les parents de même niveau (ne pas choisir des containers qui sont eux-mêmes contenus dans d'autres containers de la liste).
