### ISSUE TITLE
Compléter l'import des échantillons

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#37]
En import des échantillons, rajouter :
-les identifiants "métier" secondaires
- les coordonnées géographiques
- le champ de métadonnées (metadata ?)
- le lieu de prélèvement

**Comment by cplumejeaud** [comment]
Exemple de modèle : à gauche les noms des colonnes, à droite des valeurs exemple. 
Note : un fichier avec une macro pour faire le JSON et expliquant bien l'exemple sera mis à disposition.

sample_identifier	LDB10-06A
project_id	1
sample_type_id	1
sample_status_id	1
sample_date	41059
sample_location	B4
sample_multiple_value	104
container_type_id	7
container_status_id	1
container_location	C1 P2
container_parent_uid	11
igsn	IEFRA00NW
location	BOURGET
wgs84_y	45.761944
wgs84_x	5.854944
sample_metadata_json	{SITE":"BOURGET","TYPE":"SEDIMENT","SAMPLE_NAME":"LDB10-06A","LONGUEUR":"104","PROFONDEUR":"","PI":"JENNY JP (ORCID:0000-0002-2740-174X)"}"

**Comment by equinton** [comment]
Pour location, comme on a une table de paramètres, il faudra indiquer la clé de la table de paramètres (comme pour les autres infos comme status, type...).

**Comment by hlinyer** [comment]
Implémenté sur feature_metadata
