### ISSUE TITLE
test version 2.4 - une crois pour fermer la fenetre de resumé sur l'échantillon

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#372]
Bonjour

Ca serait sympa d'avoir une croix pour fermer la fenêtre de résumé de l'échantillon  (parfois on a du mal à s'en débarrasser). ça pourrait être aussi sympa que ça soit une option de collec-science (est ce que l'on veut ou pas l'afficher pendant la session)

![image](https://user-images.githubusercontent.com/29607993/75272397-1a228100-57fe-11ea-83a5-1d7e9c1d7b48.png)

**Comment by equinton** [comment]
augmentation de la durée d'attente à 1 seconde avant affichage du tooltip, pour limiter les effets de passages trop rapides
