### ISSUE TITLE
Test version 2.4 - affichage des popups pour le container

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#374]
Bonjour

Au niveau des contenants, on a un popup qui donne le contenu du container. Mon contenair contenant des enveloppes, le nombre de slots utilisés est élevé (ici + de 400) ce qui rend le contenu du popup inutilisable. Ca affiche que les derniers échantillons et il n'y a pas d'ascenseur

![image](https://user-images.githubusercontent.com/29607993/75353558-e9008a00-58ab-11ea-810d-47911b886eef.png)

**Comment by equinton** [comment]
Le nombre d'objets est affiché à la place de la liste si nb > 10
