### ISSUE TITLE
Test version 2.4 - echantillon - type et metadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#375]
Bonjour

Le RAZ ne marche pas si on avait choisi des métadonnées. 

De façon générale je me demande si cette recherche marche bien en tout cas je n'arrive pas à la faire marcher (par exemple je voulais tous les taxons qui commencent par b - j'ai mis b%- et ensuite tous ceux qui commencent par a - j'ai mis a%- et j'ai l'impression que ca n'en tient pas compte. PS : je ne sais peut être pas me servir de ce menu

![image](https://user-images.githubusercontent.com/29607993/75363444-67fcbf00-58ba-11ea-9db9-339fb5174579.png)

**Comment by equinton** [comment]
le % est rajouté automatiquement en début et fin de chaîne, et tout est transformé en minuscule.
La recherche fonctionne dans la version 2.4.0b, en cours de mise au point.

Le RAZ et l'affichage des métadonnées, et la recherche directe dans les métadonnées ont été corrigés.
