### ISSUE TITLE
En saisie de métadonnées, une liste de choix obligatoire n'est pas correctement initialisée

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#38]
J'ai créé un formulaire de métadonnées, comprenant une liste à choix multiple obligatoire.
Le premier choix est proposé à l'écran lors de la saisie, mais la valeur connue est considérée comme nulle
![capture du 2017-06-28 09-41-11](https://user-images.githubusercontent.com/6715861/27625857-463ed4b2-5be6-11e7-8af8-1e166eaed95f.png)

**Comment by hlinyer** [comment]
Résolu, à tester.
