### ISSUE TITLE
backup.sh

### ISSUE THREAD

**Issue by VDaric** [Irstea/collec#387]
Bonjour,

Petite erreur dans le script de sauvegarde **/var/lib/postgresql/backup.sh** (appelé par le cron de l'utilisateur postgres) retourne l'erreur suivante :

cp: impossible d'évaluer *'/etc/postgresql/11.7/main/pg_hba.conf'* : Aucun fichier ou dossier de ce type

Sous debian 10 le fichier pg_hba.conf se trouve dans le répertoire **/etc/postgresql/11/main/pg_hba.conf**

Voici la modification qui corrige l'erreur chez moi :+1: 
[backup.sh.patch.txt](https://github.com/Irstea/collec/files/4308262/backup.sh.patch.txt)

Je suis sou debian 10 (buster). Tout y est par defaut, installation faite via le script deploy_new_instance.sh sans rien modifier.

Merci !
Cordialement

**Comment by equinton** [comment]
ok, merci. C'est lié au changement de numérotation des versions de Postgresql, et je n'y ai pas fait attention. Je corrige pour la prochaine livraison.
