### ISSUE TITLE
Test Version 2.4.0.b : accès aux statistiques pas seulement lors de la connection

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#388]
Bonjour

Ca serait  sympa d'avoir accès aux statistiques pas seulement lors de la collection

![image](https://user-images.githubusercontent.com/29607993/76244897-3e894f00-623b-11ea-9ce3-cc91f1038b81.png)

**Comment by equinton** [comment]
il suffit de revenir sur la page d'accueil, en cliquant sur l'icone ou le nom de l'instance.

**Comment by quidoz** [comment]
C'est OK
MCQ
