### ISSUE TITLE
Test Version 2.4.0.b : module recherche échantillons

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#391]
Bonjour
Je viens de m'apercevoir que quelque soit l’onglet que l'on utilise pour faire la recherche d’échantillon, ca "active" la recherche dans les 4 (UID/identifiant, Type et métadonnées, Divers, Localisation). C'est un brin piégieux. je pensais qu'ils étaient indépendants mais une fois que l'on sait ca le fait

**Comment by equinton** [comment]
oui, c'est pour ça qu'on a un bouton de remise à zéro disponible sous la boite d'onglets.
Si on voulait avoir un fonctionnement spécifique à chaque onglet, ça aurait été trop complexe à développer, et l'interface en aurait été surchargée.
