### ISSUE TITLE
Test Version 2.4.0.b : quelques remarques sur structure de la base de données

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#392]
Bonjour

Manque le titre pour col.borrowing, col_campaign_regulation, col.operation, col.protocol, gacl.logingestion. Certains sont en français, d'autres en anglais

Dans col.borrowers par exemple on ne voit pas indiqué dans le nom de la clef étrangère dans foreign key. Mais dans  col.collection_group on le voit 

Il y a des tables sans clef primaire style col.campaign_regulation

Ca pourrait être sympa que l'on est accès dans ce menu à la version PDF de la structure (on y accès dans la partie requete SQL)

**Comment by equinton** [comment]
Pour le dernier point, il suffit de cliquer sur le menu : _schéma de la base de données >_

**Comment by equinton** [comment]
col.borrowers n'a pas de clé étrangère, il s'agit d'une table de paramètres de niveau 1.

**Comment by quidoz** [comment]
J'ai mal interprété le terme "Referenced by : borrower_id: col.borrowing (borrower_id)" alors ?

**Comment by equinton** [comment]
borrowed_id : le champ dans la table courante. col.borrowing(borrower_id) : la table qui pointe vers la table courante, avec le champ impliqué.
