### ISSUE TITLE
Test Version 2.4.0.b : difficulté de compréhension de la fonctionnalité imprimante

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#393]
Bonjour

Je suis en train de tester l'impression d’étiquette sur une imprimante connectée à un poste windows (attention ce n'est pas le poste avec lequel je fais mes requêtes) et j'avoue avec du mal avec ce menu. 
J'avoue que je ne sais pas ce qu'il faut mettre dans nom de la file d'impression. En tout cas quand je tente impression directe il me dit "L'impression a échoué pour un problème technique"

![image](https://user-images.githubusercontent.com/29607993/76640288-f2e2e800-654f-11ea-84ae-ab89ac5dd91a.png)

**Comment by equinton** [comment]
C'est une fonction qui permet d'imprimer directement vers une imprimante connectée au serveur, et pas au poste de travail. La file d'attente doit avoir été déclarée dans le serveur Linux avec Cups, et un des deux clients d'impression (lp ou lpr) doit avoir été installé.
Cette configuration a été créée pour les environnements de terrain, où l'imprimante est reliée au serveur, les clients pouvant être des tablettes, par exemple.

Dans ton cas de figure, il faut que l'imprimante connectée au portable soit partagée, et qu'elle soit installée dans ton PC (imprimante réseau). Le mode opératoire ne change pas, c'est toujours le fichier PDF qu'il faut imprimer.

**Comment by quidoz** [comment]
Bonjour

Merci de l’explication. Ca serait bien de mettre l'information quelque 
part. Je peux le faire mais où  ? Lexique ? FAQ ?

Le 16/03/2020 à 09:10, Eric Quinton a écrit :

**Comment by equinton** [comment]
Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Le lundi 16 mars 2020 09:18, quidoz <notifications@github.com> a écrit :
Dans la faq du site web.

> Bonjour
>
> Merci de l’explication. Ca serait bien de mettre l'information quelque
> part. Je peux le faire mais où  ? Lexique ? FAQ ?

**Comment by quidoz** [comment]
Bonjour

Je soupçonne que tu veuilles le faire apparaitre ici 
https://www.collec-science.org/en/knowledge-base/ dans la rubrique 
impresssion et etiquette ? Il faut que je mette documentation et 
usage_fr comme catégorie ?

Est ce que tu peux me faire une entrée pour mettre " Rôle du bouton 
impression", histoire que je parte dans la bonne voie ?

Le 16/03/2020 à 09:32, Eric Quinton a écrit :
> Eric Quinton
>
> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by equinton** [comment]
Ajout d'une entrée dans la faq : [](https://www.collec-science.org/2020/03/26/imprimer-par-une-imprimante-reliee-au-serveur-role-du-bouton-impression-directe/)
