### ISSUE TITLE
Test Version 2.0.4.b : visualisation de la structure dans menu parametre etiquette

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#395]
Bonjour

- Ça serait sympa que dans ce menu, il y ait une possibilité de visualiser la "structure" de l'étiquette pour valider les champs et leur positionnement par exemple. Pour l'instant on est obligé de sélectionner un échantillon ou un container pour le faire. 

- De plus, il est marqué que dans le QRcode, le uid et le db sont obligatoires mais si tu ne les mets pas le logiciel ne gueule pas (cf mon modèle CEFE01-). Sont ils vraiment obligatoires ?

- Et pour finir, pourquoi est ce que l'on ne peut pas dans le QR code mettre ce que l'on veut. Pour ma part, j'aurai bien mis une combinaison de db, uid et un séparateur style '01-' pour être en continuité de ce que l'on faisait avant ?  

![image](https://user-images.githubusercontent.com/29607993/76646028-7efa0d00-655a-11ea-97be-478aa31f5377.png)

**Comment by quidoz** [comment]
- Dans la documentation, il est indiqué pour les champs utilisables dans le QR Code, cas général et cas particulier mais je n'ai jamais vu où on pouvait le préciser ?

**Comment by equinton** [comment]
- visualisation de la structure : ce n'est pas techniquement possible. L'étiquette est générée à partir d'une transformation d'un fichier xml via le traducteur xsl (le descriptif de l'étiquette). La solution que je préconise est de travailler avec deux navigateurs, l'un pour modifier le modèle, l'autre pour générer le pdf pour vérifier le contenu
- le uid et le db sont obligatoires, mais comme c'est du xsl, il serait très difficile de le "parser" pour vérifier qu'ils sont présents. De plus, il y a un cas particulier où un numéro simplement peut être mis dans l'étiquette (qrcode de petite dimension, p. e. 1 cm2), là où on ne peut pas mettre du contenu au format JSON
- dans l'étiquette, il faut différencier le qrcode, qui ne contient que des valeurs susceptibles d'être lues automatiquement, du contenu de l'étiquette, qui est libre. Rien n'empêche de mettre les libellés que l'on souhaite, par exemple : <fo:block>uid:<fo:inline font-weight="bold"><xsl:value-of select="db"/>:C'est mon libellé à moi:<xsl:value-of select="uid"/></fo:inline></fo:block>
- le cas particulier est activé quand on active "Etiquette ne comprenant qu'un identifiant métier ?" (cf. 2nd point dans ma réponse).

**Comment by equinton** [comment]
Ajout d'un bouton permettant de rester sur la page de modification de l'étiquette, pour faciliter sa mise au point
