### ISSUE TITLE
Métadonnées : informations saisies dans le descriptif non visibles en saisie des fiches

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#40]
Les champs "description du champ" et "unité" ou "modalités" sont obligatoires dans le formulaire, mais ces informations ne sont pas affichées quand on saisit un échantillon.

**Comment by cplumejeaud** [comment]
On a affiché le champs unité en grisé dans le champs de saisie pour rappeler l'unité du champ à saisir. Les autres champs serviront plus tard pour l'extraction et l'analyse des données.
