### ISSUE TITLE
2.5.0.B : ouvrir sur le détail d'un échantillon ou d'un contenant

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#414]
Bonjour
Je ne me rappelle plus pourquoi on a mis une possibilité d'ouvrir un autre échantillon ou contenant sur les détails d'un échantillon ou d'un contenant. En tout cas, après une longue interruption ca fait bizarre
![image](https://user-images.githubusercontent.com/29607993/91878086-1d9c3680-ec7f-11ea-9a56-08a8afe539b0.png)

**Comment by equinton** [comment]
C'était pour éviter de retourner à la liste pour ouvrir un nouvel échantillon, et accélérer le travail.

**Comment by quidoz** [comment]
Je comprends l’intérêt mais c’est pas très ergonomique

De : Eric Quinton <notifications@github.com>
Envoyé : mercredi 2 septembre 2020 11:46
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] 2.5.0.B : ouvrir sur le détail d'un échantillon ou d'un contenant (#414)


C'était pour éviter de retourner à la liste pour ouvrir un nouvel échantillon, et accélérer le travail.

**Comment by equinton** [comment]
Si tu as une idée d'amélioration...

**Comment by quidoz** [comment]
on pourrait pas mettre un truc style "acces rapide", le mettre à la même hauteur que les autres onglets mais le cadrer à droite et diminuer la taille des cadres (la ca fait mastoc)

**Comment by equinton** [comment]
J'ai réduit l'affichage sur les grands écrans, mais on ne peut pas trop le déplacer ailleurs : sur les petits écrans, c'est le seul endroit où ça n'empiète pas sur le reste.
![Capture d’écran de 2020-09-14 16-29-13](https://user-images.githubusercontent.com/6715861/93098768-859f4380-f6a7-11ea-9a11-6e5bfcd4cb46.png)

En petit écran : 
![Capture d’écran de 2020-09-14 16-30-26](https://user-images.githubusercontent.com/6715861/93098897-aa93b680-f6a7-11ea-8f5a-7367f0aa9e0f.png)

Qu'en penses-tu ?

**Comment by quidoz** [comment]
Bonjour

Le problème c'est que l'on ne sait pas à quoi ça sert . On a l'impression d'une "verrue" de développeur posée la. Ca ne serait pas mieux en dessus avec retour à la liste . nouvelle échantillon... avec un titre accès rapide à un échantillon

**Comment by equinton** [comment]
J'ai rajouté un lien "accès rapide" juste après la liste, qui affiche le formulaire actuel au survol (il est masqué par défaut).

**Comment by quidoz** [comment]
Bonjour

Il est effectivement masqué mais il s'affiche quand on passe la souris sur acces rapide  et ensuite il ne se remasque jamais

**Comment by quidoz** [comment]
Bonjour

De plus dans contenant tu n'as pas fait la modif

![image](https://user-images.githubusercontent.com/29607993/93785911-f063f800-fc2e-11ea-9f8b-c8c97c7e22c1.png)

**Comment by equinton** [comment]
Un oubli (soupir)...
Par contre, il faut conserver l'ouverture rapide avec survol, pour ceux qui en ont besoin. Pour les autres, même si ça s'affiche, ce n'est pas très grave...
