### ISSUE TITLE
2.5.0.B Type de dataset

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#422]
Bonjour

Est ce que cette fonctionnalité ne devrait pas être dans le menu paramètres de l'applicatif ?

**Comment by equinton** [comment]
Déplacé.
Une question : ne serait-il pas plus judicieux de mettre cette nouvelle fonction d'export dans le menu _Objets_, en conservant le sous-menu ?

**Comment by quidoz** [comment]
Bonjour
Tu parles du menu objets ou il y a contenant, échantillon ? si oui je ne suis pas persuadé
D'ailleurs dans ce menu, j’enlèverai tout ce qui concerne l'import et je ferai une entrée à part car un utilisateur va de demander pourquoi il y a une entrée exports des échantillons et pas d'entrée imports d'échantillon

**Comment by equinton** [comment]
J'ai remplacé l'entrée par imports/exports, et tout mis dedans.

**Comment by quidoz** [comment]
Bonjour

point de détail. Ca serait bien de mettre une majuscule à Import (et peut être à export)

**Comment by quidoz** [comment]
Bonjour

Repoint de détail. je n'aime pas le terme "dataset" - c'est pas très français mais j'avoue que jeu de données c'est pas terrible.
