### ISSUE TITLE
2.5.0.B : traducteur pour une collection ? pour un attribut d'une collection ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#424]
Bonjour

J'ai un petit souci de compréhension : un traducteur il est fonction d'une collection ? ou d'un attribut ? en gros est ce que je peux mélanger dans cet élément des traductions de différents champs (style taxon et lieu)

**Comment by equinton** [comment]
Les traducteurs servent à transcoder un libellé. Il sont utilisables avec n'importe quelle colonne exportée. 
On peut faire ce qu'on veut : un traducteur par type d'informations (taxon, lieu) ou un traducteur fonctionnel (tous les libellés pour le GBIF, par exemple). La seule contrainte, c'est que le libellé à traduire soit unique pour le traducteur considéré.
Pas de relations avec la collection, ils sont disponibles pour l'ensemble de la base de données.

**Comment by quidoz** [comment]
Bonjour

Je mets cela dans le lexique ?

**Comment by quidoz** [comment]
Bonjour

Cette entrée elle ne devrait pas être aussi dans le menu parametre ?

**Comment by equinton** [comment]
Pas vraiment, parce que les traducteurs sont spécifiques des types d'exports (des cibles). Ce n'est pas vraiment un paramètre, plutôt un fonction de l'exportation.

**Comment by equinton** [comment]
Donne-moi un libellé explicatif clair, je le rajouterai dans les popup contextuels.

**Comment by quidoz** [comment]
Bonjour

Pas d'idée. Je serai plutôt pour expliquer comment utiliser cette fonctionnalité dans le lexique

**Comment by equinton** [comment]
À tout hasard, as-tu regardé la doc dans le site web (elle est en avance de phase, je sais...) ?
[](https://www.collec-science.org/2020/08/13/exporter-les-collections-dechantillons-vers-dautres-referentiels/)

**Comment by quidoz** [comment]
Bonjour

Oui je l'avais lu avant de commencer à tester le module

**Comment by equinton** [comment]
Libellés ajoutés (ou corrigés) : 
- sur la page de saisie : 
Les tables de correspondance permettent de remplacer un libellé présent dans la base de données par un libellé attendu dans le système d'informations destinataire de l'export 
- dans le lexique : 
table de traduction : table permettant de remplacer un libellé présent dans la base de données par celui attendu par le destinataire d'un export.
- en fenêtre popup : 
Table permettant de remplacer les libellés présents dans la base de données par ceux attendus par le destinataire de l'export
