### ISSUE TITLE
2.5.0.B : echantillons - recherches enregistrées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#426]
Bonjour

Je suis arrivée à créer deux requêtes qui s'appellent pareil 

![image](https://user-images.githubusercontent.com/29607993/93472862-91804500-f8f5-11ea-8631-aeae7c6bdd1c.png)

Je trouve ce menu peu clair. Il n'y a pas jamais de bouton enregistrer la requête 

![image](https://user-images.githubusercontent.com/29607993/93472719-5a119880-f8f5-11ea-976e-cf5b56543ce8.png)

**Comment by quidoz** [comment]
Bonjour

J'ai un problème avec cette fonctionnalité. Est ce qu'elle a un lien avec les requêtes SQL : on dirait que non, mais alors comment on connait le contenu des recherches enregistrées ?

**Comment by equinton** [comment]
En fait, ça sauvegarde tous les paramètres sélectionnés dans le module de sélection. Pour voir le contenu exact, il faut passer onglet par onglet...
Sinon, pour les gestionnaires : select * from samplesearch
mais le contenu des variables est au format json...

**Comment by quidoz** [comment]
Bonjour

J'ai compris la différence entre les deux. 

par contre je trouve le menu requêtes enregistrées peu clair. 

D'une part il permet de sélectionner une requête et l'exécuter (d'ailleurs c'est après l'avoir exécutée que l'on peut accéder aux critères mis). Faudrait un peu comme putty un étape intermédiaire : charger.

D'autre part il permet d'enrgistrer la requête mais il n'y a pas de bouton enregistré.

Je me demande si un écran avec des boutons charger / sauvegarder / executer / supprimer ne serait pas plus clair

**Comment by equinton** [comment]
En fait, j'ai des contraintes techniques. Rajouter une gestion en bonne et due forme serait possible, mais demanderait pas mal de code (il faut alimenter tous les champs de l'ensemble des onglets de recherche, ce qui n'est pas une mince affaire, compte-tenu du script qui existe déjà - il y a déjà 600 lignes de code, rien que pour gérer la boite d'onglets de recherche - la page complète, avec l'affichage de la liste, c'est 1300 lignes).
Pour l'instant, on va garder le fonctionnement actuel, on verra à le faire évoluer plus tard en fonction des retours des utilisateurs.
