### ISSUE TITLE
2.5.0.D : doublon possible

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#434]
Bonjour

En parcourant le menu paramètre je suis tombée sur le menu licence (je ne connaissais pas). j'ai été étonnée de voir que les licences étaient doublées (2 CC0 2 CCBY). Mais en parcourant d'autres menus je me suis aperçue que l'on pouvait le faire de partout... A terme (quand on aura plein de trucs dans la base de données) je me demande si ça ne va poser des problèmes ...
 
![image](https://user-images.githubusercontent.com/29607993/94261191-beee7380-ff31-11ea-99eb-36231ec57976.png)

**Comment by equinton** [comment]
Le script a été lancé deux fois, il faut que tu supprimes les enregistrements en double.
Il est toujours possible de mettre des index uniques, sur les codes ou les libellés selon les tables, mais à voir...

**Comment by quidoz** [comment]
Bonjour

tu parles du script que j'ai fait passé quand j'ai installé la version 2.5.0.D ?

**Comment by equinton** [comment]
Probablement, je ne vois pas trop comment ça serait possible autrement.

**Comment by quidoz** [comment]
Bonjour

Je pense que mettre des index uniques sur certains termes seraient bien

**Comment by equinton** [comment]
Fait sur la plupart des tables de paramètres, sauf certaines qui peuvent être importées (metadata notamment) : mettre un filtre sur le nom bloquera l'importation, ce qui ira à l'encontre des besoins d'échange.
