### ISSUE TITLE
Question : utilisation de la fédération d'identité

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#435]
Bonjour

Il me semble que tu avais évoqué cette possibilité. Cela en est resté où ? Et même si ca existait est ce que ça serait possible que j'en bénéficie sur mon instance du CEFE ?

**Comment by equinton** [comment]
J'ai énormément de difficultés à aller au bout de la démarche. J'ai fait des tests avec mon pc, ça marche, à condition de rajouter un module dans Apache.
La principale difficulté tient au fait qu'il faut échanger avec la DSI, c'est elle qui enregistre l'application auprès de Renater. Et il faut que la technologie employée pour le serveur relais soit compatible.
Je butte actuellement sur le mode opératoire pour arriver à rattacher une instance à la fédération de manière simple. Si tu as quelqu'un de ta DSI qui maîtrise ce sujet, il faut lui transmettre le paragraphe 2.3.7 (page 10) du document d'installation (database/documentation/collec_installation_configuration.pdf).
