### ISSUE TITLE
l2.5.0.D : lieu géographique

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#436]
Bonjour

J'ai créé un lei géographique (amsterdam)
![image](https://user-images.githubusercontent.com/29607993/94441383-fa43a900-01a2-11eb-8b23-5e7bf665b0d3.png)

Pourquoi il ne me géolocalise pas mon point sur une carte ?

![image](https://user-images.githubusercontent.com/29607993/94441578-37a83680-01a3-11eb-8286-cec2d34473cb.png)

**Comment by equinton** [comment]
Ça fonctionne, à condition de sélectionner le lieu de prélèvement dans l'interface. Pour que les coordonnées géographiques soient reportées dans l'échantillon (et apparaissent dans la carte), il faut qu'aucune coordonnée n'existe au préalable dans l'échantillon (pour éviter l'écrasement de coordonnées qui pourraient être différentes), et sélectionner ensuite la station dotée de coordonnées.
Je l'ai testé pour l'échantillon 67626.
La procédure d'importation ne sait pas récupérer les coordonnées des stations pour les injecter dans les échantillons (pour le moment, à voir si ça vaut le coup ou non).

**Comment by quidoz** [comment]
Bonjour

Pour moi ca vaut le coup de récupérer les coordonnées géographiques dans l'échantillon. 
En plus je pense que c'est indispensable si tu veux envoyer tes données au GBIF par exemple
