### ISSUE TITLE
2.5.0.D : montée en charge -> Ca rame 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#437]
Bonjour

Je viens de créer comme contenant 50544 tubes que j'ai rangé dans 624 cryoboites qui sont dans 52 racks. C'est 1/5  du contenu de ma chambre froide. Et j'ai rentré Un peu plus de 600 échantillons
 
Je ne sais pas si mon serveur est mal configuré mais je trouve ca rame quand je fais des requêtes. C'est vrai que je fais des requetes sur les contenants (par exemple les tubes)

Tu peux te connecter sur mon instance si tu veux

**Comment by equinton** [comment]
Donne moi tes critères de recherche, il manque peut être des index

-------- Message d'origine --------

**Comment by quidoz** [comment]
Bonjour

Je cherche au niveau des contenants sur famille et type

MCQ

De : Eric Quinton <notifications@github.com>
Envoyé : lundi 28 septembre 2020 17:07
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] 2.5.0.D : montée en charge -> Ca rame (#437)

Donne moi tes critères de recherche, il manque peut être des index

-------- Message d'origine --------

**Comment by equinton** [comment]
Il faut voir combien de lignes sont retournées par la requête : plus il y en a, plus l'affichage va prendre du temps dans le navigateur. 
Je viens de faire un test sur les cryoboites, l'affichage est correct.
