### ISSUE TITLE
2.5.0.D : Nbre de slots utilisés/Nbre total

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#438]
Bonjour

Je viens de créer comme contenant 50544 tubes que j'ai rangé dans 624 cryoboites qui sont dans 52 racks. Et j'ai rentré un peu plus de 600 échantillons dans les tubes.

Au niveau des tubes, je sais s'ils sont remplis ou pas grâce à l'info "Nbre de slots utilisés/Nbre total" (NDR : j'ai un peu de mal au niveau compréhension avec cette entête de colonne mais bon). Par contre au niveau de la cryoboite 8 ils ne récupèrent pas cette info. Je pense que c'est difficile à faire mais je le signale quand même au cas où tu es une idée pour résoudre cela

![image](https://user-images.githubusercontent.com/29607993/94450726-e5b8de00-01ad-11eb-9251-1200c2ba0777.png)

![image](https://user-images.githubusercontent.com/29607993/94451332-89a28980-01ae-11eb-8f73-e738847b862a.png)

**Comment by equinton** [comment]
Le nombre total correspond au nombre de slots maximum disponibles dans un container. Ce nombre doit être renseigné dans le type de contenant. Je l'ai fait pour Cryoboite-81, et le nombre total apparaît maintenant, avec une magnifique couleur rouge si le contenant est plein.
