### ISSUE TITLE
2.5.0.D : schéma et structure de la base de données pas a jour

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#439]
Bonjour

J'ai regardé le schéma de la base de données et la structure pour faire des requêtes. 

J'ai l'impression que ce n'est pas a jour. 

J'ai l'impression que dans le schéma il manque un lien entre container et slots_used . je ne comprend pas d’ailleurs pourquoi cette dernière n'a pas de clef primaire ?

J'ai l'impression que dans la structure il manque des tables comme par exemple slots_used

**Comment by equinton** [comment]
Slot_used est une vue, qui correspond à cette requête : 
```
SELECT
   container_id, count(*) as nb_slots_used
FROM
   last_movement
WHERE
   movement_type_id = 1
   group by container_id;
```
Il n'y a pas de gestion de stockage dans la base de données, simplement des mouvements, et les contenus sont reconstitués à partir de cette table...

**Comment by equinton** [comment]
Ajout des vues à la structure de la base de données (format texte)
