### ISSUE TITLE
Ajouter la possibilité de déplacement les groupes de logins

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#446]
Bonjour

L'autre jour tu m'as dit que j’avais donné trop de droits à mes utilisateurs. Je suis en train de les déplacer mais c'est un brin laborieux. A l'occas. si tu as du temps à perdre une petite fonctionnalité pour faire cela serait la bienvenue

![image](https://user-images.githubusercontent.com/29607993/95223785-440f3d80-07fa-11eb-9e9a-b84c4c46ca86.png)

**Comment by quidoz** [comment]
je viens de m'apercevoir que je ne peux pas les récréer et les supprimer car

![image](https://user-images.githubusercontent.com/29607993/95224274-c0a21c00-07fa-11eb-9535-68d9bbab8752.png)

**Comment by equinton** [comment]
oui, pour les supprimer, il faut les virer d'abord des collections auxquelles ils sont rattachés.

Je corrige (pour cette anomalie). Pour le déplacement des groupes, on verra plus tard.

Eric Quinton
