### ISSUE TITLE
2.5.0.E : grille d'objets

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#447]
Bonjour

Les colonnes n'ont pas le bon numéro (ca devrait être 1 2 3 et non 3 2 1 

![image](https://user-images.githubusercontent.com/29607993/95351884-f4944480-08c1-11eb-83b6-00b7399cf749.png)

**Comment by equinton** [comment]
Affichage incorrect dans le détail du contenant, correct au survol de la souris
