### ISSUE TITLE
Admin : pas super utilisateur ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#448]
Bonjour

Il n'y a pas de super utilisateur dans collec ?

**Comment by equinton** [comment]
Ce terme n'existe pas. Deux droits permettent d'avoir cette fonctionnalité : admin (gestion des utilisateurs et fonctions d'administration) et param (paramétrage total du logiciel).
Un utilisateur qui appartiendrait à des groupes qui sont associés à ces deux droits aurait le statut équivalent à "super administrateur".
