### ISSUE TITLE
2.5.0.D : recherche des contenants par référent (voir par produit utilisé, condition de stockage, ...)

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#450]
Bonjour

Ca serait bien de pouvoir rechercher des contenants par référent (voir par produit utilisé, condition de stockage, ...). Pour ma part, je n'ai besoin que par référent

**Comment by equinton** [comment]
Recherche par référent uniquement, on verra s'il y a des besoins sur d'autres choses (sachant qu'on peut faire des requêtes spécifiques si besoin ponctuel).
