### ISSUE TITLE
Version 2.5.0.f : pb avec les métadonnées de type select

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#457]
Bonjour

Quand je regarde l'échantillon AMS17-YNA-001, il y a marqué MB pour le récoltant. 
![image](https://user-images.githubusercontent.com/29607993/97461449-11aab900-193e-11eb-9772-1671e2839fdf.png)

Quand je fais modifier MB semble disparaitre - pourtant il me dit que la valeur par défaut est MB 
![image](https://user-images.githubusercontent.com/29607993/97461548-26874c80-193e-11eb-9645-6e4bf34480e4.png)

Je te joins le détail de cette métadonnée
![image](https://user-images.githubusercontent.com/29607993/97461926-81b93f00-193e-11eb-9b60-78ff1581006c.png)

**Comment by equinton** [comment]
Les listes à choix multiples doivent proposer les items qui peuvent être sélectionnés. Dans la description des métadonnées, dans la zone "Choix possibles", il n'y a aucun item saisi (bouton _Add New Item_ seul, ce qui signifie qu'aucune valeur n'est sélectionnable).

Il faut d'abord saisir les différents choix, qui doivent correspondre aux données déjà présentes dans les échantillons.

**Comment by quidoz** [comment]
Bonjour
Dans le cas des récoltants, ca va être super contraignant  dans un laboratoire de la taille du CEFE de saisir les récoltants à l'avance. Et puis ca ne sert à rien car je ne veux pas les vérifier par rapport à une liste (comme je pourrais vouloir le faire pour des taxons). Est ce que cela serait possible de prévoir un type de métadonnée permettant la sélection multiple sans contrôle ?

**Comment by equinton** [comment]
Techniquement, non. Un select impose que les choix soient disponibles au préalable.

Une solution serait de saisir les récoltants en les séparant par une virgule, dans un champ quelconque. L'autre, pour une version ultérieure, serait de créer une table des récoltants, à voir.

**Comment by quidoz** [comment]
Il faudrait créer une table chaque fois que l'on veut utiliser un "select", ca ne me semble pas envisageable.
La virgule pourquoi pas (voir un /) - ca sera considéré comme un chaine et comment je peux chercher par bout de chaine, ca marcherait
