### ISSUE TITLE
Version 2.5.0.F : documents associés

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#460]
Bonjour

J'ai eu une erreur quand j'ai voulu associer un document aux réglementations
![image](https://user-images.githubusercontent.com/29607993/97984426-0e4c7d00-1dd7-11eb-8461-3047593d5c27.png)
![image](https://user-images.githubusercontent.com/29607993/97984478-1c9a9900-1dd7-11eb-961f-401252d6be77.png)

**Comment by equinton** [comment]
C'est un pb de droits à positionner pour Imagick, le logiciel qui traite les images. Voici le script à exécuter : 
```
# adjust imagick policy
sed -e "s/  <policy domain=\"coder\" rights=\"none\" pattern=\"PDF\" \/>/  <policy domain=\"coder\" rights=\"read|write\" pattern=\"PDF\" \/>/" /etc/ImageMagick-6/policy.xml > /tmp/policy.xml
cp /tmp/policy.xml /etc/ImageMagick-6/
```
Dans la pratique, il faut modiifer le fichier /etc/ImageMagick-6/policy.xml, en corrigeant ainsi cette ligne : 
~~~
  <policy domain="coder" rights="read|write" pattern="PDF" />
~~~

**Comment by quidoz** [comment]
Test OK
