### ISSUE TITLE
version 2.5.0.F : métadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#462]
Bonjour

C'est super bien que l'on puisse faire déclarer des métadonnées par type d'échantillon, que l'on puisse mettre toutes les métadonnées que l'on veut et que la recherche par métadonnée existe MAIS si on fait cela dans un laboratoire comme le CEFE où il est quasi impossible de faire se mettre d'accord les propriétaires de collection sur une liste,  ça peut devenir rapidement très difficile de se servir de ce champ pour faire de la recherche. Est ce qu'il ne serait pas envisageable de faire un peu comme pour les containers (cf ci dessous), c'est à dire aucun accès aux métadonnées si on n'a pas choisi le type d'identifiant ou alors accès à toutes les métadonnées si on n'a pas choisi de types d'échantillons ou alors accès seulement aux métadonnées de l'échantillon si on a choisi un type d'échantillon 

![image](https://user-images.githubusercontent.com/29607993/97996967-b9b1fd80-1de8-11eb-86b1-df86bd82dbf4.png)

**Comment by equinton** [comment]
Début de modification dans la branch:feature_metadatasearch
