### ISSUE TITLE
Version 2.5.0 : amélioration sur la suppression d'éléments (et peut être bug)

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#464]
Bonjour

Je suis en train de faire du ménage dans mes tests pour essayer de repartir du bon pied  (parfois je me demande si je ne devrais pas tout réinitialiser  et réintroduire que ce qui va passer en production mais la je manque un peu de temps)

Tjs est il que ce message n'est pas terrible 
![image](https://user-images.githubusercontent.com/29607993/99791926-a6ac6680-2b26-11eb-8b37-9364b9d005c2.png)
on n'a pas trop d'indication pour rechercher l'élément concerné

(dans ce cas, en plus je l'ai trouvé - c'était l"échantillon 6927). j'ai fait la modif mais il me dit toujours pareil - je fais fermer et rouvrir l'application pour voir)

**Comment by quidoz** [comment]
Bonjour

J'ai l'impression que les suppressions boguent. Je n'arrive pas non plus à détruire (et quand je recherche par ce type dans les échantillons il me répond zéro)

![image](https://user-images.githubusercontent.com/29607993/99792820-f0e21780-2b27-11eb-9539-c73b16807473.png)

**Comment by quidoz** [comment]
je retire le dernier exemple car effectivement il y a des échantillons mais il y a un truc bizarre dans l'applicatif ça ne répond pas tjs pareil. j'essaie de cerner la difficulté

**Comment by equinton** [comment]
Je t'ai créé une requête de recherche dans ton instance (que tu peux retrouver dans l'interface), il reste l'échantillon 6926 (BF10) associé à chambéry.
Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quidoz** [comment]
Il n'existe pas d'échantillon associé au 6926 su je ne dis pas de bêtise (celui que j'ai supprimé était associé au 6927)

**Comment by equinton** [comment]
Le 6926 a comme statut : détruit. Normal qu'il n'apparaisse pas dans la requête de recherche "classique" (statut pré-défini : état normal)

**Comment by quidoz** [comment]
Bien vue !
