### ISSUE TITLE
Version 2.5.0 : la suppression d'une collection est trop lente

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#466]
Bonjour

L'utilisateur a parfois des envies bizarres. par exemple supprimer toute une collection. 

C'est lent (trop lent) et je ne sais même pas si ca marche (je crois que non)
![image](https://user-images.githubusercontent.com/29607993/99954878-b674b680-2d83-11eb-9387-d6eccfd24ed1.png)

**Comment by equinton** [comment]
Effectivement, on peut avoir des temps de réponse assez longs avec la suppression de 5000 échantillons. Pour vérifier que la suppression fonctionne bien, tout désélectionner, puis cocher 2 ou 3 échantillons, et les supprimer.
Ensuite, faire des sélections par ensemble moins importants, en jouant par exemple sur les intervalles d'UID.
Une autre solution est d'écrire des requêtes de suppression, mais c'est particulièrement fastidieux : il faut supprimer tous les enregistrements liés avant d'arriver à supprimer les échantillons eux-mêmes.

**Comment by equinton** [comment]
Le code est déjà optimisé, on ne peut guère faire mieux.
