### ISSUE TITLE
version 2.5.0 : recompactage ds numéros echantillons / contenants

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#467]
Bonjour

je viens de faire du ménage de printemps - j'ai détruit tous les échantillons et je vais détruire tous les contenants. J'aurai trouvé cela propre de remettre à zéro les compteurs. C'est pas grave car je n'ai pas encore atteint le nombre max mais ca me plaisait comme idée

**Comment by equinton** [comment]
Il faut lancer ce type de requêtes, après avoir vidé les enregistrements : 
`
select setval('col.object_uid_seq', (select max(uid) from col.object));
select setval('col.sample_sample_id_seq', (select max(sample_id) from col.sample));
select setval('col.container_container_id_seq', (select max(container_id) from col.container));
select setval('col.storage_storage_id_seq', (select max(movement_id) from col.movement));
`
Ce sont les principales tables pour lesquelles cela peut avoir un intérêt.

**Comment by quidoz** [comment]
Bonjour

Je soupçonne que c'est storage_condition et non storage ?

select setval('col.storage_storage_id_seq', (select max(movement_id) from col.movement));

**Comment by equinton** [comment]
Non, c'est bien le nom de la séquence. Elle avait été créée alors que la table s'appelait storage, dans les premières versions du logiciel. Elle a été renommée ensuite en movement, mais la séquence a conservé son ancien nom.

Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quidoz** [comment]
Bonjour
    
    Bien ca ne marche pas

**Comment by quidoz** [comment]
Bonjour

C'est les UID que je voulais compacter (mais c'ets pas grave)

**Comment by quidoz** [comment]
Bonjour

Finalement je viens de m'apercevoir que si je supprime les contenants, il réutilise les UID
