### ISSUE TITLE
version 2.5.0 : destruction de contenant "impossible"

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#468]
Bonjour

Tjs dans mon ménage, j'ai besoin de détruire les 17000 microtubes que j'ai créé et qui sont inutiles. Je ne sais pas comment faire pour le faire !

**Comment by equinton** [comment]
Il existe une fonction de suppression de contenants, mais pour 18000, cela peut être fastidieux !
Il faut déjà avoir la liste des UID. Normalement, après une opération d'importation de masse, on a une trace des UID générés dans les logs, si l'import a été réalisé avec une version relativement récente (rechercher importImport ou importExec, de mémoire).

Une fois la fourchette des UID connus, le plus simple est de supprimer directement dans la base de données : 
`
begin transaction;
delete from col.movement m using col.container c where m.container_id = c.container_id and c.uid between <uid_inf> and <uid_sup>;
delete from col.movement where uid between <uid_inf> and <uid_sup>;
delete from col.container where uid between <uid_inf> and <uid_sup>;
delete from col.object where uid between <uid_inf> and <uid_sup>;
commit; (ou rollback si le résultat n'est pas satisfaisant ou en cas d'erreur)
`

**Comment by quidoz** [comment]
Bonjour

j'ai trouve cela (me reste maintenant à savoir si ce sont des échantillons ou des containers)

![image](https://user-images.githubusercontent.com/29607993/100072881-17ac9080-2e3d-11eb-8aea-191dd13924bf.png)

**Comment by quidoz** [comment]
Bonjour

Je suis arrivée à détruire avec la commande de l'uid 17083 à l'uid 67625 !

Pour une version future, ca aurait été bien que je puisse le faire depuis collec-science. Un petit menu "requete SQL" permettant de faire des modifs dans la BDD serait le bienvenu

Remarque : les requêtes dans objets sont ouvertes à tout le monde, c'est bien cela ?

**Comment by equinton** [comment]
La destruction en masse, c'est pas vraiment à mettre dans un logiciel, trop dangereux. Il y a pas mal de contrôles à faire pour vérifier que tout peut se dérouler normalement, je préfère éviter d'avoir une fonction de masse.
Quant à mettre un éditeur SQL qui permette de modifier directement la base de données, c'est non, trop dangereux. Si vous voulez le faire en mode web, utilisez pgadmin4, qui peut être monté en frontal web dans un serveur.
