### ISSUE TITLE
version 2.5.0 : groupes de login

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#472]
Bonjour

Maintenant que ma chambre froide va rentrer en service, je me préoccupe des accès. Pour l’instant j'ai trois collections qui vont rentrés dans la chambre froide : Global_ECOPATH, Mesange et EPHE_Reptiles. Pour chacune j'ai créé des groupes de logins et je leur donné le droit de collection (cf doc : rajout des types d’échantillons ou de conteneurs, import de masse). Je leur ai aussi associé un groupe avec le droit de consult (cf doc : Consultation des informations, sans possibilité de modification. Le droit de consultation doit être indiqué volontairement) pour les autres collections de la chambre froide

![image](https://user-images.githubusercontent.com/29607993/100630270-a08a6700-332a-11eb-9589-e147147a6330.png)

![image](https://user-images.githubusercontent.com/29607993/100630684-260e1700-332b-11eb-9639-3245d398b506.png)

Je suis assez étonné que les membres du groupe de login  "collections" puissent modifier les métadonnées et les campagnes. 
Par contre je suis assez embêté qu'ils ne puissent pas saisir de lieu prélèvement (à part si j'ai raté un truc dans l'import de masse).  Idem pour les campagnes . Ca veut peut être dire qu'il faut que je les mette en param plus tôt ?

**Comment by quidoz** [comment]
Bonjour

Je viens aux nouvelles. Est ce qu'il faut que je les mette en param ?

**Comment by equinton** [comment]
C'est probablement un bug de ma part, concernant la gestion des droits.

Il faut éditer le fichier param.actions.xml, et rechercher : 
samplingPlace(xxxx) pour les lieux de prélèvement
campaign(xxxx) pour les campagnes.

Dans l'attribut _droits_, il faut remplacer _param_ par _collection_.

Je corrigerai pour une future version.

**Comment by quidoz** [comment]
Bonjour

 

Tu parles d’actions.xml dans le répertoire … html/collec/param ? et je change toutes les fois que je croise « param » je met « collection » ?

Me demandes si le mieux ne serait pas que tu m’envoies un fichier corrigé 

 

A+

 

MCQ

 

       <samplingPlaceList action="modules/param/samplingPlace.php" param="list" droits="consult" retourlogin="1" type="smarty" />

        <samplingPlaceChange action="modules/param/samplingPlace.php" param="change" droits="param" retourlogin="1" type="smarty" />

        <samplingPlaceWrite action="modules/param/samplingPlace.php" param="write" droits="param" retourok="samplingPlaceList" retourko="samplingPlaceChange" modulebefore="samplingPlaceChange" />

        <samplingPlaceDelete action="modules/param/samplingPlace.php" param="delete" droits="param" retourok="samplingPlaceList" retourko="samplingPlaceChange" modulebefore="samplingPlaceChange"/>

        <samplingPlaceImport action="modules/param/samplingPlace.php" param="import" droits="param" retourok="samplingPlaceList" retourko="samplingPlaceList" modulebefore="samplingPlaceList,samplingPlaceImport"/>

        <samplingPlaceGetFromCollection action="modules/param/samplingPlace.php" param="getFromCollection" droits="gestion" type="ajax"/>

        <samplingPlaceGetCoordinate action="modules/param/samplingPlace.php" param="getCoordinate" droits="gestion" type="ajax"/>

 

    <campaignList action="modules/param/campaign.php" param="list" droits="consult" retourlogin="1" type="smarty" />

        <campaignChange action="modules/param/campaign.php" param="change" droits="collection" retourlogin="1" type="smarty" />

        <campaignDisplay action="modules/param/campaign.php" param="display" droits="consult" retourlogin="1" type="smarty"/>

        <campaignWrite action="modules/param/campaign.php" param="write" droits="collection" retourok="campaignDisplay" retourko="campaignChange" modulebefore="campaignChange" />

        <campaignDelete action="modules/param/campaign.php" param="delete" droits="collection" retourok="campaignList" retourko="campaignChange" modulebefore="campaignChange"/>

 

        <campaignRegulationChange action="modules/param/campaignRegulation.php" param="change" droits="collection" retourlogin="1" type="smarty" />

        <campaignRegulationWrite action="modules/param/campaignRegulation.php" param="write" droits="collection" modulebefore="campaignRegulationChange" retourok="campaignDisplay" retourko="campaignRegulationChange"/>

        <campaignRegulationDelete action="modules/param/campaignRegulation.php" param="delete" droits="collection" retourok="campaignDisplay" retourko="campaignRegulationChange" modulebefore="campaignRegulationChange"/>

 

 

*************************** 

Marie-Claude QUIDOZ

CEFE / CNRS

1919, Route de Mende

34293 Montpellier Cedex 5

Tel : 04 67 61 32 39

Marie-Claude.Quidoz@cefe.cnrs.fr <mailto:Marie-Claude.Quidoz@cefe.cnrs.fr> 

http://www.cefe.cnrs.fr/fr/pf/sie

 

De : Eric Quinton <notifications@github.com> 
Envoyé : lundi 14 décembre 2020 12:10
À : Irstea/collec <collec@noreply.github.com>
Cc : quidoz <marie-claude.quidoz@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] version 2.5.0 : groupes de login (#472)

 

C'est probablement un bug de ma part, concernant la gestion des droits.

Il faut éditer le fichier param.actions.xml, et rechercher :
samplingPlace(xxxx) pour les lieux de prélèvement
campaign(xxxx) pour les campagnes.

Dans l'attribut droits, il faut remplacer param par collection.

Je corrigerai pour une future version.

**Comment by equinton** [comment]
Pas trop le temps de faire la modif, là... Voici les corrections dans les paramètres : 

<samplingPlaceList action="modules/param/samplingPlace.php" param="list" droits="consult" retourlogin="1" type="smarty" />

<samplingPlaceChange action="modules/param/samplingPlace.php" param="change" droits="collection" retourlogin="1" type="smarty" />

<samplingPlaceWrite action="modules/param/samplingPlace.php" param="write" droits="collection" retourok="samplingPlaceList" retourko="samplingPlaceChange" modulebefore="samplingPlaceChange" />

<samplingPlaceDelete action="modules/param/samplingPlace.php" param="delete" droits="collection" retourok="samplingPlaceList" retourko="samplingPlaceChange" modulebefore="samplingPlaceChange"/>

<samplingPlaceImport action="modules/param/samplingPlace.php" param="import" droits="collection" retourok="samplingPlaceList" retourko="samplingPlaceList" modulebefore="samplingPlaceList,samplingPlaceImport"/>

<samplingPlaceGetFromCollection action="modules/param/samplingPlace.php" param="getFromCollection" droits="gestion" type="ajax"/>

<samplingPlaceGetCoordinate action="modules/param/samplingPlace.php" param="getCoordinate" droits="gestion" type="ajax"/>



<campaignList action="modules/param/campaign.php" param="list" droits="consult" retourlogin="1" type="smarty" />

<campaignChange action="modules/param/campaign.php" param="change" droits="collection" retourlogin="1" type="smarty" />

<campaignDisplay action="modules/param/campaign.php" param="display" droits="consult" retourlogin="1" type="smarty"/>

<campaignWrite action="modules/param/campaign.php" param="write" droits="collection" retourok="campaignDisplay" retourko="campaignChange" modulebefore="campaignChange" />

<campaignDelete action="modules/param/campaign.php" param="delete" droits="collection" retourok="campaignList" retourko="campaignChange" modulebefore="campaignChange"/>



<campaignRegulationChange action="modules/param/campaignRegulation.php" param="change" droits="collection" retourlogin="1" type="smarty" />

<campaignRegulationWrite action="modules/param/campaignRegulation.php" param="write" droits="collection" modulebefore="campaignRegulationChange" retourok="campaignDisplay" retourko="campaignRegulationChange"/>

<campaignRegulationDelete action="modules/param/campaignRegulation.php" param="delete" droits="collection" retourok="campaignDisplay" retourko="campaignRegulationChange" modulebefore="campaignRegulationChange"/>
