### ISSUE TITLE
Version 2.5.0 : Réglementations applicables

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#473]
Bonjour

Je me demande si au final on ne va pas rentrer les réglementations par type plutôt que de tous les lister. Ça ne change rien au fonctionnement mais si ma solution se confirme il faudra changer de place la rubrique à terme (et la mettre dans type de réglementation)

**Comment by equinton** [comment]
Je n'ai pas bien compris ce que tu veux faire...

**Comment by quidoz** [comment]
Bonjour

Ce que je voulais dire c’est que dans le logiciel c’est marqué nom de la réglementation (cf en dessous). Et qu’en réalité on va mettre des types de règlementation. Et que donc si ca se confirme il faudra peut être changer la localisation de cette rubrique dans le menu paramètre. 

A+

MCQ
