### ISSUE TITLE
version 2.5.0 : campagne / reglementation

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#474]
Bonjour

Je n'ai pas trouvé comment je pouvais importer en masse des informations sur les campagnes / règlementations. La seule chose que j'ai vu le taper avec mes petites mimines

**Comment by equinton** [comment]
oui, ça n'existe pas. Pas demandé jusqu'à présent...

**Comment by equinton** [comment]
Tu as beaucoup de campagnes à importer ? As-tu un fichier d'exemples ?

**Comment by quidoz** [comment]
Normalement je devrai en avoir au moins une par campagne car c'est comme cela que l'on peut rentre les réglementations. Dans le template que l'on a fait pour la chambre froide, on a fait une  feuille pour la campagne (cf 2 copies d'ecran )

![image](https://user-images.githubusercontent.com/29607993/112191988-d7042e80-8c06-11eb-9fed-86cd9638f8f6.png)
![image](https://user-images.githubusercontent.com/29607993/112192040-e71c0e00-8c06-11eb-8506-bd1b5f4eef48.png)

et on a défini 4 "reglementations"

![image](https://user-images.githubusercontent.com/29607993/112192216-0fa40800-8c07-11eb-810f-054a0a12eb1d.png)

**Comment by equinton** [comment]
On peut prévoir un module d'importation, mais il faudrait savoir avant si tu veux qu'on crée automatiquement les réglementations manquantes et les référents manquants.
Il faudra probablement que tu modifies le format du formulaire (nom des colonnes). L'importation des pièces jointes devra, de toute façon, être fait à la main.
Après, c'est intéressant d'avoir la fonction si vous avez un volume conséquent de campagnes à rentrer : la préparation des fichiers, la gestion des anomalies peut être plus chronophage que de saisir à la main.

**Comment by quidoz** [comment]
Bonjour

Je ne comprend pas ce que tu veux dire par "on crée automatiquement les réglementations manquantes et les référents manquants." SI c'est manquant pourquoi le créer ?

Pour l'instant je vais saisir ses infos à la main. On verra par la suite
