### ISSUE TITLE
Version 2.5.0 import de masse et échantillon secondaire

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#475]
Bonjour

On a possibilité de définir de nombreux identifiants au niveau d'un échantillon mais je n'ai pas trouvé comme les importer !  

MCQ

**Comment by equinton** [comment]
Décrit dans la page d'import :
Pour les identifiants complémentaires :

- repérez les codes dans le menu des paramètres > Types d'identifiants
- vous ne pouvez indiquer qu'un code par ligne (mais plusieurs types de codes possibles)
- ils seront associés à l'échantillon et au contenant, si les deux sont indiqués dans la même ligne

En gros, il faut prévoir une colonne dont l'entête est le code de l'identifiant.

Eric Quinton

**Comment by quidoz** [comment]
OK ca marche aussi pour identifiant secondaire ?

**Comment by quidoz** [comment]
Bonjour

Je ne comprend pas comment je fais pour rentrer mon identifiant_secondaire que j'ai appelé secondaire dans type d'identifiants. Je n'ia pas mois de code car je ne veux pas faire d'étiquettes 

collection_id | campaign_id | container_parent_uid | sample_identifier | Identifiant_Secondaire | sampling_date | md_annee | country_code | sampling_place_id | wgs84_y | wgs84_x | md_recoltant | md_nature | md_conservateur | md_taxon | sample_type_id | sample_status_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5 | 2 | 9936 | T6502-e1 | T6502 |   | ["2013"] | FR | 25 | 43.47506 | 6.52021 | ["Marc Cheylan"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1
5 | 2 | 9936 | T6502-e2 | T6502 |   | ["2013"] | FR | 24 | 43.47506 | 6.52021 | ["Marc Cheylan"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1
5 | 2 | 9936 | T6503-e1 | T6503 |   | ["2013"] | FR | 25 | 43.47131 | 6.5267 | ["Guillelme Astruc"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1
5 | 2 | 9936 | T6503-e2 | T6503 |   | ["2013"] | FR | 25 | 43.47131 | 6.5267 | ["Guillelme Astruc"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1

![image](https://user-images.githubusercontent.com/29607993/102246306-e6d0f000-3efe-11eb-94ec-464d483934d1.png)

**Comment by equinton** [comment]
Pour pouvoir importer des identifiants secondaires, il faut que le code soit renseigné (même si le libellé "utilisé dans les étiquettes" est, dans ce cas très précis, trompeur). Il en est de même pour pouvoir rechercher un échantillon avec ce type d'identifiant : si le code n'est pas renseigné, la recherche risque de ne pas aboutir (à vérifier toutefois).

**Comment by quidoz** [comment]
J'ai testé - ca marche 


collection_id | campaign_id | container_parent_uid | sample_column | sample_line | sample_identifier | BEV | sampling_date | md_annee
-- | -- | -- | -- | -- | -- | -- | -- | --
5 | 2 | 9936 | 1 | 1 | T6502-e1 | T6502 |   | ["2013"]
5 | 2 | 9936 | 1 | 2 | T6502-e2 | T6502 |   | ["2013"]

![image](https://user-images.githubusercontent.com/29607993/104215228-c716e400-5438-11eb-9051-b2c753e6b3ad.png)

**Comment by equinton** [comment]
Libellé modifié
