### ISSUE TITLE
version 2.5.0 : import de masse & métadonnée

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#478]
Bonjour
Il y a un bug dans l'import de masse pour les métadonnées de type array. L'importation se fait sans souci mais ca ne marche pas : le champ recoltant est vide. Tout cela car j''ai mis un espace après la virgule

**Comment by quidoz** [comment]
J'ai le fichier csv si tu veux tester

**Comment by equinton** [comment]
As-tu encore le csv qui posait problème ? Je reprends les tickets en attente.

**Comment by quidoz** [comment]
Bonjour

Je pense qu'avec ce fichier, en le trafiquant un peu (c'est à dire en mettant un espace après la virgule dans md_recoltant, tu pourrais régénérer l'erreur

[CF2_EPHE_Reptiles_cryoboites1-11_20201126_donnees.txt](https://github.com/Irstea/collec/files/6198735/CF2_EPHE_Reptiles_cryoboites1-11_20201126_donnees.txt)

**Comment by equinton** [comment]
Si les champs sont formatés avec des crochets, ils doivent respecter la norme JSON. Il est possible que ce soit lié à des apostrophes simples plutôt que des doubles apostrophes. Je n'ai pas reproduit un pb avec un espace dans cet exemple : 
["alpha","beta", "gamma"] (un espace après la seconde virgule).

J'ai rajouté le déclenchement d'une erreur lors de l'import si le décodage JSON ne s'effectue pas correctement.
