### ISSUE TITLE
version 2.5.0 : container et sample_column et sample_line

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#479]
Bonjour

Pour les cryoboites, les chercheurs préfèrent noter sur les fichiers excel des numéros allant de 1 à 81. Pour les classer avec collec science je dois faire une transformation style (je fais le faire avec R)

					Emplacement : 1 -> sample_column : 1 et sample_line : 1
					Emplacement : 2 -> sample_column : 2 et sample_line : 1
					Emplacement : 3 -> sample_column : 3 et sample_line : 1
					Emplacement : 4 -> sample_column : 4 et sample_line : 1
					Emplacement : 5 -> sample_column : 5 et sample_line : 1
					Emplacement : 6 -> sample_column : 6 et sample_line : 1
					Emplacement : 7 -> sample_column : 7 et sample_line : 1
					Emplacement : 8 -> sample_column : 8 et sample_line : 1
					Emplacement : 9 -> sample_column : 9 et sample_line : 1
					....
					Emplacement : 73 -> sample_column : 1 et sample_line : 9
					Emplacement : 74 -> sample_column : 2 et sample_line : 9
					Emplacement : 75 -> sample_column : 3 et sample_line : 9
					Emplacement : 76 -> sample_column : 4 et sample_line : 9
					Emplacement : 77 -> sample_column : 5 et sample_line : 9
					Emplacement : 78 -> sample_column : 6 et sample_line : 9
					Emplacement : 79 -> sample_column : 7 et sample_line : 9
					Emplacement : 80 -> sample_column : 8 et sample_line : 9
					Emplacement : 81 -> sample_column : 9 et sample_line : 9

Y a une autre solution ?
![image](https://user-images.githubusercontent.com/29607993/102252202-159e9480-3f06-11eb-9493-0a296c4a490e.png)

**Comment by equinton** [comment]
Il est possible d'utiliser le champ _container_location_, qui est de type "libre" : on peut saisir ce qu'on veut. Par contre, pas possible d'utiliser l'affichage en grille si on ne renseigne que ce champ.
On peut envisager d'importer non seulement la position (ligne, colonne), mais également le numéro d'ordre dans la boite.

**Comment by quidoz** [comment]
Bonjour

Quand tu écris "On peut envisager d'importer non seulement la position (ligne, colonne), mais également le numéro d'ordre dans la boite." tu veux bien dire que j'utilise la colonne container_location pour cela ?

**Comment by equinton** [comment]
Oui, position xy avec xxx_column et xxx_line, et container_location pour le numéro d'ordre
