### ISSUE TITLE
version 2.5.0 : import de masse version 2

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#480]
Bonjour

Il y a un truc qui serait vraiment bien, c'est que les modifs que je fais avec un script R soient faites directement par le logiciel.  Je ne parles pas de renommer les colonnes mais d'en remplir certaines. 

Par exemple 
- pour le nom de la collection.  Dans le fichier excel le chercheur connait le nom et par le id
- pour le numéro de la cryoboite il connait le nom mais pas son uid
- pour le nom des sites, il connait le nom mais pas son id

Ca serait vachement plus fun.

A titre d'info pour voir les manips que je fais faire pour ma chambre froide je te forwarde le fichier que j'ai envoyé à Cyril

**Comment by equinton** [comment]
Il est possible d'utiliser le module d'import "import d'échantillons externes", qui fonctionne en travaillant à partir des libellés. 
Par contre, il ne gère pas le rangement dans les contenants.
Je réfléchirai pour voir si on peut rajouter le rangement dans les contenants, mais c'est un peu complexe, pas sûr que ce soit possible.

**Comment by quidoz** [comment]
Bonjour

ET adapter l'import de masse pour travailler à parti de libellés et non de code ca te semblerait possible ?


collection_id | campaign_id | container_parent_uid | sample_column | sample_line | sample_identifier | BEV | sampling_date | md_annee | country_code | sampling_place_id | wgs84_y | wgs84_x | md_recoltant | md_nature | md_conservateur | md_taxon | sample_type_id | sample_status_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5 | 2 | 9936 | 1 | 1 | T6502-e1 | T6502 |   | ["2013"] | FR | 25 | 43.47506 | 6.52021 | ["Marc Cheylan"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1
5 | 2 | 9936 | 1 | 2 | T6502-e2 | T6502 |   | ["2013"] | FR | 24 | 43.47506 | 6.52021 | ["Marc Cheylan"] | ["ADN"] | ["tampon"] | ["Testudo hermanni hermanni"] | 12 | 1

**Comment by equinton** [comment]
Pas impossible, on verra pour la prochaine version. Il faut vérifier que tous les libellés existent bien dans la base avant de déclencher l'importation.

**Comment by equinton** [comment]
Nouvelles fonctionnalités de l'import de masse : reconnaissance des noms (strictement identiques) :
- container_type_name
- container_status_name
- collection_name
- sample_type_name
- sample_status_name
- campaign_name
- referent_name (nom prenom)

en lieu et place des id...
