### ISSUE TITLE
Version 2.5.0 : revenir à une base de données propre

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#481]
Bonjour

Dans la présentation, p. 37 il est indiqué 
il est possible de revenir à une base de données propre
- création d’un autre schéma dans la base de données
- récupération des paramètres
   - soit par export/import pour certaines informations
   - soit par recopie des données depuis le schéma de test
   
Ca m'interesse d'en savoir plus car avec tous mes tests !

**Comment by quidoz** [comment]
Bonjour

Je ne sais pas si tu as répondu à cette question ?

**Comment by equinton** [comment]
Dans ton cas de figure, si tu veux supprimer les objets (échantillons et contenants), je lancerai ça (après une sauvegarde de la base de données, il y a une fonction dans le module d'administration) : 
set search_path = col,public;
delete from object cascade;
Il faut ensuite régénérer les compteurs : 
select setval('borrowing_borrowing_id_seq', 1);
select setval('container_container_id_seq', 1);
select setval('document_document_id_seq', (select max(document_id) from document));
select setval('event_event_id_seq', 1);
select setval('object_identifier_object_identifier_id_seq', 1);
select setval('object_uid_seq', 1);
select setval('sample_sample_id_seq', 1);
select setval('storage_storage_id_seq', 1);
