### ISSUE TITLE
ldaps

### ISSUE THREAD

**Issue by totoman858** [Irstea/collec#484]
J'essaye de faire tourner l'authentification en LDAPS
en ldap (389) pas de soucis ça marche mais en ldaps (636) ça ne fonctionne pas (message d'erreur : identification refusée)
Mon param.ini comporte bien les 2 directives suivantes comme indiqué dans la doc :

$LDAP ["port" ] = 636;
$LDAP [ "tls"] = true;

J'ai peut-être raté qque chose ? Ou bien un soucis côté code ?
si vous avez une idée je suis preneur

merci !

**Comment by equinton** [comment]
La première chose à faire, c'est de vérifier que le serveur LDAP réponde bien en ldaps : 
ldapsearch uid=equinton -b "dc=mysociety,dc=com" -H ldaps://ldap.mysociety.com -x
La commande ldapsearch peut être trouvée dans le paquet ldap-utils
l'option -b correspond à la racine de recherche.

**Comment by totoman858** [comment]
oui de ce côté là pas de soucis l'annuaire est fonctionnel en ldaps
mon fichier /etc/ldap/ldap.conf est correctement configuré
Depuis le serveur web je fais correctement mon ldapsearch en ldaps :

ldapsearch -xLLL -H ldaps://ip_serveur:636 -b "$ma-racine" -D "$admin_dn" -W  

-> me retourne toutes les infos de l'annuaire ldap

**Comment by equinton** [comment]
Dans $LDAP_address, vous avez bien mis : ldaps://ip_serveur ? Il faut rajouter le s à ldap.

**Comment by totoman858** [comment]
bingo ! Effectivement il me manquait "ldaps://" à la directive $LDAP ["address" ]
ça fonctionne :)
merci beaucoup !
