### ISSUE TITLE
version 2.5.0 : trier par ordre alphanbétique les champs des métadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#485]
Bonjour

C'est un détail mais ca serait bien que  l'on ait la possibilité de trier par ordre alphabétique les champs des métadonnées

![image](https://user-images.githubusercontent.com/29607993/104344702-c6945100-54fd-11eb-9e0b-d7aa93230bea.png)

**Comment by equinton** [comment]
Pas sûr que ce soit une bonne idée... On perdrait l'ordre de création et donc de saisie des champs. Le risque serait d'avoir un champ anecdotique en première position.
Dans le formulaire de modification des métadonnées, il est toujours possible de déplacer les champs (flèches en haut de chaque item) : 
![Capture d’écran de 2021-01-12 17-53-52](https://user-images.githubusercontent.com/6715861/104346154-61415f80-54ff-11eb-8278-b2d8237577c8.png)

**Comment by quidoz** [comment]
Bonjour

L'idée n'est pas de le rendre obligatoire mais de faire comme pour les échantillons

![image](https://user-images.githubusercontent.com/29607993/104433423-5f70ae00-558a-11eb-8094-45ee9773adbe.png)
