### ISSUE TITLE
version 2.5.0 : export en csv des contenants

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#486]
Bonjour

Pour mon script R , j'ai recherché tous les contenants et je les ai exportés en csv. J'ai noté deux trucs bizarres :
- la colonne A est vide 
- certaines lignes de la colonne emplacement ont une sale gueule (ça peut venir des accents dans le nom de l'emplacement ou de la longueur trop longue du nom)

![image](https://user-images.githubusercontent.com/29607993/104473171-fb1b1200-55bc-11eb-8856-06ce7b473000.png)

**Comment by equinton** [comment]
La fonction d'export est liée au composant utilisé pour afficher le tableau : c'est le contenu exact du tableau qui est transformé en csv.
Par exemple, la première colonne ne comprend que des cases à cocher : normal qu'elle soit vide dans l'export. Et quand il y a des retours à la ligne, on les retrouve dans le fichier csv.
Le plus simple est probablement de préparer des requêtes SQL adaptées, pour ce type de besoins.
