### ISSUE TITLE
version 2.5.0 : aide pour l'écriture d'une requete SQL pour lister tous les contenants de l'instance collec-science

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#487]
Bonjour

Pour mon script R, je dois lister tous les contenants de l'instance collec-science. Après avoir testé avec une recherche classique (cf mon autre ticket), j'ai eu l'idée de faire une requête (et de l'enregistrer). Et ça marche bien. 

select * FROM col.container INNER JOIN col.object USING (uid)

Le seul souci c'est que j'ai des numéros à la place des libellés. Je m'étais lancée dans une requête plus sophistiqué mais je ne suis dit que tu l'avais déja quelque part car avec le module classique j'obtiens cela en faisant un export csv. 

Si tu veux tester en direct, n'hésites pas, ma requete s'appelle "Recherche de tous les containers de l'instance de CollecScience"

UID | Identifiant ou nom | Autres identifiants | Statut | Type | Dernier mouvement | Emplacement | Nbre de slots utilisés/Nbre total | Condition de stockage | Produit utilisé | Code CLP | Photo
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | INES_RB14 |   | État normal | Caisse/ Carton | 29/08/2019 10:46:16 | Placard_P2C8  col:1 ligne:3 | / 0 |   |   |   |  
427 | INES_RB15 |   | État normal | Caisse/ Carton | 01/07/2019 18:06:36 | Placard_P2C8  col:4 ligne:1 | / 0 |   |   |   |

**Comment by quidoz** [comment]
Peut être au final que je ne fais pas mettre les libelles dans mon fichier pour mon script R mais ca serait quand même bien d'avoir une requete avec les libelles (bonne façon de connaitre le contenu de son instance)

**Comment by quidoz** [comment]
Finalement j'ai fait celle la (que l'on pourrait mettre par défaut dans les instances de collec-science)

![image](https://user-images.githubusercontent.com/29607993/104574232-1554fe80-5656-11eb-921b-7b821973130c.png)

**Comment by equinton** [comment]
```
select uid, identifier, wgs84_x, wgs84_y,
object_status_id, object_status_name,
container_type_id, container_type_name,container_family_name,
referent_id, referent_name,
change_date, uuid, trashed, 
location_accuracy, object_comment,
container_uid, movement_date, movement_type_name, line_number, column_number, movement_reason_name
from col.object
join col.container using (uid)
join col.container_type using (container_type_id)
join col.container_family using (container_family_id)
join col.object_status using (object_status_id)
left outer join col.referent using (referent_id)
left outer join col.last_movement using (uid)
left outer join col.movement_type using (movement_type_id)
left outer join col.movement_reason using (movement_reason_id)
order by identifier,uid
```
