### ISSUE TITLE
version 2.5.0 : order by dans select 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#488]
Bonjour

J'ai l'impression que ORDER BY ne marche pas

![image](https://user-images.githubusercontent.com/29607993/104579096-d1fd8e80-565b-11eb-9819-bd9a93b265b3.png)

**Comment by equinton** [comment]
Le tri s'effectue dans le tableau, en cliquant sur les flèches pour chaque colonne. Il est possible de sélectionner plusieurs colonnes avec Ctrl + clic.
