### ISSUE TITLE
version 2.5.0 : mise à jour de postgis

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#489]
Bonjour

j'ai voulu mettre à jour la version de postgis sur ma machine collection (passage de 3.0.3 à 3.1.0) et j'ai eu le message suivant 

👍 ERREUR : ERREUR:  n'a pas pu trouver la fonction « ST_MaximumInscribedCircle » dans le fichier « /usr/lib/postgresql/12/lib/postgis-3.so »

Je suis sur postgresql 12

**Comment by equinton** [comment]
Il faudrait connaître les commandes lancées pour comprendre comment le problème est survenu, ainsi que la version exacte de l'OS du serveur.

**Comment by quidoz** [comment]
Annules mon ticket. j'avais du faire un e fausse manip.
