### ISSUE TITLE
impossible de supprimer 1 statut

### ISSUE THREAD

**Issue by astarck35310** [Irstea/collec#492]
on a bien le message "suppression confirmée" mais le statut reste dans la liste 
![image](https://user-images.githubusercontent.com/78091559/106005797-dc387780-60b4-11eb-9ab2-f03db9dd8527.png)

**Comment by astarck35310** [comment]
exemple pour suppression de "montage lame-lamelle"ID11
![image](https://user-images.githubusercontent.com/78091559/106006061-1d308c00-60b5-11eb-95b9-fa65f2bd9a33.png)

**Comment by equinton** [comment]
Il faut que le statut ne soit plus affecté à un échantillon pour qu'il puisse être supprimé (contrainte d'intégrité référentielle maintenue)
