### ISSUE TITLE
Ajouter une campagne -> message d'erreur

### ISSUE THREAD

**Issue by ojsd** [Irstea/collec#493]
Depuis le site de test, j'essaie d'ajouter une Campagne : https://demo.collec-science.inrae.fr/index.php?module=campaignChange&campaign_id=0
Je rentre un nom dans "Nom de la campagne", je ne touche pas aux 3 autres champs et je valide.

Ca me renvoit sur la page d'accueil avec le message suivant en rouge : 

> L'accès au module que vous demandez ne respecte pas la cinématique de l'application. Peut-être avez-vous essayé de rafraîchir la page ? 

J'ai exactement le même problème sur notre installation locale, qui est en 2.5.0 également.

**Comment by equinton** [comment]
Je n'ai pas réussi à reproduire l'incident : je viens de créer dans l'appli de démo la campagne test2, avec le compte de demo, en utilisant le lien fourni.

L'appli intègre un mécanisme qui vérifie que les modules d'écriture ne soient appelés qu'après l'affichage du formulaire. Cela limite les risques de "doubler" les écritures avec appui sur la touche F5, ou par des retours avec "page précédente". 
Pour aller plus loin dans le diagnostic, il faudrait me donner plus d'infos sur la suite des opérations réalisées.

**Comment by ojsd** [comment]
Je viens d'essayer avec Chromium version 87.0.4280.66 et là ça fonctionne.

Par contre j'ai l'erreur avec Firefox 85.0.1 (dernière version à ce jour), que ce soit depuis un PC sous Ubuntu 18.04 ou Windows 7.

Ce que je fais : 

1. Dans Firefox, ouverture d'une nouvelle fenêtre (en navigation privée, pour ne pas avoir d'éventuels cookies d'un précédent test)
2. https://demo.collec-science.inrae.fr/index.php
3. Clic sur connexion ([menu de gauche](https://demo.collec-science.inrae.fr/index.php?module=connexion)), login, mdp, "Se Connecter"
4. Survol de "Paramètres" (menu du haut), clic sur "Campagnes" => https://demo.collec-science.inrae.fr/index.php?module=campaignList
5. Clic sur "Nouveau..." => https://demo.collec-science.inrae.fr/index.php?module=campaignChange&campaign_id=0
6. Saisie de "test3" dans le champs "Nom de la campagne"
7. Clic sur "Valider"
8. Retour à la page https://demo.collec-science.inrae.fr/index.php, avec le message en rouge "L'accès au module que vous demandez ne respecte pas la cinématique de l'application. Peut-être avez-vous essayé de rafraîchir la page ?"

Je ne fais pas de F5 ni de page précédente/suivante.

**Comment by equinton** [comment]
Il faudrait vider le cache de Firefox : j'ai déjà eu des soucis avec l'arrivée d'une nouvelle version.
J'ai testé avec Firefox sur  mon poste, et je n'ai pas eu de souci.

**Comment by ojsd** [comment]
J'ai vidé le cache+cookies, sans succès. J'ai aussi redémarré le PC, au cas où.
J'ai essayé sur un autre poste Windows qui avait un Firefox 75.0 : pas de soucis. Puis MàJ en 85.0.1 : pas de soucis non plus...
J'ai essayé de comparer les réglages entre le Firefox qui marche et ceux qui ne marchent pas, mais je ne vois pas de différence.

Si vous avez d'autres idées, je suis preneur.
Sinon ce n'est pas très grave, ce n'est pas bloquant pour moi, je vais utiliser Chromium, peut-être que ça se résoudra automagiquement lors d'une prochaine màj de Firefox, de Collec-Science, voire d'Ubuntu.

**Comment by equinton** [comment]
Il faudrait vérifier la table gacl.log, qui comprend toutes les actions exécutées par les utilisateurs (tous les modules appelés, avec l'utilisateur et son ip). Normalement, on devrait avoir campaignChange puis campaignWrite, sans rien entre. S'il y a quelque chose entre les deux, ça peut donner une piste pour savoir où chercher.
La table log est visualisable dans votre instance en étant administrateur, dans le menu d'administration, sinon en requête sql.

**Comment by ojsd** [comment]
Il y a effectivement un "intrus" qui s'est glissé entre les commandes : col-imagescalendar-small.gifList
<a href="http://i.imgur.com/gWv1FHu.png">
  <img src="http://imgur.com/gWv1FHul.png" />
</a>
Vu le nom, je suppose que c'est le calendrier de sélection de date le fautif. 
D'ailleurs, sur Chromium et le Firefox qui fonctionne, le calendrier s'affiche quand on clique sur un champ date, par contre sur les Firefox pour lesquels l'insertion échoue, le "pop-up" calendrier ne s'affiche pas.

**Comment by ojsd** [comment]
Ah non, sur https://demo.collec-science.inrae.fr, cette règle n'est plus vraie : le calendrier s'affiche mais l'insertion est impossible...
Et là je ne peux pas voir les logs ;-)

**Comment by equinton** [comment]
Il faudrait regarder dans le navigateur, dans le mode débogueur (ctrl maj I), s'il y a un message d'erreur.

**Comment by ojsd** [comment]
Trouvé !
C'est l'extension [Dark Reader](https://addons.mozilla.org/fr/firefox/addon/darkreader/) qui bloque l'insertion... Je pense qu'elle charge la page avec le thème normal et qu'elle la recharge tout de suite derrière pour l'afficher en mode sombre (ou quelque chose comme ça), c'est probablement ça que n'aime pas Collec-science.

Et pour l'histoire du calendrier, c'est l'extension [uBlockOrigin](https://addons.mozilla.org/fr/firefox/addon/ublock-origin/) qui posait problème (les deux soucis ne sont apparemment pas liés).

J'avais beau tester sur plusieurs PC, comme je mets toujours les mêmes extensions partout ça ne changeait rien...
Problème résolu, donc.
Merci pour le debug !

**Comment by equinton** [comment]
J'avais imaginé effectivement un pb d'extension. Par contre, bizarre que uBlock est bloqué le calendrier : normalement, il n'y a pas d'appel externe.
