### ISSUE TITLE
objet prêté de retour dans la collection

### ISSUE THREAD

**Issue by astarck35310** [Irstea/collec#494]
Bonjour,
Comment faire lorsque j'ai un échantillon prêté ( statut : prêté ) qui ré-intègre la collection ? 
je change le statut en le remettant en statut normal mais comment créer le retour ? est ce que on ne pourrait pas créer un mouvement ou un évènement "retour collection" avec la date du retour, pour que ça apparaisse et qu'on puisse le voir rapidement ? 
pour l'instant , par exemple pour l'échantillon SEL_01750, je ne peux le voir que parce que j'ai mis un commentaire "retour collection le 04/03/2021" dans les détails de l'échantillon; mais ça n'apparait pas dans la liste générale, le dernier mouvement pour cet échantillon est celui du prêt le 03/12/2020 
Merci

**Comment by equinton** [comment]
Bonjour,
Vous disposez d'une fonction "prêt" d'un échantillon ou d'un contenant, qui est activable soit depuis la liste des objets (dans le menu en bas de liste), soit dans le détail d'un objet, dans l'onglet "Événement/Prêt". 
En activant cette fonction, les objets concernés (y compris les échantillons intégrés dans le contenant, par exemple les tubes d'une boite) ont leur statut qui passe à "objet prêté", et la trace du prêt est enregistrée dans une table dédiée de la base de données.
Au retour de l'échantillon ou de la boite, dans le détail, il suffit de renseigner la date de retour effective pour que le statut soit de nouveau basculé à "État normal", y  compris pour les échantillons intégrés. Il en est de même si vous créez un mouvement d'entrée : l'enregistrement du prêt sera complété avec, comme date de retour, la date du mouvement.

Je note de créer une doc à ce sujet, la fonctionnalité n'est pas forcément évidente à manipuler...

**Comment by equinton** [comment]
https://www.collec-science.org/2021/03/23/preter-un-ou-plusieurs-echantillons/
