### ISSUE TITLE
retour en grande quantité !

### ISSUE THREAD

**Issue by astarck35310** [Irstea/collec#495]
Merci de votre réponse, en fait j'avais trouvé la solution après de nombreux essais !
Maintenant , je me demande comment faire lorsque de nombreux échantillons ( par ex cette semaine : environ 1500 échantillons) réintègrent la collection tous ensemble !?
Au lieu de les traiter un par un , ne peut on pas créer dans le menu déroulant en bas de la liste un mouvement ou un évènement "retour"; il suffirait de sélectionner dans la liste des objets prêtés ceux qui réintègrent ..je ne sais pas si c'est possible , vu qu'ils ne proviennent pas de la même boite ? mais au moins avoir l'info qu'ils sont de retour...
je continue mes investigations
bonne journée

**Comment by equinton** [comment]
C'est une fonctionnalité à laquelle je n'avais pas pensé ! Bonne idée...

En fait, on peut s'en sortir assez facilement en créant un mouvement d'entrée. Dans les actions possibles sur une liste des échantillons, le menu propose : _Entrer ou déplacer les échantillons au  même emplacement_.
Cette fonctionnalité va créer le mouvement pour chacun des échantillons, et déclencher par là-même le retour.
Bien sûr, il faut que les échantillons soient rangés dans les mêmes emplacements, mais on peut toujours créer un contenant de type "en attente de rangement", pour aller plus vite.

Dites-moi si cette solution vous convient.

Cordialement,

**Comment by astarck35310** [comment]
Celà me convient tout à fait !!
Merci
