### ISSUE TITLE
notion de quantité , gestion des stocks

### ISSUE THREAD

**Issue by astarck35310** [Irstea/collec#499]
nous sommes amenés très souvent à prêter des échantillons ( 1 ou 2 ou quelques écailles )et il faut que nous sachions à tout moment combien d'écailles restent disponibles dans le sachet initial. Serait il possible de créer un statut "échantillon en faible quantité " lorsqu'il n'y a que quelques écailles  pour que lorsque je veux le prêter , en consultant la liste , je vois tout de suite si c'est possible ou pas ? ou créer une notion d'alerte  ? 
 de créer dans les prêts ( mouvements) un sous échantillon ? pour avoir toujours la notion de quantité ?
aujourd'hui, je crée un échantillon parent  75285, je crée son doublon 75285_01  en renseignant la quantité : 5; puis je fais un sous échantillonnage : sortie du stock , quantité 2 . Quand je vais dans les détails de ce 75285_01 je vois le mouvement "sortie du stock" et la quantité d'écailles restantes : 3
comment faire pour avoir toujours visible la notion de quantité ? 
comment faire pour avoir la liste des sous échantillonnages ? sans aller au coup par coup voir dans le détail de l'échantillon combien il en reste ?
remarque : quand je vais dans la liste des mouvements , ce mouvement là n'apparait pas !
merci de vos réponses

**Comment by equinton** [comment]
Pour toutes ces questions, le plus simple serait qu'on en parle en visio. Contactez-moi directement sur mon adresse pro : ***@***.***, pour qu'on se fixe un rendez-vous.

Cordialement,

Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
