### ISSUE TITLE
Script d'initialisation de la BDD à corriger

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#50]
Après test, voici un rapport complet et les suggestions de correction incluses.
Il faut corriger init_by_psql.sql et col_create_1.1.sql

 ----------------------------------------------------------------
1) Dans init_by_psql.sql
/*
 * Creation des tables dans le schema gacl
 */
\ir ./gacl_create-1.1.sql

/*
 * Creation des tables dans le schema col
 */
\ir ./col_create_1.1.sql

Christine : bug fixe
\i ne trouve pas le fichier. Il faut enlever les guillemets aussi. \ir permet de trouver le fichier relativement à la position du fichier init_by_psql.sql

----------------------------------------------------------------
2) Retour d'exécution
ROOT:siza:/home/collec/collec/install > psql -U postgres -f init_by_psql.sql
Password for user postgres:
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
You are now connected to database "collec11" as user "collec" on host "localhost" at port "5432".
CREATE SCHEMA
SET
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
INSERT 0 1
psql:gacl_create-1.1.sql:41: NOTICE:  la schéma « gacl » existe déjà, poursuite du traitement
CREATE SCHEMA
SET
CREATE TABLE
COMMENT
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
ALTER SEQUENCE
CREATE TABLE
COMMENT
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
INSERT 0 1
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
ALTER TABLE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE INDEX
CREATE INDEX
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
ALTER TABLE
INSERT 0 4
INSERT 0 4
INSERT 0 4
INSERT 0 1
 setval
--------
      1
(1 row)

 setval
--------
      1
(1 row)

 setval
--------
      5
(1 row)

 setval
--------
      1
(1 row)

 setval
--------
      5
(1 row)

CREATE SCHEMA
SET
CREATE VIEW
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
psql:col_create_1.1.sql:89: ERREUR:  la colonne « t » n'existe pas
psql:col_create_1.1.sql:90: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:91: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:92: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:93: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:94: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:95: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:97: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:100: ERREUR:  la relation « container_type » n'existe pas

CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
psql:col_create_1.1.sql:307: ERREUR:  erreur de syntaxe sur ou près de « ; »
LINE 9: ...rsion_unique" UNIQUE ("operation_name","operation_version");                                                         ^
psql:col_create_1.1.sql:308: ERREUR:  la relation « operation » n'existe pas
psql:col_create_1.1.sql:309: ERREUR:  la relation « operation » n'existe pas
psql:col_create_1.1.sql:310: ERREUR:  la relation « operation » n'existe pas
psql:col_create_1.1.sql:313: ERREUR:  la relation « operation » n'existe pas
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE TABLE
COMMENT
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
CREATE SEQUENCE
CREATE TABLE
COMMENT
COMMENT
COMMENT
ALTER SEQUENCE
psql:col_create_1.1.sql:519: ERREUR:  la relation référencée « aclgroup » n'est pas une table
ALTER TABLE
psql:col_create_1.1.sql:533: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:540: ERREUR:  la relation « container_type » n'existe pas
psql:col_create_1.1.sql:547: ERREUR:  la relation « container_type » n'existe pas
ALTER TABLE
ALTER TABLE
psql:col_create_1.1.sql:568: ERREUR:  la relation « container_type » n'existe pas
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
psql:col_create_1.1.sql:659: ERREUR:  la relation « operation » n'existe pas
psql:col_create_1.1.sql:666: ERREUR:  la relation « operation » n'existe pas
ALTER TABLE
ALTER TABLE
psql:col_create_1.1.sql:687: ERREUR:  la relation « operation » n'existe pas
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
psql:col_create_1.1.sql:722: ERREUR:  la relation « container_type » n'existe pas
ALTER TABLE
ALTER TABLE
psql:col_create_1.1.sql:743: ERREUR:  la colonne « metadata_id » référencée dans la contrainte de clé étrangère n'existe pas
ALTER TABLE
CREATE VIEW
CREATE VIEW
CREATE VIEW
INSERT 0 2
INSERT 0 14
INSERT 0 1
 setval
--------
      1
(1 row)

INSERT 0 2
 setval
--------
      2
(1 row)

psql:col_create_1.1.sql:924: ERREUR:  la relation « container_type » n'existe pas
LINE 1: insert into container_type (container_type_name, container_f...
                    ^
INSERT 0 5
INSERT 0 4
INSERT 0 4
INSERT 0 1

----------------------------------------------------------------
3) psql:col_create_1.1.sql:100: ERREUR:  la relation « container_type » n'existe pas
Christine : bug fixe : "first_line" VARCHAR DEFAULT 'T' NOT NULL,

----------------------------------------------------------------
4)psql:col_create_1.1.sql:307: ERREUR:  erreur de syntaxe sur ou près de « ; »
LINE 9: ...rsion_unique" UNIQUE ("operation_name","operation_version");

Christine : bug fixe : CONSTRAINT "operation_name_version_unique" UNIQUE ("operation_name","operation_version")
-- Supprimer le ; en fin de cette ligne 306

----------------------------------------------------------------
5)ALTER SEQUENCE
psql:col_create_1.1.sql:519: ERREUR:  la relation référencée « aclgroup » n'est pas une table

-- Christine : bug fixe
set search_path = 'col';

ALTER TABLE "project_group" ADD CONSTRAINT "aclgroup_projet_group_fk"
FOREIGN KEY ("aclgroup_id")
REFERENCES "aclgroup" ("aclgroup_id")
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

-- ERREUR:  la relation référencée « aclgroup » n'est pas une table
--- Ne peut pas fonctionner. Car aclgroup est une vue. 

-- Correction possible : référencer la table d'origine, ou bien faire une vue matérialisée

ALTER TABLE "project_group" ADD CONSTRAINT "aclgroup_projet_group_fk"
FOREIGN KEY ("aclgroup_id")
REFERENCES gacl.aclgroup ("aclgroup_id")
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

----------------------------------------------------------------
6)psql:col_create_1.1.sql:743: ERREUR:  la colonne « metadata_id » référencée dans la contrainte de clé étrangère n'existe pas
Pas de solution

----------------------------------------------------------------
7) Suppression de la base de données et re-exécution avec les corrections

psql:col_create_1.1.sql:307: ERREUR:  plusieurs valeurs par défaut sont spécifiées pour la colonne « operation_id » de la table
« operation »
LINE 2: ...('operation_operation_id_seq'::regclass) NOT NULL DEFAULT ne...
                "operation_id" INTEGER DEFAULT nextval('operation_operation_id_seq'::regclass) NOT NULL DEFAULT nextval('"operation_operation_id_seq"'),
Christine : bug fixe
Remplacer par                 
				"operation_id" INTEGER DEFAULT nextval('operation_operation_id_seq'::regclass) NOT NULL,
 

----------------------------------------------------------------
8) Suppression de la base de données et re-exécution avec les corrections

psql:col_create_1.1.sql:659: ERREUR:  la colonne « operation_id » référencée dans la contrainte de clé étrangère n'existe pas

-- label n'a plus de champs operation, mais référence un modèle de métadonnées
ALTER TABLE "label" ADD CONSTRAINT "operation_label_fk"
FOREIGN KEY ("operation_id")
REFERENCES "operation" ("operation_id")
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

psql:col_create_1.1.sql:743: ERREUR:  la colonne « metadata_id » référencée dans la contrainte de clé étrangère n'existe pas

-- sample_type n'a plus de champs metadata_id
ALTER TABLE "sample_type" ADD CONSTRAINT "metadata_sample_type_fk"
FOREIGN KEY ("metadata_id")
REFERENCES "metadata" ("metadata_id")
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

----------------------------------------------------------------
9) Suppression de la base de données et re-exécution avec les corrections
Parfait, plus de messages d'erreur.

**Comment by equinton** [comment]
Correction de l'ensemble des scripts
relecture des consignes dans chaque fichier
Test de création complet : ok
