### ISSUE TITLE
version 2.5.5 : renommer un nom dans les métadonnées

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#500]
Bonjour

Dans mes métadonnées, j'ai voulu renommer année en période. Ca s'est bien passé dans le module "paramètre". par contre la modification ne s’est pas propagée dans les métadonnées de mes échantillons. Si je visualise, j'ai toujours année et si je modifie j'ai période mais il m'a perdu la valeru que j'avais mise dans année

**Comment by equinton** [comment]
Bonjour,
Les métadonnées sont gérées dans un champ json, renommer un champ dans la description des métadonnées ne permet pas de renommer les valeurs dans les métadonnées. De plus, l'éditeur utilisé pour les métadonnées réécrit complètement celles-ci, et seuls les champs décrits sont insérés. Si on renomme un champ, à l'édition, le contenu de l'ancien champ est perdu.

Voici le script (à adapter) pour modifier un nom de champ dans l'ensemble des métadonnées :

update col.sample 
set metadata = jsonb_insert(metadata::jsonb, '{"periode"}'::text[],  (metadata->'annee' )::jsonb) - 'annee'
where metadata ->> 'annee' is not null;

Le script pour tester que ça fonctionne bien avant de faire la mise à jour :
select sample_id, uid, metadata, metadata -> 'annee',
jsonb_insert(metadata::jsonb, '{"periode"}'::text[],  (metadata->'annee' )::jsonb) - 'annee'
from col.sample where metadata ->>'annee' is not null;

**Comment by quidoz** [comment]
C a al'air d'avoir marcher !

Faudrait peut être mettre un message pour que les utilisateurs ne les modifient pas une fois des échantillons saisis

**Comment by equinton** [comment]
https://www.collec-science.org/2021/03/23/renommer-un-champ-de-metadonnees/
