### ISSUE TITLE
version 2.5.0 : grille d'objet

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#501]
Bonjour

Dans le cadre d'essai que j'avais fait pour le webinaire de décembre 2020,  j'avais mis un ordre (lignes et colonnes) pour ranger des tubes dans une cryoboite. Je voudrai maintenant enlever cet ordre (qui ne correspond pas à la "volonté" du chercheur. Je ne sais pas comment faire ...

![image](https://user-images.githubusercontent.com/29607993/112347791-77218c80-8cc7-11eb-8c10-240c5a460d9f.png)

**Comment by equinton** [comment]
Les informations sont stockées dans la table movement. Pour corriger, deux possibilités :
- recréer manuellement les mouvements d'entrée pour chacun des échantillons, en indiquant le bon emplacement pour chacun
- insérer en SQL de nouveaux mouvements pour automatiser le processus (79 mouvements à faire à la main, ça peut être fastidieux).

Pour insérer les nouveaux mouvements : 
Première étape : récupérer l'identifiant du contenant.
~~~
select container_id from col.container where uid = XXX;
~~~
où XXX correspond à l'uid du contenant.

Seconde étape : préparer une requête SQL, qui peut être construite en partie de manière automatisée : 
~~~
insert into col.movement (uid, container_id, movement_type_id, movement_date, login, column_number, line_number)
values
(12262, XXX, 1, '2021-03-25 09:30:00', 'ton_login', 3, 5),
(12263, XXX, 1, '2021-03-25 09:30:00', 'ton_login', 3, 6),
(...);
~~~
où XXX correspond au numéro du contenant récupéré précédemment, ton_login au login utilisé pour te connecter dans l'appli, 3 le numéro de colonne de rangement, 5 ou 6 le numéro de ligne de rangement.
