### ISSUE TITLE
Première connexion sur v1.1 et gestion des droits

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#51]
Message en haut, non connecté

"Le module demandé n'existe pas (collecindex.phpList) "

Puis connecté en admin (premier mot de passe : password) je n'ai le droit de rien faire. 
**A priori, modifier le nom de l'appli en 'col' dans gacl peut résoudre le problème
update gacl.aclappli set appli = 'col' where aclappli_id = 1**

En effet, je me connecte après avoir effectué cette correction. 
J'ai accès aux liste de conteneurs ou aux mouvements de stock. Par contre, impossible d’accéder à Administration ou Paramètres même après connexion.

**Comment by equinton** [comment]
Script de création des droits corrigé
