### ISSUE TITLE
version 2.6.0.a : modifier les recoltants pour anonymiser

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#510]
Bonjour

IL faudrait modifier sur la version de demo les recoltants qui apparaissent dans le container INES_RBxx et tous ceux de la collection test_MCQ. Cette information ne devrait pas apparaitre sur la version de demo (demande du proprietaire des données). Tu peux mettre un nom bidon ou ne rien mettre 

Merci

**Comment by equinton** [comment]
Fait avec le script : 

`update col.sample set metadata =  jsonb_set(metadata::jsonb, '{"recoltant"}'::text[], '[]') where metadata->'recoltant' is not null`
