### ISSUE TITLE
version 2.6.0.B : où sont passés les métadonnées ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#515]
Bonjour

C'est annoncé comme une nouveauté mais je ne les vois pas (remarque : je les ai entrevue quelque part il me semble)

![image](https://user-images.githubusercontent.com/29607993/116980170-33f30a00-acc6-11eb-8155-86f8c6269fd0.png)

**Comment by equinton** [comment]
Il faut cliquer sur "colonnes affichées" et sélectionner celles que tu veux voir
