### ISSUE TITLE
version 2.6.0.B : trier les pays par ordre alphabétique dans le module recherche ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#516]
Bonjour

J'ai voulu chercher Congo pour m'apercevoir que maintenant ça s’appelait République du congo et la je me suis aperçue que république était après Roumanie. C'est possible de trier d'une autre façon ?

**Comment by equinton** [comment]
Impossible de changer le tri. J'ai basculé le champ en "combobox", qui permet une recherche plein texte, au détriment toutefois de l'affichage (un pb que je n'arrive pas à régler).
