### ISSUE TITLE
test procedure :  Installation en mode mono-instance

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#517]
Bonjour 

Je suis en train de tester sur ma machine virtual box. J'ai exécuté le script qui a l'air de s'être bien déroulée.

Je tente de me connecter mais sans succés. C'est pas le bon nom ?

![image](https://user-images.githubusercontent.com/29607993/117310458-96453980-ae83-11eb-85c0-b869eba514e8.png)

**Comment by quidoz** [comment]
Bonjour

Non j essaieai depuis la machine virtuelle



⁣Envoyé par BlueMail ​

Le 6 mai 2021 à 16:08, à 16:08, Eric Quinton ***@***.***> a écrit:

**Comment by equinton** [comment]
Il faut alors renseigner le fichier /etc/hosts ainsi : 
`127.0.0.1	localhost collec.mysociety.com`

**Comment by quidoz** [comment]
Bonjour

Ca marche. Ca serait bien de l'indiquer dans la page https://www.collec-science.org/install/

Par contre quand j'arrive à l'écran de connexion d'accueil je n'ai pas d'info sur le compte et mot de passe à mettre.

**Comment by equinton** [comment]
admin/password

Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by quidoz** [comment]
Bonjour
Je pense que ca serait bien d'installer dans le script un outil pour interroger postgresql . Pour ma part je viens d'installer pgadmin sur mon instance virtual box

**Comment by equinton** [comment]
par défaut, on a psql qui est installé avec Postgresql, et qui fonctionne en mode texte.

Eric Quinton

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
