### ISSUE TITLE
version 2.5.0 : mettre le nombre de réponses en haut de l'écran

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#522]
Bonjour

Je reviens sur cette demande. Ca serait vraiment bien que l'on puisse savoir le nombre d'éléments retournés par une requête plutôt que d'aller voir en bas du tableau. Connaitre le nombre de réponses est un élément important de vérification.

Ca pourrait être une case à cocher qui lancerait derrière la requête

**Comment by equinton** [comment]
Ça te convient ?

![Capture d’écran de 2021-05-20 13-43-00](https://user-images.githubusercontent.com/6715861/118972955-70369380-b971-11eb-83b9-2371b621a795.png)

**Comment by quidoz** [comment]
Parfait
