### ISSUE TITLE
Utilisation dans l import de masse de la colonne "sample_parent_uid"

### ISSUE THREAD

**Issue by ofilangi** [Irstea/collec#523]
Bonjour,
Nous souhaitons utiliser l import de masse pour insérer des echantillons (status detruit) avec des echantillons crées sur celui ci 
Concretement, Nous avons une feuille qui donne un echantillons ADN (dans une plaque) et un "Liquide" dans un tube ML
Sachant que l échantillon Feuille est compris dans le fichier d'import (nous n avons donc pas l'UID), comment rempli t-on la colonne "sample_parent_uid" des 2 échantillons ADN/Tube ?

**Comment by equinton** [comment]
Bonjour,

Le logiciel n'est pas capable actuellement de créer les liens vers les parents sans leurs UID. Il faudrait que je réfléchisse à la manière d'intégrer ça dans l'import, sous réserve que l'identifiant du parent soit unique, et qu'il figure avant les échantillons enfants dans le fichier.

Pour le moment, il faut faire l'importation en plusieurs étapes : 

- importer d'abord les échantillons parents
- récupérer leurs uid (possibilité de faire un export externe sur ceux-ci, ou de lancer une requête SQL)
- incorporer les uid dans les échantillons enfants dans le fichier
- lancer l'importation des échantillons enfants 

Cordialement,

Éric Quinton.

**Comment by ofilangi** [comment]
merci pour cette precision.
Il serait intéressant d'utiliser le "container_identifier" dans une nouvelle colonne "sample_parent_identifier".
Cela permettrait d implémenter cette fonctionnalité ?
Meme en utilisant une requete SQL ou un export dans un deuxieme temps, si je veux automatiser je serais obligé de prendre le "container_identifier" comme référence et retrouver l'UID correspondant....

**Comment by equinton** [comment]
Oui, il faut que je réfléchisse à la manière de faire. Ce n'est pas si simple que ça, mais ça serait effectivement bien utile.
J'essaie de voir si je peux intégrer la fonctionnalité dans la version prévue à la fin du mois.

**Comment by equinton** [comment]
Vérifier les règles de relecture des échantillons et containers parents, il semble qu'il y ait des créations intempestives

**Comment by equinton** [comment]
Vérifié, c'est ok
