### ISSUE TITLE
Disparition d'un échantillon "Fils" suite à modification de l'échantillon "Parent"

### ISSUE THREAD

**Issue by spetek29** [Irstea/collec#525]
Bonjour,

Ce message pour vous signaler un problème / comportement de l'application (instance IUEM), auquel nous n’avions pas encore été confronté jusqu’à maintenant.

En résumé: lorsque l’on modifie la fiche d’un échantillon « Parent », l’échantillon « Fils/dérivé » disparait…

Comme vous pourrez le voir dans cette [vidéo](https://drive.google.com/file/d/1DT3DOcXy6gY9suJEWn2-9xBYZhX7IA4U/view?usp=sharing )  :
Dans notre exemple, le simple fait de modifier la masse de la poudre lyophilisée (Ac10-G13) au niveau de l’échantillon « Parent », fait disparaître l’extrait (Ac10-G13-XDM) correspondant.

Visiblement cet échantillon « Fils » est toujours dans le système, mais nous n’arrivons pas à le faire apparaître sauf au niveau de la fonctionnalité « entrer un échantillon dans un contenant », et au niveau de la liste des mouvements.

Merci d'avance pour votre éclairage concernant ce problème.

Bonne journée,

Sylvain

**Comment by equinton** [comment]
Le pb est lié à la réécriture du fils suite à la modification du père : le flag "en attente de suppression" n'est pas repositionné correctement (les métadonnées du père sont répercutées dans les fils).

En attendant la correction, dans le formulaire de recherche, il faut placer l'indicateur à "tous" : 

![Capture d’écran de 2021-06-11 12-41-07](https://user-images.githubusercontent.com/6715861/121674460-6278b780-cab2-11eb-8c9e-3aae5ccf3c16.png)

**Comment by equinton** [comment]
L'attribut object.trashed est vide au lieu d'être positionné à false

**Comment by spetek29** [comment]
Merci!!
