### ISSUE TITLE
Accès aux collections

### ISSUE THREAD

**Issue by ofilangi** [Irstea/collec#528]
Nous avons insérer une liste d’échantillon (collection "MILDIOU" qui appartient au groupe "MILDIOU").
Cette collection n'est normalement pas accessible au public

![image](https://user-images.githubusercontent.com/16104110/123063662-e8c7be80-d40d-11eb-97d7-363d62b614f1.png)

Si une personne d'un autre groupe (groupe "NEMATOLOGIE") fait une recherche par métadonnée ou par type (onglet "Type et métadonnées"), elle a accès quand même à la collection "MILDIOU".

![image](https://user-images.githubusercontent.com/16104110/123064626-ba96ae80-d40e-11eb-86f8-0321db71a5a8.png)

Ou devons nous paramétrer l'application pour y remédier ?

lien Collec-Science IGEPP : 
https://igepp.collec-science.inrae.fr/

**Comment by equinton** [comment]
Bonjour,

C'est un parti pris dans l'application : tout utilisateur référencé peut consulter un échantillon, et quelle que soit la collection d'origine, pour des questions pratiques. Par exemple, en cas de panne d'un frigo, il faut qu'il puisse enregistrer les mouvements ou consulter les infos concernant les échantillons pour savoir ce qu'ils sont, voire les risques de manipulation associés, et ce indépendamment de la collection de rattachement.

En principe, un utilisateur qui ne dispose pas des droits sur la collection ne peut pas visualiser les métadonnées ni les documents associés des échantillons qui la composent, mais a accès aux autres informations. Il est vrai que la recherche des métadonnées permet, de manière indirecte, d'accéder aux échantillons et de détecter les métadonnées par recherche successive.

Ce comportement pourrait être changé, mais il faudrait arriver à mieux qualifier le besoin pour ne pas brider la gestion au quotidien des échantillons.

À discuter, donc...

Cordialement,

Éric Quinton.
