### ISSUE TITLE
version 2.6.0a : module ? absent 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#539]
Bonjour

En français ou en anglais, quand on n'est pas connecté si on clique sur ? on obtient "Le module demandé n'existe pas (aide)"

![image](https://user-images.githubusercontent.com/29607993/129683671-2fde7c01-6f48-4327-b25c-bb6f433aa5fb.png)

**Comment by equinton** [comment]
Remplacé par l'affichage de A propos
