### ISSUE TITLE
[question] Mise à disposition des requêtes SQL aux utilisateurs 

### ISSUE THREAD

**Issue by ofilangi** [Irstea/collec#540]
Afin d'utiliser les métadonnées dans le cadre de nos projets, nous ajoutons des "Requêtes SQL" pré-enregistrées préalablement remplies par l'administrateur.
Est-il possible que l'utilisateur ai accès à ces requêtes ?

exemple sur https://igepp.collec-science.inrae.fr/ 
- "Donne le nombre d'échantillon par départements (utilisation de la métadonnée "dpt")"

**Comment by equinton** [comment]
Je vais y réfléchir, pour qu'un utilisateur puisse exécuter des requêtes prévues pour une collection donnée, sans possibilité de la modifier (sinon, on fait sauter toute la sécurité d'accès).

J'intégrerai ça dans la prochaine version.
