### ISSUE TITLE
anomalie : erreur insertion de masse

### ISSUE THREAD

**Issue by astarck35310** [Irstea/collec#554]
Quand on demande l'insertion d'un enfant dans une collection : si le numéro d'échantillon du parent existe dans une autre collection, l'enfant peut être rattaché au mauvais parent 
Il faudrait s'assurer que l'échantillon parent soit de la même collection que son enfant !! en effet dans des collections différentes, on peut avoir des mêmes numéros d'échantillons : exemple on a 302 échantillons enfants du CNICS qui ont pour parents des échantillons du Scorff..ce qui est une anomalie !
Merci !
Agnès et Nadine

**Comment by equinton** [comment]
Rajouter une option permettant de ne rechercher les parents que dans la collection de l'enfant, au moment de l'importation. Option à positionner par défaut
