### ISSUE TITLE
Bug: impossible de supprimer un échantillon multiple si l'une de ses parties est déclarée en prêt

### ISSUE THREAD

**Issue by yannickkk** [Irstea/collec#565]
Collec science interdit la suppression (droits insuffisant) et avorte donc la transaction pour des échantillons multiples dont une partie est en prêt 
 
Lorsque je cherche à supprimer l'échantillon de sang total A-20200109-3083-sang-total, j’ai le message :
 
![image](https://user-images.githubusercontent.com/39738426/158379089-134388bf-93e0-4153-929c-9ff863bc8d37.png)

En effet lorsqu’on regarde cet échantillon on a :
 
![image](https://user-images.githubusercontent.com/39738426/158379130-844c5f24-867d-4682-85e8-c952f8bca63b.png)

Comme 1 sous-échantillon a été sorti et qu’il en reste 6, je n’ai pas le droit de le supprimer.

**Comment by equinton** [comment]
cf. issue #564
