### ISSUE TITLE
Modifier le bouton d'ajout d'un échantillon

### ISSUE THREAD

**Issue by ghislainGASSIER** [Irstea/collec#568]
Bonjour,

le bouton ajouter un échantillon semble trop petit. Les gens ne le voit pas. Croît tu qu'il serai possible de le rendre plus voyant? Peut-être, un bouton rouge sur le côté droit. C'est cosmétiques, mais cela permettrai de rendre l'application intuitive/"user friendly".

Cordialement,
Ghislain

**Comment by ghislainGASSIER** [comment]
Bonjour,
J'ai deux problèmes :
1) Lorsque l'on veux associer un fichier au format archives (zip, tar,.....) Le logiciel beug.... 
2) lorsque l'on veux faire un export au format csv celui-ci ne remplit pas la colonne des parents.

Cordialement,
Ghislain

**Comment by equinton** [comment]
Voici ce que ça donne après modification : 
![Capture d’écran de 2022-03-31 11-43-42](https://user-images.githubusercontent.com/6715861/161026879-ae8b098f-f1f3-4c26-8037-e0a28510c340.png)

**Comment by ghislainGASSIER** [comment]
Bonjour et merci Eric,

Je pense qu'il est déjà plus visible. Pourrai-t'on mettre le bouton en 
relief et peut être mettre "Ajouter un nouvel échantillon" en 
grossissant le bouton. Je pense que derrière, tu doit avoir un layout 
(grid) pour disposer les boutons donc je sais que tout n'est pas 
faisable.

Merci de ta disponibilité Eric,

Cordialement,

Ghislain

Le 2022-03-31 11:45, Eric Quinton a écrit :

> Voici ce que ça donne après modification :
> [1]
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://user-images.githubusercontent.com/6715861/161026879-ae8b098f-f1f3-4c26-8037-e0a28510c340.png
[2] https://github.com/Irstea/collec/issues/568#issuecomment-1084339609
[3]
