### ISSUE TITLE
Effectuer un lot d'export 

### ISSUE THREAD

**Issue by YousraSen** [Irstea/collec#580]
Bonjour Monsieur Quinton, 

J'ai une question concernant le lot d'export. D'abord je voudrai savoir à quoi sert cette opération, ensuite je voudrai savoir comment est ce qu'on peut supprimer un lot d'export qui a été créé et qui se trouve dans liste des lots d'export. 

Je vous remercie par avance. 
Bien Cordialement, 

Yousra SENHAJI

**Comment by equinton** [comment]
Bonjour Yousra,
Les lots d'export permettent de générer des fichiers d'export "à façon", avec la mise en forme souhaitée (csv, json, xml, avec transcodage des libellés, etc.). Pour réaliser un export, il faut d'abord créer un modèle. Le même lot peut être exporté plusieurs fois, selon des modèles différents, si nécessaire.
C'est ce mécanisme qui sera utilisé pour échanger avec la cyber-carothèque.

Pour supprimer un lot d'export, il faut aller dans la rubrique _Imports/Exports > Lots d'export_, puis afficher le détail : on peut alors supprimer un lot.
Éric
