### ISSUE TITLE
Affichage pour un utilisateur de droit user 

### ISSUE THREAD

**Issue by YousraSen** [Irstea/collec#581]
Bonjour Monsieur Quinton, 

En essayant de voir l'aperçu des rubriques et des fonctionnalités dont dispose un utilisateur de droit user, j'ai remarqué qu'il a accès à la rubrique "Paramètres", ce qui me parait un peu bizarre. Ne devrait il pas avoir accès uniquement aux rubriques "objets" et "mouvements" ou "objets" et "import/export" ? 
J'ai aussi remarqué que dans l'onglet "échantillons" de la rubrique "objets", dans la liste déroulante "collections" il n'a aucun choix, autrement dit, la liste déroulante ne lui propose rien, elle est vide. 

Je vous remercie par avance. 
Bien cordialement, 

Yousra SENHAJI

**Comment by equinton** [comment]
see #577
