### ISSUE TITLE
setup email password reset for local accounts

### ISSUE THREAD

**Issue by arielzn** [Irstea/collec#584]
hello, 

i'm testing a deployed instance of collec-science 2.6.1 
we are going to use local accounts only, no ldap/cas .

I understand that for this setup we should be able to enable the possibility to reset users passwords with the email token. 

I've setup on the param.inc.php 
$MAIL_enabled = 1;
$APPLI_lostPassword = 1;

and i've configured our smtp server on the the php.ini file.

But after creating some test local accounts, when I try to use the password recovery with the email, I always see on the logs 

`[Fri May 20 14:25:16.353942 2022] [cs_code:info] [pid 10] info: Account not allowed to reset password`

i've try adding one of the test accounts to the admin group or different others, but still not working.

Which is the correct procedure to setup the email password reset for local accounts on the app ?

thanks.

**Comment by equinton** [comment]
It's probably a bug introduced in release 2.6. I'll correct it in the next version, scheduled for the next of June.
