### ISSUE TITLE
Disposer d'une visualisation des réservations actives sur un objet

### ISSUE THREAD

**Issue by cplumejeaud** [Irstea/collec#6]
COLLEC permet de réserver des objets (échantillons ou containers). Le mode réservation n'est pas contraignant : en cas de recouvrement avec une autre période de réservation sur le même objet, un avertissement prévient l'utilisateur, mais sans l'empêcher de procéder à la réservation.

Il serait pratique de disposer d'une visualisation, sous forme d'un calendrier par exemple, facilitant l'analyse des périodes libres pour la réservation d'un objet : 
- pour un objet donné
- pour une famille d'objets donnés (par projet, par site, par famille de container par exemple). Ceci permettrait d'utiliser COLLEC pour la réservation de matériel.

**Comment by equinton** [comment]
Dans le module de recherche, ajout d'une fonction de recherche sur "réservé / non réservé" pour une période donnée, permettant de retrouver les échantillons concernés
