### ISSUE TITLE
Message pas assez explicite dans la suppression de protocole

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#68]
Si on tente de supprimer un protocole avec de supprimer les opérations, le message d’erreur qui apparait n’est pas d’une lecture évidente pour un utilisateur lambda. Si on  parle le SQL, on comprend le problème

**Comment by equinton** [comment]
Dans param.inc.php, il faut basculer le paramètre $OBJETBDD_debugmode à 0 pour inhiber le message et retrouver un libellé correct.
Je modifie en conséquence le fichier param.inc.php.dist
