### ISSUE TITLE
problème de cohérence

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#69]
On a eu des surprises en changeant les valeurs des paramètres après qu’il soit utilisé – on a fait suppression et récréation et non modification – par exemple on a supprimé et ensuite récréer la valeur des types de conditions de stockage après les avoir utilisé dans type de conteneurs. L’application ne nous a rien dit mais à la fin il avait affecté des mauvaises valeurs dans les types de conteneurs. 

C’est pas très clair comme explication mais ca provient du fait (je pense) qu’il n’avait pas détruit la référence dans type de conteneur quand on a détruit les types de conditions de stockage

**Comment by equinton** [comment]
Mécanisme impossible si la base est correctement créée : il y a un contrôle d'intégrité référentielle, il n'est pas possible de supprimer une condition de stockage si elle est utilisée dans un type de container.
Il est probable que c'est le libellé qui a été modifié, et non pas un nouvel enregistrement généré.
Mode opératoire préconisé :
- créer la nouvelle condition de stockage
- faire les modifications nécessaires dans les types de containers
- supprimer les conditions de stockage obsolètes.
