### ISSUE TITLE
Accès au document associé à un protocole

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#70]
On a eu l’impression qu’il avait un bug quand on rentrait le document associé au protocole. Il a fallu se déconnecter et se reconnecter pour y avoir accès

**Comment by equinton** [comment]
Il est probable que ce soit un autre mécanisme qui ait joué. Les documents ne sont visibles que par les membres du projet.
Ce qui a dû se passer :
- ajout en admin du document
- rattachement d'un groupe (dont fait partie l'admin) au projet concerné par le protocole 
- tant que l'admin ne s'est pas reconnecté, son appartenance au projet n'a pas été recalculée (et donc pas prise en compte)
- après reconnexion, l'admin, membre du projet, peut consulter le document.
