### ISSUE TITLE
Problème de compréhension de terme

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#71]
- Statuts des objets. La liste fourni le site de d’exemple n’est pas très clair et plus particulièrement (échantillon vidé de tout contenu)
- Type d’identifiant
- Type d’échantillon et surtout sous-echantillonage (nature et unité de base)
- Base de données et U/D d’origine dans création  d’échantillon
-  Famille de conteneurs / type de conteneurs / conteneurs. Et nombre de lignes et de colonnes dans type de conteneur qui sont des éléments obligatoires.

**Comment by equinton** [comment]
Lexique en cours d'élaboration dans le wiki.
Le lexique sera intégré à la prochaine version
