### ISSUE TITLE
conteneur ou container

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#73]
Dans l'application, il est souvent écrit conteneur mais il est écrit parfois container

**Comment by exmackina** [comment]
Je rouvre ce sujet, étant en train de faire la traduction anglaise (ce qui peut amener à préciser la version française).
Dans la version **anglaise**, c'est le terme **_container_** qui est utilisé.
_Container_ en anglais peut signifier plusieurs choses en français : récipient, conteneur, contenant...
Garder le terme anglais pour la version française ne me semble pas le plus approprié. Le terme conteneur est aussi sujet à débat.
Je propose donc d'en choisir un, et je vous invite ainsi à voter (:+1:, :-1:) pour les différents termes ou à en proposer d'autres :

**Comment by exmackina** [comment]
- un **conteneur** (parfois container) en français semble plutôt associé au tri des déchets ou au transport des marchandises (sur bateau) http://www.cnrtl.fr/definition/container (conteneur n'est pas sur cnrtl.fr) voir [google image](https://www.google.fr/search?q=conteneur&safe=active&source=lnms&tbm=isch)
![conteneur recherche google](https://user-images.githubusercontent.com/26461464/41462319-c520283c-7092-11e8-8aa0-913d6b4229f1.png)

**Comment by exmackina** [comment]
- un **récipient** semble plutôt associé à la cuisine http://www.cnrtl.fr/definition/r%C3%A9cipient voir [google image](https://www.google.fr/search?q=récipient&safe=active&source=lnms&tbm=isch)
![recipient recherche google](https://user-images.githubusercontent.com/26461464/41462327-cc7eb274-7092-11e8-9acd-8720242ea47c.png)

**Comment by exmackina** [comment]
- un **contenant** semble être plus générique http://www.cnrtl.fr/definition/contenant voir [google image](https://www.google.fr/search?q=contenant&safe=active&source=lnms&tbm=isch)
![contenant recherche google](https://user-images.githubusercontent.com/26461464/41462333-d0c29e40-7092-11e8-8d70-2e720b0fa765.png)

**Comment by quidoz** [comment]
Bonjour

Je vote pour conteneur

A+

MCQ


+++++++++++++++++
Marie-Claude QUIDOZ
CEFE / CNRS
1919, Route de Mende
34293 Montpellier Cedex 5
Tel : 04 67 61 32 39
Marie-Claude.Quidoz@cefe.cnrs.fr<mailto:Marie-Claude.Quidoz@cefe.cnrs.fr>
http://www.cefe.cnrs.fr/fr/pf/sie


De : Alexandre M [mailto:notifications@github.com]
Envoyé : vendredi 15 juin 2018 11:57
À : Irstea/collec <collec@noreply.github.com>
Cc : QUIDOZ Marie-Claude <Marie-claude.QUIDOZ@cefe.cnrs.fr>; Author <author@noreply.github.com>
Objet : Re: [Irstea/collec] conteneur ou container (#73)


  *   un conteneur (parfois container) en français semble plutôt associé au tri des déchets ou au transport des marchandises (sur bateau) http://www.cnrtl.fr/definition/container (conteneur n'est pas sur cnrtl.fr) voir google image<https://www.google.fr/search?q=conteneur&safe=active&source=lnms&tbm=isch>
[conteneur recherche google]<https://user-images.githubusercontent.com/26461464/41462319-c520283c-7092-11e8-8aa0-913d6b4229f1.png>

**Comment by cplumejeaud** [comment]
Je suggère rangement.

**Comment by equinton** [comment]
rangement est trop restrictif, un tube, un sachet ne sont pas un rangement.
Conteneur ou container (anglicisme) est effectivement restrictif.
Contenant pourrait faire l'affaire. Définition du Larousse : "Ce qui contient quelque chose ; récipient, emballage"
Si on a le temps d'ici la semaine prochaine, on peut basculer vers contenant, sinon on conserve conteneur
