### ISSUE TITLE
impossible de se connecter

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#74]
Après avoir réécouter les vidéos et vérifié que c'était bon, je confirme : les comptes que j'ai créé en choisissant de définir mon propre mot de passe (Password!) ne permettent pas de s'authentifier

Ma base de données semble avoir des problèmes de cohérence - ca vient peut être de cela

**Comment by equinton** [comment]
Il y a plusieurs raisons possibles pour que ça ne fonctionne pas, et c'est peut-être à rechercher du côté de la configuration du serveur.
Y a-t-il des informations dans les traces (/var/log/apache2/) ? Un message d'erreur lors de la création ? 
Que contiennent les tables gacl.logingestion et gacl.acllogin ?
Cela peut également être un problème de droits non adéquats sur les tables du schéma gacl, pour le login utilisé pour se connecter à la base de données.

**Comment by quidoz** [comment]
Me demande s'il n'y pas un bug quand on crée un utilisateur en lui donnant un mot de passe (et non génération automatique). J'ai l'impression qu'il n'enregistre rien dans la BDD (cf en dessous)

1;"admin";"cd916028a2d8a1b901e831246dd5b9b4d3832786ddc63bbf5af4b50d9fc98f50";64;"Administrator";"";"";"";1
5;"toto";"b9156d05882ae86e2691d8ec4392b3d0dfbef948397ccc7de6d34ed63d383914";64;"toto";"toto";"toto@toto.fr";"2017-10-16";1
6;"mcq";"aa2449ade564070a423367e19793177b5dea1bed76811a31e188d92fb2398135";64;"mcq";"mcq";"marie-claude.quidoz@cefe.cnrs.fr";"2017-10-16";1
2;"quidoz";"f74ce2503b2c70d213413696151eb0852245b30a060e2e6c6723234fd40aaa59";64;"Quidoz";"Marie-Claude";"marie-claude.quidoz@cefe.cnrs.fr";"2017-10-13";1
3;"leclerc";"";;"Leclerc";"Raphaëlle";"rleclerc@cefe.cnrs.fr";"2017-10-16";1
4;"test";"";;"test";"test";"test@test.fr";"2017-10-16";1

**Comment by equinton** [comment]
Ok, vu le bug : si la zone "répétez le mot de passe" n'est pas renseignée, le compte est enregistré, mais le mot de passe n'est pas positionné.
Je corrige.
