### ISSUE TITLE
problème de cohérence de la base de donnée

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#75]
Ma base de donnée semble avoir des problèmes de cohérence. Ca serait peut être bien de prévoir dans le menu "Administration" une petite moulinette pour vérifier sa cohérence

**Comment by equinton** [comment]
???
Je ne connais pas de problèmes de cohérence dans une base de données Postgresql. 
Différentes pistes possibles:
- droits mal positionnés 
- vacuum à exécuter (mais n'interfère normalement qu'avec des problèmes de performance) - cf. https://www.collec-science.org/faq/#recherche-lente
