### ISSUE TITLE
création d'échantillon / conteneur

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#76]
Problème sans doute de compréhension. Quand j'obtiens ce message "Enregistrement effectué " après avoir fait la création d'un conteneur avec  -objet - conteneur - nouveau conteneur  - valider, est ce que ca veut dire que mon conteneur est enregistré ? je pose la question car je ne le retrouve jamais

**Comment by equinton** [comment]
Après enregistrement, rechercher s'il y a une information dans /var/log/apache2/error.log
Très probablement un pb de droits d'écriture dans les tables.

**Comment by quidoz** [comment]
Je ne vois pas de message dans les fichiers de log. Après enquête plus fine dans la base de données, cette dernière est à jour. C'est  l'interface qui ne liste rien. J'ai donc continué mon enquête et si je met "rechercher des conteneurs" avec uid entre 1 et 2, ca marche. SI je met * dans le champ uid ou identifiant , ca ne marche pas
