### ISSUE TITLE
comment faire du ménage (echantillon et collection) dans la base de données ?

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#79]
Suite aux nombreux essais que nous avons fait sur la création d'échantillon et de conteneur pensant que ces éléments n'étaient pas enregistrés (problème de l'utilisation de l'* dans le champ de recherche), nous avons semé un bazar considérable. Je peux les sortir mais ils resteront dans la base de données avec un tag.

Quelle est la meilleure solution ? (sachant que ca serait dommage de l'on perde notre paramétrage)

**Comment by equinton** [comment]
Pour garder le paramétrage, mais supprimer tous les essais : 
truncate object RESTART IDENTITY cascade;
devrait supprimer tous les échantillons et containers.
Sinon, il faut reprendre le modèle et supprimer les enregistrements les uns après les autres : 
delete from subsample
delete from sample
delete from storage
delete from container
delete from document
delete from event
delete from booking
delete from object_identifier
delete from object

**Comment by quidoz** [comment]
Ca a marché sans souci
