### ISSUE TITLE
Liste des comptes pas à jour

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#83]
J'ai fait du ménage dans ma base de données (supprimer des logins). Ca a bien marché. par contre la liste des comptes n'a pas été mise à jour

Utilisateur | Login employé
-- | --
admin | admin
Leclerc Raphaëlle | leclerc
Quidoz Marie-Claude | quidoz

login | Nom - prénom | Mail | actif
-- | -- | -- | --
admin | Administrator |   | oui
leclerc | Leclerc Raphaëlle | rleclerc@cefe.cnrs.fr | oui
mcq | mcq mcq | marie-claude.quidoz@cefe.cnrs.fr | oui 
quidoz | Quidoz Marie-Claude | marie-claude.quidoz@cefe.cnrs.fr | oui
test | test test | test@test.fr | oui
toto | toto toto | toto@toto.fr | oui

**Comment by equinton** [comment]
C'est un comportement normal actuellement.
La liste des comptes : comptes déclarés dans la base de données, et autorisés à se connecter en mode "base de données"
login : comptes déclarés dans l'application, provenant soit de la liste des comptes, soit d'un annuaire d'entreprise (connexion via annuaire LDAP ou serveur CAS ou autre).
La suppression d'un login supprime le droit d'usage dans la base de données, mais n'empêche pas la connexion.
La suppression du compte supprime la possibilité de se connecter, pas le droit d'usage.

**Comment by equinton** [comment]
Opération à réaliser : supprimer de façon croisée dans la table login ou dans la table logingestion, en fonction du cas de figure.
