### ISSUE TITLE
impossible d'envoyer des messages

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#85]
Je ne sais pas si c'est lié au faut que  mes utilisateurs sont bizarrement déclarés mais je ne epux envoyer de message. 

Pour l'un il ne me dit rien mais écrit dans le le fichier log
[Mon Nov 20 16:26:32.000000 2017] [:notice] [pid 65331] err: Account not found from mail

Pour l'autre il me "envoi impossible" et écrit dans le le fichier log
sendmail: RCPT TO:<marie-claude.quidoz@cefe.cnrs.fr> (554 5.7.1 <unknown[193.49.134.150]>: Client host rejected: Access denied)
[Mon Nov 20 16:27:11.000000 2017] [:notice] [pid 65241] err: passwordlost : send mail aborted tomarie-claude.quidoz@cefe.cnrs.fr

A noter que ma machine envoie bien des messages (j'en ai qui sont envoyes tous les soirs lors des sauvegardes)

**Comment by equinton** [comment]
Pour le premier point, il faut que l'utilisateur soit déclaré correctement dans la "liste des comptes" : le mail doit être saisi et correspondre à l'adresse du mail saisie pour la récupération du mot de passe.
Pour le second point, c'est un problème de configuration de Postfix au niveau du serveur qui héberge Apache. Il faut tester avec : 
mail -s toto@gmail.com

et valider par ctrl+s (pour sent). Tant que cette étape ne fonctionne pas, l'envoi des mails ne peut pas marcher.

**Comment by equinton** [comment]
A priori, pas lié au logiciel lui-même, sauf s'il s'agit d'une adresse mail écrite avec des majuscules (point corrigé en version 2).
