### ISSUE TITLE
message - reinitialisation mot de passe 

### ISSUE THREAD

**Issue by quidoz** [Irstea/collec#88]
Bonjour

Le message que l'on a quand on clique sur le lien de ce  message
"Vous avez demandé à réinitialiser votre mot de passe pour l'application . Si ce n'était pas le cas, contactez l'administrateur de l'application.  Pour réinitaliser votre mot de passe, recopiez le lien suivant dans votre navigateur : Réinitialisez votre mot de passe 
Ne répondez pas à ce mail, qui est généré automatiquement"

n'est pas à jour? Le mot de passe a l'air d’être de 10 caractères mimimum

Le mot de passe doit avoir une longueur minimale de 8 caractères
Il doit comprendre au minimum 3 types de caractères différents
(minuscule, majuscule, chiffre, ponctuation et autre symboles)

A+

MCQ

**Comment by equinton** [comment]
feature-import-mars18
