### ISSUE TITLE
Générer l'identifiant à partir d'informations saisies

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#97]
est il possible que le nom de l’échantillon ou l’identifiant soit généré automatiquement à partir des données rentrées dans les champs suivants : lieu de prélèvement/date/nature échantillon. est ce possible? Nous avons établi une nomenclature pour les échantillons de ce projet, ainsi que pour les fichiers de données.

(Zone atelier Moselle)

**Comment by equinton** [comment]
Possibilité de définir une règle de génération par type d'échantillon, écrite en Javascript, et déclenchée manuellement par un bouton à rajouter dans l'interface

**Comment by cplumejeaud** [comment]
- Pattern de nommage des échantillons :
 HL0709 BC01 : --> site de HL, en 2017, Septembre, ligne BC, individu 01
 <site><year><mois> <ligne><numero individu>

**Comment by cplumejeaud** [comment]
Décision du 15 janvier 2018 (réunion avec ZA Moselle)
- associer une règle de nommage écrite en javascript avec le type d'échantillon
- un formulaire Web associé permet à l'administrateur ou au gestionnaire de la collection d'éditer cette règle
- le bouton "générer l'identifiant" n'est pas obligatoire (ca pourrait être bien). Le champ IDENTIFIANT n'est pas à remplir si une règle d'écriture existe. Sinon, laisser l'utilisateur remplir le champ IDENTIFIANT. Etre sur que l'identifiant est généré avant impression de l'étiquette
- attention, un IDENTIFIANT ainsi codé devient invalide si les utilisateurs changent à postériori ses composants (par exemple, correction de la ligne de piège --> l'identifiant est encodé dans l'étiquette avec la mauvaise ligne de piège).

**Comment by equinton** [comment]
feature-database-mars18
